// examples/plugins/hello-world/src/App.tsx
import { useRef, useState, useCallback } from 'react';
import { DocxEditor, type DocxEditorRef } from '@docx-editor.dev/react';
import { PluginHost } from '@docx-editor.dev/react/plugin-api';
import { createEmptyDocument } from '@docx-editor.dev/core';
import { wordCountPlugin } from './wordCountPlugin';

export function App() {
  const editorRef = useRef<DocxEditorRef>(null);
  const [documentBuffer, setDocumentBuffer] = useState<ArrayBuffer | null>(null);

  const handleFileSelect = useCallback(async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) setDocumentBuffer(await file.arrayBuffer());
  }, []);

  return (
    <div style={{ display: 'flex', flexDirection: 'column', height: '100vh' }}>
      <header
        style={{
          display: 'flex',
          alignItems: 'center',
          gap: 12,
          padding: '10px 20px',
          background: '#fff',
          borderBottom: '1px solid #e2e8f0',
        }}
      >
        <h1 style={{ fontSize: 16, fontWeight: 600, margin: 0 }}>Hello World Plugin</h1>
        <label
          style={{
            padding: '6px 12px',
            background: '#0f172a',
            color: '#fff',
            borderRadius: 6,
            cursor: 'pointer',
            fontSize: 13,
          }}
        >
          <input
            type="file"
            accept=".docx"
            onChange={handleFileSelect}
            style={{ display: 'none' }}
          />
          Open DOCX
        </label>
      </header>

      <main style={{ flex: 1, overflow: 'hidden' }}>
        <PluginHost plugins={[wordCountPlugin]}>
          <DocxEditor
            ref={editorRef}
            document={documentBuffer ? undefined : createEmptyDocument()}
            documentBuffer={documentBuffer ?? undefined}
            showToolbar
            showRuler
          />
        </PluginHost>
      </main>
    </div>
  );
}

// examples/nuxt/app.vue
<template>
  <div class="app">
    <header class="header">
      <h1 class="title">docx-editor · Nuxt module</h1>
      <span v-if="status" class="status">{{ status }}</span>
      <label class="btn btn-primary">
        <input type="file" accept=".docx" class="file-input" @change="onFileSelect" />
        Open DOCX
      </label>
      <button class="btn" @click="onNew">New</button>
    </header>
    <main class="main">
      <!--
        <DocxEditor> is auto-imported and registered client-only by
        @docx-editor.dev/nuxt — no import or <ClientOnly> wrapper needed.
      -->
      <DocxEditor
        :document="documentBuffer ? undefined : currentDocument"
        :document-buffer="documentBuffer"
        :show-toolbar="true"
        @error="onError"
      />
    </main>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue';
import { createEmptyDocument, type Document } from '@docx-editor.dev/core';

const documentBuffer = ref<ArrayBuffer | undefined>(undefined);
const currentDocument = ref<Document | null>(null);
const status = ref('');

// Runs in the browser only — the editor never renders during SSR.
onMounted(async () => {
  try {
    const res = await fetch('/sample.docx');
    documentBuffer.value = await res.arrayBuffer();
  } catch {
    currentDocument.value = createEmptyDocument();
  }
});

async function onFileSelect(event: Event) {
  const file = (event.target as HTMLInputElement).files?.[0];
  if (!file) return;
  status.value = 'Loading…';
  try {
    const buffer = await file.arrayBuffer();
    currentDocument.value = null;
    documentBuffer.value = buffer;
    status.value = '';
  } catch {
    status.value = 'Error loading file';
  }
}

function onNew() {
  documentBuffer.value = undefined;
  currentDocument.value = createEmptyDocument();
  status.value = '';
}

function onError(error: Error) {
  console.error('Editor error:', error);
  status.value = `Error: ${error.message}`;
}
</script>

<style>
* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}
body {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
}
.app {
  display: flex;
  flex-direction: column;
  height: 100vh;
  overflow: hidden;
  background: #f8fafc;
}
.header {
  display: flex;
  align-items: center;
  gap: 12px;
  padding: 10px 16px;
  background: #fff;
  border-bottom: 1px solid #e2e8f0;
}
.title {
  font-size: 14px;
  font-weight: 600;
  color: #0f172a;
  margin-right: auto;
}
.btn {
  padding: 6px 12px;
  background: #fff;
  border: 1px solid #e2e8f0;
  border-radius: 6px;
  cursor: pointer;
  font-size: 13px;
  font-weight: 500;
  color: #334155;
}
.btn:hover {
  background: #f1f5f9;
}
.btn-primary {
  background: #0f172a;
  color: #fff;
  border-color: #0f172a;
}
.btn-primary:hover {
  background: #1e293b;
}
.file-input {
  display: none;
}
.status {
  font-size: 12px;
  color: #64748b;
  padding: 4px 8px;
  background: #f1f5f9;
  border-radius: 4px;
}
.main {
  flex: 1;
  display: flex;
  overflow: hidden;
}
</style>
