// packages/vue/src/components/PageSetupDialog.vue
<template>
  <div v-if="isOpen" class="dialog-overlay" @mousedown.self="close">
    <div class="dialog" @mousedown.stop @keydown.stop>
      <div class="dialog__header">
        <span class="dialog__title">Page Setup</span>
        <button class="dialog__close" @click="close">✕</button>
      </div>
      <div class="dialog__body">
        <!-- Page size -->
        <div class="field">
          <label class="field__label">Page size</label>
          <select v-model="selectedSize" class="field__select" @change="onSizeChange">
            <option v-for="s in pageSizes" :key="s.label" :value="s.label">{{ s.label }}</option>
            <option value="custom">Custom</option>
          </select>
        </div>

        <!-- Custom dimensions -->
        <div class="field field-row" v-if="selectedSize === 'custom'">
          <label>Width: <input v-model.number="widthInches" type="number" min="1" max="22" step="0.1" class="field__input--small" /> in</label>
          <label>Height: <input v-model.number="heightInches" type="number" min="1" max="22" step="0.1" class="field__input--small" /> in</label>
        </div>

        <!-- Orientation -->
        <div class="field">
          <label class="field__label">Orientation</label>
          <div class="orientation-group">
            <button
              class="orientation-btn"
              :class="{ active: orientation === 'portrait' }"
              @mousedown.prevent="setOrientation('portrait')"
            >📄 Portrait</button>
            <button
              class="orientation-btn"
              :class="{ active: orientation === 'landscape' }"
              @mousedown.prevent="setOrientation('landscape')"
            >📄 Landscape</button>
          </div>
        </div>

        <!-- Margins -->
        <div class="field">
          <label class="field__label">Margins (inches)</label>
          <div class="margins-grid">
            <label>Top: <input v-model.number="marginTop" type="number" min="0" max="5" step="0.1" class="field__input--small" /></label>
            <label>Bottom: <input v-model.number="marginBottom" type="number" min="0" max="5" step="0.1" class="field__input--small" /></label>
            <label>Left: <input v-model.number="marginLeft" type="number" min="0" max="5" step="0.1" class="field__input--small" /></label>
            <label>Right: <input v-model.number="marginRight" type="number" min="0" max="5" step="0.1" class="field__input--small" /></label>
          </div>
        </div>

        <div class="dialog__actions">
          <button class="dialog__btn" @click="close">Cancel</button>
          <button class="dialog__btn dialog__btn--primary" @mousedown.prevent="apply">Apply</button>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, watch } from 'vue';
import type { SectionProperties } from '@eigenpal/docx-core/types/document';

const TWIPS_PER_INCH = 1440;

const props = defineProps<{
  isOpen: boolean;
  sectionProperties?: SectionProperties | null;
}>();

const emit = defineEmits<{
  (e: 'close'): void;
  (e: 'apply', props: Partial<SectionProperties>): void;
}>();

const pageSizes = [
  { label: 'Letter (8.5" × 11")', width: 12240, height: 15840 },
  { label: 'A4 (210mm × 297mm)', width: 11906, height: 16838 },
  { label: 'Legal (8.5" × 14")', width: 12240, height: 20160 },
  { label: 'A3', width: 16838, height: 23811 },
  { label: 'A5', width: 8391, height: 11906 },
];

const selectedSize = ref('Letter (8.5" × 11")');
const orientation = ref<'portrait' | 'landscape'>('portrait');
const widthInches = ref(8.5);
const heightInches = ref(11);
const marginTop = ref(1.0);
const marginBottom = ref(1.0);
const marginLeft = ref(1.0);
const marginRight = ref(1.0);

function twipsToInches(twips: number): number {
  return Math.round((twips / TWIPS_PER_INCH) * 10) / 10;
}

function inchesToTwips(inches: number): number {
  return Math.round(inches * TWIPS_PER_INCH);
}

watch(() => props.isOpen, (open) => {
  if (!open) return;
  const sp = props.sectionProperties;
  if (sp) {
    const w = sp.pageWidth || 12240;
    const h = sp.pageHeight || 15840;
    widthInches.value = twipsToInches(w);
    heightInches.value = twipsToInches(h);
    orientation.value = w > h ? 'landscape' : 'portrait';
    marginTop.value = twipsToInches(sp.marginTop || 1440);
    marginBottom.value = twipsToInches(sp.marginBottom || 1440);
    marginLeft.value = twipsToInches(sp.marginLeft || 1440);
    marginRight.value = twipsToInches(sp.marginRight || 1440);

    // Try to match a preset
    const match = pageSizes.find(s =>
      (s.width === w && s.height === h) || (s.width === h && s.height === w)
    );
    selectedSize.value = match?.label || 'custom';
  }
});

function onSizeChange() {
  const preset = pageSizes.find(s => s.label === selectedSize.value);
  if (preset) {
    if (orientation.value === 'landscape') {
      widthInches.value = twipsToInches(preset.height);
      heightInches.value = twipsToInches(preset.width);
    } else {
      widthInches.value = twipsToInches(preset.width);
      heightInches.value = twipsToInches(preset.height);
    }
  }
}

function setOrientation(o: 'portrait' | 'landscape') {
  if (o === orientation.value) return;
  orientation.value = o;
  // Swap width and height
  const tmp = widthInches.value;
  widthInches.value = heightInches.value;
  heightInches.value = tmp;
}

function close() { emit('close'); }

function apply() {
  emit('apply', {
    pageWidth: inchesToTwips(widthInches.value),
    pageHeight: inchesToTwips(heightInches.value),
    marginTop: inchesToTwips(marginTop.value),
    marginBottom: inchesToTwips(marginBottom.value),
    marginLeft: inchesToTwips(marginLeft.value),
    marginRight: inchesToTwips(marginRight.value),
  });
  close();
}
</script>

<style scoped>
.dialog-overlay { position: fixed; inset: 0; background: rgba(0,0,0,0.3); z-index: 300; display: flex; align-items: center; justify-content: center; }
.dialog { background: #fff; border-radius: 8px; box-shadow: 0 8px 30px rgba(0,0,0,0.2); min-width: 380px; max-width: 90vw; }
.dialog__header { display: flex; align-items: center; justify-content: space-between; padding: 12px 16px; border-bottom: 1px solid #e5e7eb; }
.dialog__title { font-weight: 600; font-size: 14px; color: #1f2937; }
.dialog__close { border: none; background: transparent; cursor: pointer; font-size: 14px; color: #6b7280; width: 24px; height: 24px; display: flex; align-items: center; justify-content: center; border-radius: 4px; }
.dialog__close:hover { background: #f3f4f6; }
.dialog__body { padding: 16px; }
.dialog__actions { display: flex; justify-content: flex-end; gap: 8px; margin-top: 16px; }
.dialog__btn { padding: 6px 16px; border: 1px solid #d1d5db; border-radius: 4px; cursor: pointer; font-size: 13px; background: #fff; }
.dialog__btn--primary { background: #3b82f6; color: #fff; border-color: #3b82f6; }
.dialog__btn--primary:hover { background: #2563eb; }

.field { margin-bottom: 14px; }
.field__label { display: block; font-size: 12px; font-weight: 500; color: #374151; margin-bottom: 4px; }
.field__select { width: 100%; padding: 6px 10px; border: 1px solid #d1d5db; border-radius: 4px; font-size: 13px; background: #fff; }
.field__input--small { width: 60px; padding: 4px 6px; border: 1px solid #d1d5db; border-radius: 4px; font-size: 12px; }
.field-row { display: flex; gap: 12px; font-size: 12px; color: #4b5563; }
.orientation-group { display: flex; gap: 8px; }
.orientation-btn { padding: 8px 16px; border: 1px solid #d1d5db; border-radius: 6px; background: #fff; cursor: pointer; font-size: 13px; }
.orientation-btn.active { background: #e0e7ff; border-color: #818cf8; color: #3730a3; }
.margins-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 8px; font-size: 12px; color: #4b5563; }
</style>

// packages/react/src/components/dialogs/PageSetupDialog.tsx
/**
 * Page Setup Dialog
 *
 * Modal for editing page layout properties:
 * - Page size (Letter, A4, Legal, etc.)
 * - Orientation (portrait/landscape)
 * - Margins (top, bottom, left, right) in inches
 */

import React, { useState, useCallback, useEffect } from 'react';
import type { CSSProperties } from 'react';
import type { SectionProperties } from '@eigenpal/docx-core/types/document';
import { TWIPS_PER_INCH } from '@eigenpal/docx-core/utils';
import { useTranslation } from '../../i18n';

/** Common page sizes in twips (width x height in portrait orientation) */
const PAGE_SIZES = [
  { labelKey: 'dialogs.pageSetup.pageSizes.letter' as const, width: 12240, height: 15840 },
  { labelKey: 'dialogs.pageSetup.pageSizes.a4' as const, width: 11906, height: 16838 },
  { labelKey: 'dialogs.pageSetup.pageSizes.legal' as const, width: 12240, height: 20160 },
  { labelKey: 'dialogs.pageSetup.pageSizes.a3' as const, width: 16838, height: 23811 },
  { labelKey: 'dialogs.pageSetup.pageSizes.a5' as const, width: 8391, height: 11906 },
  { labelKey: 'dialogs.pageSetup.pageSizes.b5' as const, width: 9979, height: 14175 },
  { labelKey: 'dialogs.pageSetup.pageSizes.executive' as const, width: 10440, height: 15120 },
] as const;

// ============================================================================
// TYPES
// ============================================================================

export interface PageSetupDialogProps {
  isOpen: boolean;
  onClose: () => void;
  onApply: (props: Partial<SectionProperties>) => void;
  currentProps?: SectionProperties;
}

// ============================================================================
// HELPERS
// ============================================================================

function twipsToInches(twips: number): number {
  return Math.round((twips / TWIPS_PER_INCH) * 100) / 100;
}

function inchesToTwips(inches: number): number {
  return Math.round(inches * TWIPS_PER_INCH);
}

/** Find matching page size preset, ignoring orientation */
function findPageSizeIndex(w: number, h: number): number {
  // Normalize to portrait (smaller dimension = width)
  const pw = Math.min(w, h);
  const ph = Math.max(w, h);
  return PAGE_SIZES.findIndex((s) => Math.abs(s.width - pw) < 20 && Math.abs(s.height - ph) < 20);
}

// ============================================================================
// STYLES
// ============================================================================

const overlayStyle: CSSProperties = {
  position: 'fixed',
  top: 0,
  left: 0,
  right: 0,
  bottom: 0,
  backgroundColor: 'rgba(0, 0, 0, 0.5)',
  display: 'flex',
  alignItems: 'center',
  justifyContent: 'center',
  zIndex: 10000,
};

const dialogStyle: CSSProperties = {
  backgroundColor: 'white',
  borderRadius: 8,
  boxShadow: '0 4px 20px rgba(0, 0, 0, 0.15)',
  minWidth: 400,
  maxWidth: 480,
  width: '100%',
  margin: 20,
};

const headerStyle: CSSProperties = {
  padding: '16px 20px 12px',
  borderBottom: '1px solid var(--doc-border)',
  fontSize: 16,
  fontWeight: 600,
};

const bodyStyle: CSSProperties = {
  padding: '16px 20px',
  display: 'flex',
  flexDirection: 'column',
  gap: 14,
};

const sectionLabelStyle: CSSProperties = {
  fontSize: 12,
  fontWeight: 600,
  color: 'var(--doc-text-muted)',
  textTransform: 'uppercase',
  letterSpacing: '0.5px',
};

const rowStyle: CSSProperties = {
  display: 'flex',
  alignItems: 'center',
  gap: 12,
};

const labelStyle: CSSProperties = {
  width: 80,
  fontSize: 13,
  color: 'var(--doc-text-muted)',
};

const inputStyle: CSSProperties = {
  flex: 1,
  padding: '6px 8px',
  border: '1px solid var(--doc-border)',
  borderRadius: 4,
  fontSize: 13,
};

const selectStyle: CSSProperties = {
  ...inputStyle,
};

const unitStyle: CSSProperties = {
  fontSize: 11,
  color: 'var(--doc-text-muted)',
  width: 16,
};

const footerStyle: CSSProperties = {
  padding: '12px 20px 16px',
  borderTop: '1px solid var(--doc-border)',
  display: 'flex',
  justifyContent: 'flex-end',
  gap: 8,
};

const btnStyle: CSSProperties = {
  padding: '6px 16px',
  fontSize: 13,
  border: '1px solid var(--doc-border)',
  borderRadius: 4,
  cursor: 'pointer',
};

// ============================================================================
// COMPONENT
// ============================================================================

// Default Word values (Letter, 1" margins)
const DEFAULT_WIDTH = 12240;
const DEFAULT_HEIGHT = 15840;
const DEFAULT_MARGIN = 1440;

export function PageSetupDialog({
  isOpen,
  onClose,
  onApply,
  currentProps,
}: PageSetupDialogProps): React.ReactElement | null {
  const { t } = useTranslation();
  const [pageWidth, setPageWidth] = useState(DEFAULT_WIDTH);
  const [pageHeight, setPageHeight] = useState(DEFAULT_HEIGHT);
  const [orientation, setOrientation] = useState<'portrait' | 'landscape'>('portrait');
  const [marginTop, setMarginTop] = useState(DEFAULT_MARGIN);
  const [marginBottom, setMarginBottom] = useState(DEFAULT_MARGIN);
  const [marginLeft, setMarginLeft] = useState(DEFAULT_MARGIN);
  const [marginRight, setMarginRight] = useState(DEFAULT_MARGIN);

  useEffect(() => {
    if (!isOpen) return;
    const w = currentProps?.pageWidth || DEFAULT_WIDTH;
    const h = currentProps?.pageHeight || DEFAULT_HEIGHT;
    const orient = currentProps?.orientation || (w > h ? 'landscape' : 'portrait');
    setPageWidth(w);
    setPageHeight(h);
    setOrientation(orient);
    setMarginTop(currentProps?.marginTop ?? DEFAULT_MARGIN);
    setMarginBottom(currentProps?.marginBottom ?? DEFAULT_MARGIN);
    setMarginLeft(currentProps?.marginLeft ?? DEFAULT_MARGIN);
    setMarginRight(currentProps?.marginRight ?? DEFAULT_MARGIN);
  }, [isOpen, currentProps]);

  const handlePageSizeChange = useCallback(
    (index: number) => {
      if (index < 0) return;
      const size = PAGE_SIZES[index];
      if (orientation === 'landscape') {
        setPageWidth(size.height);
        setPageHeight(size.width);
      } else {
        setPageWidth(size.width);
        setPageHeight(size.height);
      }
    },
    [orientation]
  );

  const handleOrientationChange = useCallback(
    (newOrientation: 'portrait' | 'landscape') => {
      if (newOrientation === orientation) return;
      setOrientation(newOrientation);
      // Swap width and height
      setPageWidth(pageHeight);
      setPageHeight(pageWidth);
    },
    [orientation, pageWidth, pageHeight]
  );

  const handleApply = useCallback(() => {
    onApply({
      pageWidth,
      pageHeight,
      orientation,
      marginTop,
      marginBottom,
      marginLeft,
      marginRight,
    });
    onClose();
  }, [
    pageWidth,
    pageHeight,
    orientation,
    marginTop,
    marginBottom,
    marginLeft,
    marginRight,
    onApply,
    onClose,
  ]);

  const handleKeyDown = useCallback(
    (e: React.KeyboardEvent) => {
      if (e.key === 'Escape') onClose();
      if (e.key === 'Enter') handleApply();
    },
    [onClose, handleApply]
  );

  if (!isOpen) return null;

  const sizeIndex = findPageSizeIndex(pageWidth, pageHeight);

  return (
    <div style={overlayStyle} onClick={onClose} onKeyDown={handleKeyDown}>
      <div
        style={dialogStyle}
        onClick={(e) => e.stopPropagation()}
        onMouseDown={(e) => e.stopPropagation()}
        role="dialog"
        aria-label={t('dialogs.pageSetup.title')}
      >
        <div style={headerStyle}>{t('dialogs.pageSetup.title')}</div>

        <div style={bodyStyle}>
          {/* Page size section */}
          <div style={sectionLabelStyle}>{t('dialogs.pageSetup.pageSize')}</div>

          <div style={rowStyle}>
            <label style={labelStyle}>{t('dialogs.pageSetup.sizeLabel')}</label>
            <select
              style={selectStyle}
              value={sizeIndex}
              onChange={(e) => handlePageSizeChange(Number(e.target.value))}
            >
              {PAGE_SIZES.map((size, i) => (
                <option key={size.labelKey} value={i}>
                  {t(size.labelKey)}
                </option>
              ))}
              {sizeIndex < 0 && <option value={-1}>{t('dialogs.pageSetup.custom')}</option>}
            </select>
          </div>

          <div style={rowStyle}>
            <label style={labelStyle}>{t('dialogs.pageSetup.orientation')}</label>
            <select
              style={selectStyle}
              value={orientation}
              onChange={(e) => handleOrientationChange(e.target.value as 'portrait' | 'landscape')}
            >
              <option value="portrait">{t('dialogs.pageSetup.portrait')}</option>
              <option value="landscape">{t('dialogs.pageSetup.landscape')}</option>
            </select>
          </div>

          {/* Margins section */}
          <div style={{ ...sectionLabelStyle, marginTop: 4 }}>{t('dialogs.pageSetup.margins')}</div>

          <div style={rowStyle}>
            <label style={labelStyle}>{t('dialogs.pageSetup.top')}</label>
            <input
              type="number"
              style={inputStyle}
              min={0}
              max={10}
              step={0.1}
              value={twipsToInches(marginTop)}
              onChange={(e) => setMarginTop(inchesToTwips(Number(e.target.value) || 0))}
            />
            <span style={unitStyle}>in</span>
          </div>

          <div style={rowStyle}>
            <label style={labelStyle}>{t('dialogs.pageSetup.bottom')}</label>
            <input
              type="number"
              style={inputStyle}
              min={0}
              max={10}
              step={0.1}
              value={twipsToInches(marginBottom)}
              onChange={(e) => setMarginBottom(inchesToTwips(Number(e.target.value) || 0))}
            />
            <span style={unitStyle}>in</span>
          </div>

          <div style={rowStyle}>
            <label style={labelStyle}>{t('dialogs.pageSetup.left')}</label>
            <input
              type="number"
              style={inputStyle}
              min={0}
              max={10}
              step={0.1}
              value={twipsToInches(marginLeft)}
              onChange={(e) => setMarginLeft(inchesToTwips(Number(e.target.value) || 0))}
            />
            <span style={unitStyle}>in</span>
          </div>

          <div style={rowStyle}>
            <label style={labelStyle}>{t('dialogs.pageSetup.right')}</label>
            <input
              type="number"
              style={inputStyle}
              min={0}
              max={10}
              step={0.1}
              value={twipsToInches(marginRight)}
              onChange={(e) => setMarginRight(inchesToTwips(Number(e.target.value) || 0))}
            />
            <span style={unitStyle}>in</span>
          </div>
        </div>

        <div style={footerStyle}>
          <button type="button" style={btnStyle} onClick={onClose}>
            {t('common.cancel')}
          </button>
          <button
            type="button"
            style={{
              ...btnStyle,
              backgroundColor: 'var(--doc-primary)',
              color: 'white',
              borderColor: 'var(--doc-primary)',
            }}
            onClick={handleApply}
          >
            {t('common.apply')}
          </button>
        </div>
      </div>
    </div>
  );
}
