// packages/vue/src/editor/DocxEditorParagraphDialog.tsx
// The Paragraph dialog — the Vue twin of the React part. Alignment, indentation with its
// Special/By pair, spacing with its line-spacing rule and value, and the flags. The whole
// form is written back as ONE `setParagraphFormat` on OK, so the dialog is a single undo
// step. The host owns visibility (`open`/`onClose`); the engine owns everything else.

import {
  defineComponent,
  getCurrentInstance,
  nextTick,
  ref,
  watch,
  type CSSProperties,
  type PropType,
} from 'vue';
import { useTranslation } from '../i18n';
import { useParagraphFormat, type ParagraphTabStop } from './useParagraphFormat';
import {
  changedFields,
  formatInches,
  inchesToTwips,
  mixedFieldsOf,
  NO_MIXED_FIELDS,
  seedFields,
  trapTabWithin,
  TAB_ALIGNMENT_LABELS,
  twipsToInches,
  withTabStop,
  type ParagraphDialogFields,
  type ParagraphDialogMixed,
  type SpecialIndent,
  type TabAlignment,
  type TabLeaderName,
} from './paragraph-dialog-fields';

const refusedStyle: CSSProperties = {
  marginRight: 'auto',
  fontSize: '12px',
  color: 'var(--doc-danger)',
};

const overlayStyle: CSSProperties = {
  position: 'fixed',
  inset: 0,
  backgroundColor: 'var(--doc-overlay)',
  display: 'flex',
  alignItems: 'center',
  justifyContent: 'center',
  zIndex: 10000,
};

const dialogStyle: CSSProperties = {
  backgroundColor: 'var(--doc-surface)',
  borderRadius: '8px',
  boxShadow: '0 4px 20px var(--doc-shadow)',
  minWidth: '460px',
  maxWidth: '560px',
  width: '100%',
  margin: '20px',
  maxHeight: '90vh',
  // The panel is a column with a scrolling middle, NOT one scrolling box. Scrolling the
  // whole panel put OK and Cancel below the fold on an ordinary laptop viewport: the form
  // simply ended mid-control with no button and no scrollbar cue that more existed.
  display: 'flex',
  flexDirection: 'column',
  minHeight: 0,
};

const headerStyle: CSSProperties = {
  padding: '16px 20px 12px',
  borderBottom: '1px solid var(--doc-border)',
  flexShrink: 0,
  fontSize: '16px',
  fontWeight: 600,
  color: 'var(--doc-text)',
};

const bodyStyle: CSSProperties = {
  padding: '16px 20px',
  display: 'flex',
  flexDirection: 'column',
  gap: '14px',
  // The one part that scrolls, so the header and the buttons stay put.
  overflowY: 'auto',
  minHeight: 0,
};

const sectionLabelStyle: CSSProperties = {
  fontSize: '12px',
  fontWeight: 600,
  color: 'var(--doc-text-muted)',
  textTransform: 'uppercase',
  letterSpacing: '0.5px',
};

const rowStyle: CSSProperties = { display: 'flex', alignItems: 'center', gap: '12px' };
const labelStyle: CSSProperties = {
  width: '110px',
  fontSize: '13px',
  color: 'var(--doc-text-muted)',
};
const inputStyle: CSSProperties = {
  flex: 1,
  padding: '6px 8px',
  border: '1px solid var(--doc-border)',
  borderRadius: '4px',
  fontSize: '13px',
  backgroundColor: 'var(--doc-surface)',
  color: 'var(--doc-text)',
};
const unitStyle: CSSProperties = {
  fontSize: '11px',
  color: 'var(--doc-text-muted)',
  width: '20px',
};
const checkRowStyle: CSSProperties = {
  display: 'flex',
  alignItems: 'center',
  gap: '8px',
  fontSize: '13px',
  color: 'var(--doc-text)',
};
const footerStyle: CSSProperties = {
  padding: '12px 20px 16px',
  borderTop: '1px solid var(--doc-border)',
  display: 'flex',
  alignItems: 'center',
  justifyContent: 'flex-end',
  gap: '8px',
  flexShrink: 0,
};
const btnStyle: CSSProperties = {
  padding: '6px 16px',
  fontSize: '13px',
  border: '1px solid var(--doc-border)',
  borderRadius: '4px',
  cursor: 'pointer',
  backgroundColor: 'var(--doc-surface)',
  color: 'var(--doc-text)',
};

/** Props for `DocxEditorParagraphDialog`. @public */
export interface DocxEditorParagraphDialogProps {
  open: boolean;
  onClose: () => void;
  className?: string;
}

/** The Paragraph dialog, applied as one undoable command. @public */
export const DocxEditorParagraphDialog = defineComponent({
  name: 'DocxEditorParagraphDialog',
  props: {
    open: { type: Boolean, required: true },
    onClose: { type: Function as PropType<() => void>, required: true },
    className: { type: String, default: undefined },
  },
  setup(props) {
    const { t } = useTranslation();
    const paragraph = useParagraphFormat();

    const alignment = ref<'left' | 'center' | 'right' | 'justify'>('left');
    const indentLeft = ref(0);
    const indentRight = ref(0);
    const special = ref<SpecialIndent>('none');
    const specialBy = ref(0);
    const spaceBefore = ref(0);
    const spaceAfter = ref(0);
    const lineRule = ref<'multiple' | 'exact' | 'atLeast'>('multiple');
    const lineValue = ref(1.08);
    const contextualSpacing = ref(false);
    const keepNext = ref(false);
    const keepLines = ref(false);
    const widowControl = ref(true);
    const pageBreakBefore = ref(false);
    const tabStops = ref<readonly ParagraphTabStop[]>([]);
    const newTabPosition = ref(0);
    const newTabAlignment = ref<TabAlignment>('left');
    const newTabLeader = ref<TabLeaderName>('none');
    const seeded = ref(false);
    const seedRef = ref<ParagraphDialogFields | null>(null);
    const mixed = ref<ParagraphDialogMixed>(NO_MIXED_FIELDS);
    /** What the selection disagreed about ON OPEN, against which `mixed` says what was resolved. */
    const seedMixed = ref<ParagraphDialogMixed>(NO_MIXED_FIELDS);
    // Reached through the instance rather than a template ref: this component's vnodes are
    // hoistable, and Vue refuses a `ref` on a hoisted vnode ("Missing ref owner context"),
    // which left the dialog opening unfocused and Escape doing nothing.
    const instance = getCurrentInstance();
    const panelOf = (): HTMLElement | null => {
      const root = instance?.vnode.el;
      return root instanceof HTMLElement ? root.querySelector('[role="dialog"]') : null;
    };
    const refused = ref(false);
    // One prefix per mounted dialog, so a `<label for>` points at THIS dialog's input even
    // when a host renders two. Clicking a visible label is how a pointer user hits a small
    // control, and `aria-label` alone does not give them that. React uses `useId`; Vue has
    // no equivalent, and the instance uid is already unique per component.
    const fieldId = `docx-paragraph-${instance?.uid ?? 0}`;
    // Seed from the selection when the dialog OPENS — not on every tick, or a concurrent
    // edit would fight the user's typing.
    watch(
      () => [props.open, paragraph.format.value] as const,
      ([open, format]) => {
        if (!open) {
          seeded.value = false;
          // Closing deliberately does NOT hand focus back to the document; see the note on
          // the React twin's focus effect for the three mechanisms that were tried and why
          // each was worse than leaving the document alone.
          return;
        }
        if (seeded.value || format === null) return;
        const seed = seedFields(format);
        alignment.value = seed.alignment;
        indentLeft.value = seed.indentLeft;
        indentRight.value = seed.indentRight;
        special.value = seed.special;
        specialBy.value = seed.specialBy;
        spaceBefore.value = seed.spaceBefore;
        spaceAfter.value = seed.spaceAfter;
        lineRule.value = seed.lineRule;
        lineValue.value = seed.lineValue;
        // A `null` flag means the selection DISAGREES. The box opens unchecked and shows
        // indeterminate; `seedRef` remembers it so an untouched flag is not written.
        contextualSpacing.value = seed.contextualSpacing;
        keepNext.value = seed.keepNext;
        keepLines.value = seed.keepLines;
        widowControl.value = seed.widowControl;
        pageBreakBefore.value = seed.pageBreakBefore;
        tabStops.value = seed.tabStops;
        mixed.value = mixedFieldsOf(format);
        seedMixed.value = mixed.value;
        refused.value = false;
        seedRef.value = seed;
        seeded.value = true;
        // Focus the panel so Escape reaches the overlay's key handler. Without it the
        // dialog cannot be dismissed from the keyboard until the user tabs into it.
        // The selection the dialog is ABOUT. Typing in any field moves the DOM selection
        // into that input, so by the time the dialog closes the document has none — and
        // focusing a surface with no selection puts the caret at the top.
        void nextTick(() => panelOf()?.focus());
      },
      { immediate: true }
    );

    /** Add or replace the stop at this position — "Set" replaces one already there. */
    const setTabStop = (): void => {
      mixed.value = { ...mixed.value, tabStops: false };
      tabStops.value = withTabStop(tabStops.value, {
        positionTwips: Math.round(newTabPosition.value),
        alignment: newTabAlignment.value,
        ...(newTabLeader.value !== 'none' ? { leader: newTabLeader.value } : {}),
      });
    };

    const handleApply = (): void => {
      const seed = seedRef.value;
      const update =
        seed === null
          ? null
          : changedFields(
              seed,
              {
                alignment: alignment.value,
                indentLeft: indentLeft.value,
                indentRight: indentRight.value,
                special: special.value,
                specialBy: specialBy.value,
                spaceBefore: spaceBefore.value,
                spaceAfter: spaceAfter.value,
                lineRule: lineRule.value,
                lineValue: lineValue.value,
                contextualSpacing: contextualSpacing.value,
                keepNext: keepNext.value,
                keepLines: keepLines.value,
                widowControl: widowControl.value,
                pageBreakBefore: pageBreakBefore.value,
                tabStops: tabStops.value,
              },
              seedMixed.value,
              mixed.value
            );
      // Nothing moved, so there is nothing to write. Closing is the whole job.
      if (update === null) {
        props.onClose();
        return;
      }
      // A refused write keeps the dialog OPEN rather than claiming a success that did not
      // happen. It has to SAY so — a dialog that swallows the OK and sits there looks
      // broken rather than refused.
      if (paragraph.apply(update)) {
        refused.value = false;
        props.onClose();
        return;
      }
      refused.value = true;
    };

    return () => {
      if (!props.open) return null;

      const inchRow = (
        labelKey: 'beforeText' | 'afterText' | 'by' | 'tabPosition',
        value: number,
        set: (twips: number) => void
      ) => (
        <div style={rowStyle}>
          <label style={labelStyle} for={`${fieldId}-${labelKey}`}>
            {t(`dialogs.paragraph.${labelKey}`)}
          </label>
          <input
            id={`${fieldId}-${labelKey}`}
            type="number"
            style={inputStyle}
            step="0.1"
            value={twipsToInches(value)}
            onInput={(event) =>
              set(inchesToTwips(Number((event.target as HTMLInputElement).value) || 0))
            }
            aria-label={t(`dialogs.paragraph.${labelKey}`)}
          />
          <span style={unitStyle}>{t('dialogs.paragraph.unitInches')}</span>
        </div>
      );

      const pointRow = (
        labelKey: 'spaceBefore' | 'spaceAfter',
        value: number,
        set: (points: number) => void
      ) => (
        <div style={rowStyle}>
          <label style={labelStyle} for={`${fieldId}-${labelKey}`}>
            {t(`dialogs.paragraph.${labelKey}`)}
          </label>
          <input
            id={`${fieldId}-${labelKey}`}
            type="number"
            style={inputStyle}
            min="0"
            step="1"
            value={value}
            onInput={(event) =>
              set(Math.max(0, Number((event.target as HTMLInputElement).value) || 0))
            }
            aria-label={t(`dialogs.paragraph.${labelKey}`)}
          />
          <span style={unitStyle}>{t('dialogs.paragraph.unitPoints')}</span>
        </div>
      );

      const checkbox = (
        labelKey: keyof ParagraphDialogMixed,
        checked: boolean,
        set: (next: boolean) => void
      ) => (
        <label style={checkRowStyle}>
          <input
            type="checkbox"
            checked={checked}
            // A setting the selection disagrees about is INDETERMINATE, not unchecked —
            // unchecked would claim the paragraphs agree it is off. `indeterminate` is a
            // DOM property with no attribute, so it is bound with Vue's `.` prefix, which
            // patches it as a property rather than as markup.
            {...{ '.indeterminate': mixed.value[labelKey] }}
            onChange={(event) => {
              // Touching the box RESOLVES the disagreement: from here it means what it shows.
              mixed.value = { ...mixed.value, [labelKey]: false };
              set((event.target as HTMLInputElement).checked);
            }}
          />
          {t(`dialogs.paragraph.${labelKey}`)}
        </label>
      );

      return (
        <div
          class={props.className}
          style={overlayStyle}
          onClick={props.onClose}
          onKeydown={(event: KeyboardEvent) => {
            if (event.key === 'Escape') props.onClose();
            const panel = panelOf();
            if (panel && trapTabWithin(panel, event)) event.preventDefault();
            // Enter is the form's default submit, EXCEPT on a control that owns the key: a
            // button acts on the Enter that focused it, and keydown here runs first, so
            // Cancel pressed from the keyboard would otherwise apply the form first.
            if (event.key === 'Enter' && !(event.target instanceof HTMLButtonElement)) {
              handleApply();
            }
          }}
        >
          <div
            role="dialog"
            aria-modal="true"
            aria-label={t('dialogs.paragraph.title')}
            tabindex={-1}
            style={dialogStyle}
            onClick={(event: MouseEvent) => event.stopPropagation()}
            // Painted pages ARE the editable surface, so any mousedown that reaches them
            // moves the caret — and the dialog formats whatever the caret is on.
            onMousedown={(event: MouseEvent) => event.stopPropagation()}
          >
            <div style={headerStyle}>{t('dialogs.paragraph.title')}</div>
            <div style={bodyStyle}>
              <div style={sectionLabelStyle}>{t('dialogs.paragraph.general')}</div>
              <div style={rowStyle}>
                <label style={labelStyle} for={`${fieldId}-alignment`}>
                  {t('dialogs.paragraph.alignment')}
                </label>
                <select
                  id={`${fieldId}-alignment`}
                  style={inputStyle}
                  value={alignment.value}
                  onChange={(event) => {
                    alignment.value = (event.target as HTMLSelectElement)
                      .value as typeof alignment.value;
                  }}
                  aria-label={t('dialogs.paragraph.alignment')}
                >
                  <option value="left">{t('dialogs.paragraph.alignLeft')}</option>
                  <option value="center">{t('dialogs.paragraph.alignCenter')}</option>
                  <option value="right">{t('dialogs.paragraph.alignRight')}</option>
                  <option value="justify">{t('dialogs.paragraph.alignJustify')}</option>
                </select>
              </div>

              <div style={sectionLabelStyle}>{t('dialogs.paragraph.indentation')}</div>
              {inchRow('beforeText', indentLeft.value, (twips) => {
                indentLeft.value = twips;
              })}
              {inchRow('afterText', indentRight.value, (twips) => {
                indentRight.value = twips;
              })}
              <div style={rowStyle}>
                <label style={labelStyle} for={`${fieldId}-special`}>
                  {t('dialogs.paragraph.special')}
                </label>
                <select
                  id={`${fieldId}-special`}
                  style={inputStyle}
                  value={special.value}
                  onChange={(event) => {
                    special.value = (event.target as HTMLSelectElement).value as SpecialIndent;
                  }}
                  aria-label={t('dialogs.paragraph.special')}
                >
                  <option value="none">{t('dialogs.paragraph.specialNone')}</option>
                  <option value="firstLine">{t('dialogs.paragraph.specialFirstLine')}</option>
                  <option value="hanging">{t('dialogs.paragraph.specialHanging')}</option>
                </select>
              </div>
              {special.value !== 'none'
                ? inchRow('by', specialBy.value, (twips) => {
                    specialBy.value = Math.max(0, twips);
                  })
                : null}

              <div style={sectionLabelStyle}>{t('dialogs.paragraph.spacing')}</div>
              {pointRow('spaceBefore', spaceBefore.value, (points) => {
                spaceBefore.value = points;
              })}
              {pointRow('spaceAfter', spaceAfter.value, (points) => {
                spaceAfter.value = points;
              })}
              <div style={rowStyle}>
                <label style={labelStyle} for={`${fieldId}-lineSpacing`}>
                  {t('dialogs.paragraph.lineSpacing')}
                </label>
                <select
                  id={`${fieldId}-lineSpacing`}
                  style={inputStyle}
                  value={lineRule.value}
                  onChange={(event) => {
                    const next = (event.target as HTMLSelectElement).value as typeof lineRule.value;
                    lineRule.value = next;
                    // The value means LINES under Multiple and POINTS otherwise, so carrying
                    // 1.08 into "Exactly" would ask for a 1pt line box.
                    // Back to the rule it opened on means back to the value it opened
                    // on, or a user who picked "Exactly" and changed their mind would
                    // silently write 1.08 over the 1.15 their style supplies.
                    lineValue.value =
                      next === seedRef.value?.lineRule
                        ? seedRef.value.lineValue
                        : next === 'multiple'
                          ? 1.08
                          : 12;
                  }}
                  aria-label={t('dialogs.paragraph.lineSpacing')}
                >
                  <option value="multiple">{t('dialogs.paragraph.ruleMultiple')}</option>
                  <option value="atLeast">{t('dialogs.paragraph.ruleAtLeast')}</option>
                  <option value="exact">{t('dialogs.paragraph.ruleExactly')}</option>
                </select>
              </div>
              <div style={rowStyle}>
                <label style={labelStyle} for={`${fieldId}-at`}>
                  {t('dialogs.paragraph.at')}
                </label>
                <input
                  id={`${fieldId}-at`}
                  type="number"
                  style={inputStyle}
                  min="0.01"
                  step={lineRule.value === 'multiple' ? '0.01' : '1'}
                  value={lineValue.value}
                  onInput={(event) => {
                    lineValue.value = Number((event.target as HTMLInputElement).value) || 0;
                  }}
                  aria-label={t('dialogs.paragraph.at')}
                />
                <span style={unitStyle}>
                  {lineRule.value === 'multiple' ? '' : t('dialogs.paragraph.unitPoints')}
                </span>
              </div>
              {checkbox('contextualSpacing', contextualSpacing.value, (next) => {
                contextualSpacing.value = next;
              })}

              <div style={sectionLabelStyle}>{t('dialogs.paragraph.tabStops')}</div>
              {tabStops.value.length === 0 ? (
                <div style={{ fontSize: '12px', color: 'var(--doc-text-muted)' }}>
                  {/* An empty list over a MIXED selection would read as "none of these
                      paragraphs has a tab stop", which is the opposite of what is true. */}
                  {t(
                    mixed.value.tabStops
                      ? 'dialogs.paragraph.tabMixed'
                      : 'dialogs.paragraph.tabEmpty'
                  )}
                </div>
              ) : (
                tabStops.value.map((stop) => (
                  <div key={stop.positionTwips} style={rowStyle}>
                    <span style={{ ...labelStyle, color: 'var(--doc-text)' }}>
                      {t('dialogs.paragraph.tabPositionLabel', {
                        position: formatInches(stop.positionTwips),
                      })}
                    </span>
                    <span style={{ flex: 1, fontSize: '13px', color: 'var(--doc-text-muted)' }}>
                      {t(TAB_ALIGNMENT_LABELS[stop.alignment])}
                    </span>
                    <button
                      type="button"
                      style={btnStyle}
                      onClick={() => {
                        tabStops.value = tabStops.value.filter((entry) => entry !== stop);
                      }}
                      aria-label={t('dialogs.paragraph.tabRemoveAt', {
                        position: formatInches(stop.positionTwips),
                      })}
                    >
                      {t('dialogs.paragraph.tabRemove')}
                    </button>
                  </div>
                ))
              )}
              {inchRow('tabPosition', newTabPosition.value, (twips) => {
                newTabPosition.value = Math.max(0, twips);
              })}
              <div style={rowStyle}>
                <label style={labelStyle} for={`${fieldId}-tabAlignment`}>
                  {t('dialogs.paragraph.tabAlignment')}
                </label>
                <select
                  id={`${fieldId}-tabAlignment`}
                  style={inputStyle}
                  value={newTabAlignment.value}
                  onChange={(event) => {
                    newTabAlignment.value = (event.target as HTMLSelectElement)
                      .value as TabAlignment;
                  }}
                  aria-label={t('dialogs.paragraph.tabAlignment')}
                >
                  <option value="left">{t('dialogs.paragraph.tabAlignLeft')}</option>
                  <option value="center">{t('dialogs.paragraph.tabAlignCenter')}</option>
                  <option value="right">{t('dialogs.paragraph.tabAlignRight')}</option>
                  {/* No `bar`: it draws a vertical rule rather than stopping the caret, so the
                          engine neither paints it nor reports it back. Offering it here
                          would add a row that vanishes on OK. */}
                  <option value="decimal">{t('dialogs.paragraph.tabAlignDecimal')}</option>
                </select>
              </div>
              <div style={rowStyle}>
                <label style={labelStyle} for={`${fieldId}-tabLeader`}>
                  {t('dialogs.paragraph.tabLeader')}
                </label>
                <select
                  id={`${fieldId}-tabLeader`}
                  style={inputStyle}
                  value={newTabLeader.value}
                  onChange={(event) => {
                    newTabLeader.value = (event.target as HTMLSelectElement).value as TabLeaderName;
                  }}
                  aria-label={t('dialogs.paragraph.tabLeader')}
                >
                  <option value="none">{t('dialogs.paragraph.tabNone')}</option>
                  <option value="dot">{t('dialogs.paragraph.tabLeaderDot')}</option>
                  <option value="hyphen">{t('dialogs.paragraph.tabLeaderHyphen')}</option>
                  <option value="underscore">{t('dialogs.paragraph.tabLeaderUnderscore')}</option>
                </select>
              </div>
              <div style={{ ...rowStyle, justifyContent: 'flex-end' }}>
                <button type="button" style={btnStyle} onClick={setTabStop}>
                  {t('dialogs.paragraph.tabAdd')}
                </button>
                <button
                  type="button"
                  style={btnStyle}
                  onClick={() => {
                    // Over a MIXED list this is still a decision, even though the list already
                    // shows empty — `changedFields` needs the disagreement marked resolved.
                    mixed.value = { ...mixed.value, tabStops: false };
                    tabStops.value = [];
                  }}
                >
                  {t('dialogs.paragraph.tabClearAll')}
                </button>
              </div>

              <div style={sectionLabelStyle}>{t('dialogs.paragraph.pagination')}</div>
              {checkbox('keepNext', keepNext.value, (next) => {
                keepNext.value = next;
              })}
              {checkbox('widowControl', widowControl.value, (next) => {
                widowControl.value = next;
              })}
              {checkbox('keepLines', keepLines.value, (next) => {
                keepLines.value = next;
              })}
              {checkbox('pageBreakBefore', pageBreakBefore.value, (next) => {
                pageBreakBefore.value = next;
              })}
            </div>
            <div style={footerStyle}>
              {/* `role="alert"` so the refusal is announced, not just drawn. */}
              {refused.value ? (
                <span role="alert" style={refusedStyle}>
                  {t('dialogs.paragraph.refused')}
                </span>
              ) : null}
              <button type="button" style={btnStyle} onClick={props.onClose}>
                {t('dialogs.paragraph.cancel')}
              </button>
              <button
                type="button"
                style={{
                  ...btnStyle,
                  backgroundColor: 'var(--doc-primary)',
                  color: 'var(--doc-on-primary)',
                  borderColor: 'var(--doc-primary)',
                  // The same dimming `DocxEditorPageSetup` uses. These two dialogs sit
                  // beside each other in the same product; they cannot disagree about what
                  // a primary button looks like.
                  opacity: paragraph.isEnabled.value ? 1 : 0.5,
                }}
                disabled={!paragraph.isEnabled.value}
                onClick={handleApply}
              >
                {t('dialogs.paragraph.ok')}
              </button>
            </div>
          </div>
        </div>
      );
    };
  },
});

// packages/react/src/editor/DocxEditorParagraphDialog.tsx
// The Paragraph dialog as a context-fed part (`DocxEditor.ParagraphDialog`).
//
// Alignment, indentation with its Special/By pair, spacing with its line-spacing rule and
// value, and the paragraph flags. Every field reads from
// `useParagraphFormat()` and the whole form is written back as ONE `setParagraphFormat`
// command on OK, so the dialog is a single undo step. The host owns visibility
// (`open`/`onClose`); the engine owns everything else.
//
// This is the escape hatch the line-spacing menu never had. That menu's rows are Word's
// shortcuts — a fixed 10pt Add, a 0pt Remove — and on a document whose style already
// supplies space-after they move a paragraph by the DIFFERENCE, which reads as a control
// that does nothing (issue #360). A field you type a number into does not have that
// problem.

import { useCallback, useEffect, useId, useRef, useState } from 'react';
import type { CSSProperties, ReactElement } from 'react';
import { useTranslation } from '../i18n';
import { useParagraphFormat, type ParagraphTabStop } from './useParagraphFormat';
import {
  changedFields,
  formatInches,
  inchesToTwips,
  mixedFieldsOf,
  NO_MIXED_FIELDS,
  seedFields,
  trapTabWithin,
  TAB_ALIGNMENT_LABELS,
  twipsToInches,
  withTabStop,
  type ParagraphDialogFields,
  type ParagraphDialogMixed,
  type SpecialIndent,
  type TabAlignment,
  type TabLeaderName,
} from './paragraph-dialog-fields';

/** Props for `DocxEditor.ParagraphDialog`. @public */
export interface DocxEditorParagraphDialogProps {
  /** Whether the dialog is shown. The host owns this state. */
  open: boolean;
  /** Called on Cancel, Escape, overlay click, and after a successful OK. */
  onClose: () => void;
  className?: string;
}

const refusedStyle: CSSProperties = {
  marginRight: 'auto',
  fontSize: '12px',
  color: 'var(--doc-danger)',
};

const overlayStyle: CSSProperties = {
  position: 'fixed',
  inset: 0,
  backgroundColor: 'var(--doc-overlay)',
  display: 'flex',
  alignItems: 'center',
  justifyContent: 'center',
  zIndex: 10000,
};

const dialogStyle: CSSProperties = {
  backgroundColor: 'var(--doc-surface)',
  borderRadius: 8,
  boxShadow: '0 4px 20px var(--doc-shadow)',
  minWidth: 460,
  maxWidth: 560,
  width: '100%',
  margin: 20,
  maxHeight: '90vh',
  overflowY: 'auto',
};

const headerStyle: CSSProperties = {
  padding: '16px 20px 12px',
  borderBottom: '1px solid var(--doc-border)',
  fontSize: 16,
  fontWeight: 600,
  color: 'var(--doc-text)',
};

const bodyStyle: CSSProperties = {
  padding: '16px 20px',
  display: 'flex',
  flexDirection: 'column',
  gap: 14,
};

const sectionLabelStyle: CSSProperties = {
  fontSize: 12,
  fontWeight: 600,
  color: 'var(--doc-text-muted)',
  textTransform: 'uppercase',
  letterSpacing: '0.5px',
};

const rowStyle: CSSProperties = { display: 'flex', alignItems: 'center', gap: 12 };
const labelStyle: CSSProperties = { width: 110, fontSize: 13, color: 'var(--doc-text-muted)' };
const inputStyle: CSSProperties = {
  flex: 1,
  padding: '6px 8px',
  border: '1px solid var(--doc-border)',
  borderRadius: 4,
  fontSize: 13,
  backgroundColor: 'var(--doc-surface)',
  color: 'var(--doc-text)',
};
const unitStyle: CSSProperties = { fontSize: 11, color: 'var(--doc-text-muted)', width: 20 };
const checkRowStyle: CSSProperties = {
  display: 'flex',
  alignItems: 'center',
  gap: 8,
  fontSize: 13,
  color: 'var(--doc-text)',
};
const footerStyle: CSSProperties = {
  padding: '12px 20px 16px',
  borderTop: '1px solid var(--doc-border)',
  display: 'flex',
  justifyContent: 'flex-end',
  gap: 8,
};
const btnStyle: CSSProperties = {
  padding: '6px 16px',
  fontSize: 13,
  border: '1px solid var(--doc-border)',
  borderRadius: 4,
  cursor: 'pointer',
  backgroundColor: 'var(--doc-surface)',
  color: 'var(--doc-text)',
};

/**
 * The Paragraph dialog. Reads the selection through `useParagraphFormat()` and applies
 * the whole form as one undoable command.
 *
 * @public
 */
export function DocxEditorParagraphDialog({
  open,
  onClose,
  className,
}: DocxEditorParagraphDialogProps): ReactElement | null {
  const { t } = useTranslation();
  const { format, isEnabled, apply } = useParagraphFormat();

  const [alignment, setAlignment] = useState<'left' | 'center' | 'right' | 'justify'>('left');
  const [indentLeft, setIndentLeft] = useState(0);
  const [indentRight, setIndentRight] = useState(0);
  const [special, setSpecial] = useState<SpecialIndent>('none');
  const [specialBy, setSpecialBy] = useState(0);
  const [spaceBefore, setSpaceBefore] = useState(0);
  const [spaceAfter, setSpaceAfter] = useState(0);
  const [lineRule, setLineRule] = useState<'multiple' | 'exact' | 'atLeast'>('multiple');
  const [lineValue, setLineValue] = useState(1.08);
  const [contextualSpacing, setContextualSpacing] = useState(false);
  const [keepNext, setKeepNext] = useState(false);
  const [keepLines, setKeepLines] = useState(false);
  const [widowControl, setWidowControl] = useState(true);
  const [pageBreakBefore, setPageBreakBefore] = useState(false);
  const [tabStops, setTabStops] = useState<readonly ParagraphTabStop[]>([]);
  const [newTabPosition, setNewTabPosition] = useState(0);
  const [newTabAlignment, setNewTabAlignment] = useState<TabAlignment>('left');
  const [newTabLeader, setNewTabLeader] = useState<TabLeaderName>('none');
  const [mixed, setMixed] = useState<ParagraphDialogMixed>(NO_MIXED_FIELDS);
  // One prefix per mounted dialog, so a `<label for>` points at THIS dialog's input even
  // when a host renders two. Clicking a visible label is how a pointer user hits a small
  // checkbox, and `aria-label` alone does not give them that.
  const fieldId = useId();
  const [refused, setRefused] = useState(false);
  const panelRef = useRef<HTMLDivElement | null>(null);

  // Seed from the selection when the dialog OPENS — not on every tick, or a concurrent
  // edit would fight the user's typing. The same rule `DocxEditorPageSetupDialog` follows.
  const seeded = useRef(false);
  /** What the fields held on open, so `handleApply` can send only what MOVED. */
  const seedRef = useRef<ParagraphDialogFields | null>(null);
  useEffect(() => {
    if (!open) {
      seeded.current = false;
      return;
    }
    if (seeded.current || format === null) return;
    const seed = seedFields(format);
    setAlignment(seed.alignment);
    setIndentLeft(seed.indentLeft);
    setIndentRight(seed.indentRight);
    setSpecial(seed.special);
    setSpecialBy(seed.specialBy);
    setSpaceBefore(seed.spaceBefore);
    setSpaceAfter(seed.spaceAfter);
    setLineRule(seed.lineRule);
    setLineValue(seed.lineValue);
    setContextualSpacing(seed.contextualSpacing);
    setKeepNext(seed.keepNext);
    setKeepLines(seed.keepLines);
    setWidowControl(seed.widowControl);
    setPageBreakBefore(seed.pageBreakBefore);
    setTabStops(seed.tabStops);
    setMixed(mixedFieldsOf(format));
    seedRef.current = seed;
    seeded.current = true;
  }, [open, format]);

  // Focus the panel on open and hand it back on close. Leaving focus on `<body>` after OK
  // strands a keyboard user at the top of the document, having just formatted a paragraph
  // somewhere else.
  const openerRef = useRef<Element | null>(null);
  useEffect(() => {
    if (!open) return;
    openerRef.current = document.activeElement;
    panelRef.current?.focus();
    return () => {
      const opener = openerRef.current;
      openerRef.current = null;
      if (opener instanceof HTMLElement && opener.isConnected) opener.focus();
    };
  }, [open]);

  const handleApply = useCallback(() => {
    const seed = seedRef.current;
    const update =
      seed === null
        ? null
        : changedFields(seed, {
            alignment,
            indentLeft,
            indentRight,
            special,
            specialBy,
            spaceBefore,
            spaceAfter,
            lineRule,
            lineValue,
            contextualSpacing,
            keepNext,
            keepLines,
            widowControl,
            pageBreakBefore,
            tabStops,
          });
    // Nothing moved, so there is nothing to write. Closing is the whole job.
    if (update === null) {
      onClose();
      return;
    }
    // A refused write keeps the dialog OPEN: `apply` is honest about op-layer rejections,
    // so closing here would claim a success that did not happen. It has to SAY so — a
    // dialog that swallows the OK and sits there looks broken rather than refused.
    if (apply(update)) {
      setRefused(false);
      onClose();
      return;
    }
    setRefused(true);
  }, [
    apply,
    onClose,
    alignment,
    indentLeft,
    indentRight,
    special,
    specialBy,
    spaceBefore,
    spaceAfter,
    lineRule,
    lineValue,
    contextualSpacing,
    keepNext,
    keepLines,
    widowControl,
    pageBreakBefore,
    tabStops,
  ]);

  /** Add or replace the stop at this position — "Set" replaces one already there. */
  const setTabStop = useCallback(() => {
    setTabStops(
      withTabStop(tabStops, {
        positionTwips: Math.round(newTabPosition),
        alignment: newTabAlignment,
        ...(newTabLeader !== 'none' ? { leader: newTabLeader } : {}),
      })
    );
  }, [tabStops, newTabPosition, newTabAlignment, newTabLeader]);

  if (!open) return null;

  const inchRow = (
    labelKey: 'beforeText' | 'afterText',
    value: number,
    set: (twips: number) => void
  ) => (
    <div style={rowStyle}>
      <label style={labelStyle} htmlFor={`${fieldId}-${labelKey}`}>
        {t(`dialogs.paragraph.${labelKey}`)}
      </label>
      <input
        id={`${fieldId}-${labelKey}`}
        type="number"
        style={inputStyle}
        min={0}
        step={0.1}
        value={twipsToInches(value)}
        onChange={(event) => set(inchesToTwips(Number(event.target.value) || 0))}
        aria-label={t(`dialogs.paragraph.${labelKey}`)}
      />
      <span style={unitStyle}>{t('dialogs.paragraph.unitInches')}</span>
    </div>
  );

  const pointRow = (
    labelKey: 'spaceBefore' | 'spaceAfter',
    value: number,
    set: (points: number) => void
  ) => (
    <div style={rowStyle}>
      <label style={labelStyle} htmlFor={`${fieldId}-${labelKey}`}>
        {t(`dialogs.paragraph.${labelKey}`)}
      </label>
      <input
        id={`${fieldId}-${labelKey}`}
        type="number"
        style={inputStyle}
        min={0}
        step={1}
        value={value}
        onChange={(event) => set(Math.max(0, Number(event.target.value) || 0))}
        aria-label={t(`dialogs.paragraph.${labelKey}`)}
      />
      <span style={unitStyle}>{t('dialogs.paragraph.unitPoints')}</span>
    </div>
  );

  const checkbox = (
    labelKey: keyof ParagraphDialogMixed,
    checked: boolean,
    set: (next: boolean) => void
  ) => (
    <label style={checkRowStyle}>
      <input
        type="checkbox"
        checked={checked}
        // `indeterminate` is a DOM PROPERTY with no attribute, so React cannot set it from
        // JSX — it has to be written on the node. Without it a setting the selection
        // disagrees about renders as plain unchecked, which claims agreement that is not
        // there.
        ref={(node) => {
          if (node) node.indeterminate = mixed[labelKey];
        }}
        onChange={(event) => {
          // Touching the box RESOLVES the disagreement: from here it means what it shows.
          setMixed((previous) => ({ ...previous, [labelKey]: false }));
          set(event.target.checked);
        }}
      />
      {t(`dialogs.paragraph.${labelKey}`)}
    </label>
  );

  return (
    <div
      className={className}
      style={overlayStyle}
      onClick={onClose}
      onKeyDown={(event) => {
        if (event.key === 'Escape') onClose();
        if (panelRef.current && trapTabWithin(panelRef.current, event.nativeEvent)) {
          event.preventDefault();
        }
        // Enter is the form's default submit, EXCEPT on a control that owns the key: a
        // button acts on the Enter that focused it, and keydown here runs first, so Cancel
        // pressed from the keyboard would otherwise apply the form before closing it.
        if (event.key === 'Enter' && !(event.target instanceof HTMLButtonElement)) {
          handleApply();
        }
      }}
    >
      <div
        ref={panelRef}
        role="dialog"
        aria-modal="true"
        aria-label={t('dialogs.paragraph.title')}
        tabIndex={-1}
        style={dialogStyle}
        onClick={(event) => event.stopPropagation()}
        // Painted pages ARE the editable surface, so any mousedown that reaches them moves
        // the caret — and the dialog formats whatever the caret is on. Without this,
        // clicking a field inside it moves the selection out from under the edit.
        onMouseDown={(event) => event.stopPropagation()}
      >
        <div style={headerStyle}>{t('dialogs.paragraph.title')}</div>
        <div style={bodyStyle}>
          <div style={sectionLabelStyle}>{t('dialogs.paragraph.general')}</div>
          <div style={rowStyle}>
            <label style={labelStyle}>{t('dialogs.paragraph.alignment')}</label>
            <select
              style={inputStyle}
              value={alignment}
              onChange={(event) =>
                setAlignment(event.target.value as 'left' | 'center' | 'right' | 'justify')
              }
              aria-label={t('dialogs.paragraph.alignment')}
            >
              <option value="left">{t('dialogs.paragraph.alignLeft')}</option>
              <option value="center">{t('dialogs.paragraph.alignCenter')}</option>
              <option value="right">{t('dialogs.paragraph.alignRight')}</option>
              <option value="justify">{t('dialogs.paragraph.alignJustify')}</option>
            </select>
          </div>

          <div style={sectionLabelStyle}>{t('dialogs.paragraph.indentation')}</div>
          {inchRow('beforeText', indentLeft, setIndentLeft)}
          {inchRow('afterText', indentRight, setIndentRight)}
          <div style={rowStyle}>
            <label style={labelStyle}>{t('dialogs.paragraph.special')}</label>
            <select
              style={inputStyle}
              value={special}
              onChange={(event) => setSpecial(event.target.value as SpecialIndent)}
              aria-label={t('dialogs.paragraph.special')}
            >
              <option value="none">{t('dialogs.paragraph.specialNone')}</option>
              <option value="firstLine">{t('dialogs.paragraph.specialFirstLine')}</option>
              <option value="hanging">{t('dialogs.paragraph.specialHanging')}</option>
            </select>
          </div>
          {special !== 'none' ? (
            <div style={rowStyle}>
              <label style={labelStyle}>{t('dialogs.paragraph.by')}</label>
              <input
                type="number"
                style={inputStyle}
                min={0}
                step={0.1}
                value={twipsToInches(specialBy)}
                onChange={(event) =>
                  setSpecialBy(Math.max(0, inchesToTwips(Number(event.target.value) || 0)))
                }
                aria-label={t('dialogs.paragraph.by')}
              />
              <span style={unitStyle}>{t('dialogs.paragraph.unitInches')}</span>
            </div>
          ) : null}

          <div style={sectionLabelStyle}>{t('dialogs.paragraph.spacing')}</div>
          {pointRow('spaceBefore', spaceBefore, setSpaceBefore)}
          {pointRow('spaceAfter', spaceAfter, setSpaceAfter)}
          <div style={rowStyle}>
            <label style={labelStyle}>{t('dialogs.paragraph.lineSpacing')}</label>
            <select
              style={inputStyle}
              value={lineRule}
              onChange={(event) => {
                const next = event.target.value as 'multiple' | 'exact' | 'atLeast';
                setLineRule(next);
                // The value means different things per rule — LINES for multiple, POINTS
                // otherwise — so carrying 1.08 into "Exactly" would ask for a 1pt line.
                setLineValue(next === 'multiple' ? 1.08 : 12);
              }}
              aria-label={t('dialogs.paragraph.lineSpacing')}
            >
              <option value="multiple">{t('dialogs.paragraph.ruleMultiple')}</option>
              <option value="atLeast">{t('dialogs.paragraph.ruleAtLeast')}</option>
              <option value="exact">{t('dialogs.paragraph.ruleExactly')}</option>
            </select>
          </div>
          <div style={rowStyle}>
            <label style={labelStyle}>{t('dialogs.paragraph.at')}</label>
            <input
              type="number"
              style={inputStyle}
              min={0.01}
              step={lineRule === 'multiple' ? 0.01 : 1}
              value={lineValue}
              onChange={(event) => setLineValue(Number(event.target.value) || 0)}
              aria-label={t('dialogs.paragraph.at')}
            />
            <span style={unitStyle}>
              {lineRule === 'multiple' ? '' : t('dialogs.paragraph.unitPoints')}
            </span>
          </div>
          {checkbox('contextualSpacing', contextualSpacing, setContextualSpacing)}

          <div style={sectionLabelStyle}>{t('dialogs.paragraph.tabStops')}</div>
          {tabStops.length === 0 ? (
            <div style={{ fontSize: 12, color: 'var(--doc-text-muted)' }}>
              {t('dialogs.paragraph.tabEmpty')}
            </div>
          ) : (
            tabStops.map((stop) => (
              <div key={stop.positionTwips} style={rowStyle}>
                <span style={{ ...labelStyle, color: 'var(--doc-text)' }}>
                  {t('dialogs.paragraph.tabPositionLabel', {
                    position: formatInches(stop.positionTwips),
                  })}
                </span>
                <span style={{ flex: 1, fontSize: 13, color: 'var(--doc-text-muted)' }}>
                  {t(TAB_ALIGNMENT_LABELS[stop.alignment])}
                </span>
                <button
                  type="button"
                  style={btnStyle}
                  onClick={() => setTabStops(tabStops.filter((entry) => entry !== stop))}
                  aria-label={t('dialogs.paragraph.tabRemoveAt', {
                    position: formatInches(stop.positionTwips),
                  })}
                >
                  {t('dialogs.paragraph.tabRemove')}
                </button>
              </div>
            ))
          )}
          <div style={rowStyle}>
            <label style={labelStyle}>{t('dialogs.paragraph.tabPosition')}</label>
            <input
              type="number"
              style={inputStyle}
              min={0}
              step={0.1}
              value={twipsToInches(newTabPosition)}
              onChange={(event) =>
                setNewTabPosition(Math.max(0, inchesToTwips(Number(event.target.value) || 0)))
              }
              aria-label={t('dialogs.paragraph.tabPosition')}
            />
            <span style={unitStyle}>{t('dialogs.paragraph.unitInches')}</span>
          </div>
          <div style={rowStyle}>
            <label style={labelStyle}>{t('dialogs.paragraph.tabAlignment')}</label>
            <select
              style={inputStyle}
              value={newTabAlignment}
              onChange={(event) => setNewTabAlignment(event.target.value as TabAlignment)}
              aria-label={t('dialogs.paragraph.tabAlignment')}
            >
              <option value="left">{t('dialogs.paragraph.tabAlignLeft')}</option>
              <option value="center">{t('dialogs.paragraph.tabAlignCenter')}</option>
              <option value="right">{t('dialogs.paragraph.tabAlignRight')}</option>
              {/* No `bar`: it draws a vertical rule rather than stopping the caret, so the
                  engine neither paints it nor reports it back. Offering it here would add a
                  row that vanishes on OK. An existing one is preserved on save. */}
              <option value="decimal">{t('dialogs.paragraph.tabAlignDecimal')}</option>
            </select>
          </div>
          <div style={rowStyle}>
            <label style={labelStyle}>{t('dialogs.paragraph.tabLeader')}</label>
            <select
              style={inputStyle}
              value={newTabLeader}
              onChange={(event) => setNewTabLeader(event.target.value as TabLeaderName)}
              aria-label={t('dialogs.paragraph.tabLeader')}
            >
              <option value="none">{t('dialogs.paragraph.tabNone')}</option>
              <option value="dot">{t('dialogs.paragraph.tabLeaderDot')}</option>
              <option value="hyphen">{t('dialogs.paragraph.tabLeaderHyphen')}</option>
              <option value="underscore">{t('dialogs.paragraph.tabLeaderUnderscore')}</option>
            </select>
          </div>
          <div style={{ ...rowStyle, justifyContent: 'flex-end' }}>
            <button type="button" style={btnStyle} onClick={setTabStop}>
              {t('dialogs.paragraph.tabAdd')}
            </button>
            <button type="button" style={btnStyle} onClick={() => setTabStops([])}>
              {t('dialogs.paragraph.tabClearAll')}
            </button>
          </div>

          <div style={sectionLabelStyle}>{t('dialogs.paragraph.pagination')}</div>
          {checkbox('keepNext', keepNext, setKeepNext)}
          {checkbox('widowControl', widowControl, setWidowControl)}
          {checkbox('keepLines', keepLines, setKeepLines)}
          {checkbox('pageBreakBefore', pageBreakBefore, setPageBreakBefore)}
        </div>
        <div style={footerStyle}>
          {/* `role="alert"` so the refusal is announced, not just drawn. */}
          {refused ? (
            <span role="alert" style={refusedStyle}>
              {t('dialogs.paragraph.refused')}
            </span>
          ) : null}
          <button type="button" style={btnStyle} onClick={onClose}>
            {t('dialogs.paragraph.cancel')}
          </button>
          <button
            type="button"
            style={{
              ...btnStyle,
              backgroundColor: 'var(--doc-accent)',
              color: 'var(--doc-accent-contrast)',
              borderColor: 'var(--doc-accent)',
            }}
            disabled={!isEnabled}
            onClick={handleApply}
          >
            {t('dialogs.paragraph.ok')}
          </button>
        </div>
      </div>
    </div>
  );
}
