// packages/react/src/editor/images/ImageSelectionOverlay.tsx
// Selection ring and eight resize handles for the selected drawing — geometry from layout records.

import {
  useCallback,
  useEffect,
  useMemo,
  useRef,
  useState,
  type KeyboardEvent,
  type RefObject,
} from 'react';
import { createPortal } from 'react-dom';
import {
  captureImageMutationPreconditions,
  computeMovedImagePosition,
  IMAGE_OVERLAY_NUDGE_PT,
  IMAGE_OVERLAY_NUDGE_SHIFT_PT,
  isStaleImageInteractionCommit,
  selectedDrawingOverlayTargetOf,
  type ImageInteractionSession,
  type ImageOverlayScrollPort,
  type ImageResizeHandle,
  type SelectedDrawingOverlayTarget,
} from '@docx-editor.dev/core/editor';
import {
  computeImageResizeResult,
  createImageOverlayScrollPort,
  cssPixelsToLayoutPoints,
  finalizeImageOverlayInteraction,
  overlayFrameToSheetCssPixels,
  overlayHostOrigin,
  resizePreservesAspect,
} from '@docx-editor.dev/core/editor';
import type { DrawingPositionInput } from '@docx-editor.dev/core/editor';
import { useTranslation } from '../../i18n';
import { useDocxEditor } from '../context';
import { guardToolbarMousedown } from '../toolbar/ToolbarButton';

const HANDLES: readonly ImageResizeHandle[] = ['nw', 'n', 'ne', 'e', 'se', 's', 'sw', 'w'];
const AUTO_SCROLL_EDGE_PX = 40;
const AUTO_SCROLL_MAX_PT = 12;

interface PreviewState {
  readonly session: ImageInteractionSession;
  readonly bounds: SelectedDrawingOverlayTarget;
  readonly accumulatedScrollPt: number;
}

export interface ImageSelectionOverlayProps {
  readonly containerRef: RefObject<HTMLElement | null>;
  readonly portalRef: RefObject<HTMLElement | null>;
  readonly scrollPort?: ImageOverlayScrollPort;
}

function handleLabelKey(handle: ImageResizeHandle): `imageOverlay.handle.${ImageResizeHandle}` {
  return `imageOverlay.handle.${handle}`;
}

function cursorForHandle(handle: ImageResizeHandle): string {
  switch (handle) {
    case 'nw':
    case 'se':
      return 'nwse-resize';
    case 'ne':
    case 'sw':
      return 'nesw-resize';
    case 'n':
    case 's':
      return 'ns-resize';
    default:
      return 'ew-resize';
  }
}

function handlePosition(handle: ImageResizeHandle): { readonly x: string; readonly y: string } {
  const map: Record<ImageResizeHandle, { x: string; y: string }> = {
    nw: { x: '0%', y: '0%' },
    n: { x: '50%', y: '0%' },
    ne: { x: '100%', y: '0%' },
    e: { x: '100%', y: '50%' },
    se: { x: '100%', y: '100%' },
    s: { x: '50%', y: '100%' },
    sw: { x: '0%', y: '100%' },
    w: { x: '0%', y: '50%' },
  };
  return map[handle];
}

function handleFromDelta(dx: number, dy: number): ImageResizeHandle {
  if (dx > 0 && dy > 0) return 'se';
  if (dx > 0 && dy < 0) return 'ne';
  if (dx < 0 && dy > 0) return 'sw';
  if (dx < 0 && dy < 0) return 'nw';
  if (dx > 0) return 'e';
  if (dx < 0) return 'w';
  if (dy > 0) return 's';
  return 'n';
}

export function ImageSelectionOverlay({
  containerRef,
  portalRef,
  scrollPort: scrollPortOverride,
}: ImageSelectionOverlayProps): React.ReactPortal | null {
  const editor = useDocxEditor();
  const { t } = useTranslation();
  const [target, setTarget] = useState<SelectedDrawingOverlayTarget | null>(null);
  const [preview, setPreview] = useState<PreviewState | null>(null);
  // Where the surface's box begins inside the overlay's containing block. The surface
  // centres itself with an auto margin, so a viewport resize moves this origin without any
  // engine event firing. Held in state and measured in the observer (and once per
  // selection), never per render: `overlayHostOrigin` reads offsetLeft/offsetTop, which
  // forces layout, and preview renders arrive at pointermove frequency during a drag.
  const [origin, setOrigin] = useState<{ readonly left: number; readonly top: number }>({
    left: 0,
    top: 0,
  });
  const previewRef = useRef<PreviewState | null>(null);
  previewRef.current = preview;
  const pointerStartRef = useRef<{ readonly x: number; readonly y: number } | null>(null);
  const captureTargetRef = useRef<HTMLElement | null>(null);
  const overlayRef = useRef<HTMLDivElement | null>(null);
  const focusRequestedForDrawingRef = useRef<string | null>(null);
  const scrollPortRef = useRef<ImageOverlayScrollPort | null>(null);

  useEffect(() => {
    const container = containerRef.current;
    if (!container) return undefined;
    const onPointerDown = (event: PointerEvent): void => {
      const element = event.target instanceof Element ? event.target : null;
      if (element?.closest('.docx-drawing-textbox-content')) {
        focusRequestedForDrawingRef.current = null;
        return;
      }
      const drawingId = element
        ?.closest<HTMLElement>('[data-drawing-node-id]')
        ?.getAttribute('data-drawing-node-id');
      focusRequestedForDrawingRef.current = drawingId ?? null;
      if (drawingId && drawingId === target?.id) {
        queueMicrotask(() => overlayRef.current?.focus({ preventScroll: true }));
      }
    };
    container.addEventListener('pointerdown', onPointerDown, { capture: true });
    return () => container.removeEventListener('pointerdown', onPointerDown, { capture: true });
  }, [containerRef, target?.id]);

  useEffect(() => {
    if (!editor) {
      setTarget(null);
      return undefined;
    }
    const sync = (): void => {
      setTarget(selectedDrawingOverlayTargetOf(editor.surface));
    };
    // Document `change` can fire synchronously from inside a surface commit (the facade
    // listens on the session and emits before `selectionAfter` runs). Running overlay
    // sync in that window used to re-enter React and leave table structural edits on the
    // pre-commit caret — `insertRowAbove` kept reading A1. Defer to a microtask so the
    // engine finishes adopting the committed caret first; `selectionChange` stays immediate.
    const syncAfterCommit = (): void => {
      queueMicrotask(sync);
    };
    sync();
    const off = [editor.on('change', syncAfterCommit), editor.on('selectionChange', sync)];
    return () => {
      for (const unsubscribe of off) unsubscribe();
    };
  }, [editor]);

  const refreshOrigin = useCallback(() => {
    setOrigin((previous) => {
      const next = overlayHostOrigin(containerRef.current);
      return next.left === previous.left && next.top === previous.top ? previous : next;
    });
  }, [containerRef]);

  useEffect(() => {
    // Once per selection too: keyed on `target`, so a portal that mounted after the first
    // pass still gets its observer, and a fresh selection re-measures a moved origin.
    refreshOrigin();
    const portal = portalRef.current;
    if (!portal || typeof ResizeObserver !== 'function') return undefined;
    const observer = new ResizeObserver(refreshOrigin);
    observer.observe(portal);
    // The origin is a function of BOTH boxes: the surface's own width moves the centring
    // margin at a constant portal box (a page-size change), so observe the surface too.
    const container = containerRef.current;
    if (container) observer.observe(container);
    return () => observer.disconnect();
  }, [containerRef, portalRef, refreshOrigin, target]);

  useEffect(() => {
    if (scrollPortOverride) {
      scrollPortRef.current = scrollPortOverride;
      return undefined;
    }
    const container = containerRef.current;
    if (!container || !editor?.surface) return undefined;
    const scroller = container.closest('.docx-editor__scroll-container') as HTMLElement | null;
    if (!scroller) return undefined;
    const coordinates = editor.surface.overlayCoordinates();
    scrollPortRef.current = createImageOverlayScrollPort(scroller, coordinates.paintScale);
    return () => {
      scrollPortRef.current = null;
    };
  }, [containerRef, editor, scrollPortOverride]);

  const clearPreview = useCallback(() => {
    setPreview(null);
    pointerStartRef.current = null;
    const captured = captureTargetRef.current;
    captureTargetRef.current = null;
    if (captured) {
      try {
        captured.releasePointerCapture(
          (captured as HTMLElement & { _lastPointerId?: number })._lastPointerId ?? 0
        );
      } catch {
        // Already released.
      }
    }
  }, []);

  const beginSession = useCallback(
    (
      mode: 'move' | 'resize',
      handle: ImageResizeHandle | null,
      active: SelectedDrawingOverlayTarget,
      clientX: number,
      clientY: number,
      captureTarget: HTMLElement,
      pointerId: number
    ) => {
      if (!editor?.surface) return;
      // The flushing read FIRST: a pass still parked on the scheduler's timer would
      // otherwise publish mid-drag and fail the commit's staleness check for nothing, so
      // the session is stamped against the flushed layout. Preconditions are captured
      // after it, so a flush that lands buffered input cannot stamp a selection the
      // flush is about to move.
      const scope = editor.surface.activeScope();
      if (scope.kind === 'frame' && !editor.surface.selectDrawing(active.id, scope.hostParagraphId))
        return;
      const layout = editor.surface.layout();
      const pre = captureImageMutationPreconditions(editor);
      if (!pre) return;
      pointerStartRef.current = Object.freeze({ x: clientX, y: clientY });
      captureTargetRef.current = captureTarget;
      (captureTarget as HTMLElement & { _lastPointerId?: number })._lastPointerId = pointerId;
      try {
        captureTarget.setPointerCapture(pointerId);
      } catch {
        // Capture is best-effort.
      }
      setPreview({
        session: Object.freeze({
          drawingNodeId: active.id,
          startBounds: Object.freeze({
            x: active.x,
            y: active.y,
            width: active.width,
            height: active.height,
          }),
          startWidthEmu: active.widthEmu,
          startHeightEmu: active.heightEmu,
          startPosition: active.position,
          anchorFrameOrigin: active.anchorFrameOrigin,
          transform: active.transform,
          mode,
          handle,
          preconditions: pre,
          layoutRevision: layout.revision,
          packageRevision: editor.surface.session.packageRevision(),
          kind: active.kind,
        }),
        bounds: active,
        accumulatedScrollPt: 0,
      });
      overlayRef.current?.focus({ preventScroll: true });
    },
    [editor]
  );

  const commitSession = useCallback(
    (
      session: ImageInteractionSession,
      widthEmu: number,
      heightEmu: number,
      _bounds: {
        readonly x: number;
        readonly y: number;
        readonly width: number;
        readonly height: number;
      },
      position: DrawingPositionInput | null
    ) => {
      if (!editor) return;
      const stale = isStaleImageInteractionCommit(editor, session);
      if (stale) {
        clearPreview();
        return;
      }
      if (session.mode === 'resize') {
        editor.exec({
          type: 'setImageProperties',
          widthEmu,
          heightEmu,
          ...(position?.mode === 'simple'
            ? {
                horizontalEmu: position.horizontalEmu,
                verticalEmu: position.verticalEmu,
              }
            : {}),
          ...(position?.mode === 'frame'
            ? {
                ...(position.horizontalEmu !== undefined
                  ? { horizontalEmu: position.horizontalEmu }
                  : {}),
                ...(position.verticalEmu !== undefined
                  ? { verticalEmu: position.verticalEmu }
                  : {}),
              }
            : {}),
        });
      } else if (session.mode === 'move' && position) {
        editor.exec({ type: 'setImagePosition', ...position });
      }
      clearPreview();
    },
    [clearPreview, editor]
  );

  const onOverlayKeyDown = useCallback(
    (event: KeyboardEvent<HTMLElement>) => {
      if (!editor) return;
      const active = previewRef.current?.bounds ?? selectedDrawingOverlayTargetOf(editor.surface);
      if (!active) return;
      if (previewRef.current && event.key === 'Escape') {
        event.preventDefault();
        event.stopPropagation();
        clearPreview();
        return;
      }
      if (previewRef.current) return;
      const step = event.shiftKey ? IMAGE_OVERLAY_NUDGE_SHIFT_PT : IMAGE_OVERLAY_NUDGE_PT;
      if (event.key === 'Delete' || event.key === 'Backspace') {
        event.preventDefault();
        event.stopPropagation();
        editor.exec({ type: 'deleteImage' });
        return;
      }
      if (!['ArrowUp', 'ArrowDown', 'ArrowLeft', 'ArrowRight'].includes(event.key)) return;
      event.preventDefault();
      event.stopPropagation();
      const dx = event.key === 'ArrowLeft' ? -step : event.key === 'ArrowRight' ? step : 0;
      const dy = event.key === 'ArrowUp' ? -step : event.key === 'ArrowDown' ? step : 0;
      if (event.altKey) {
        if (!active.canResize) return;
        const handle = handleFromDelta(dx, dy);
        const resized = computeImageResizeResult({
          handle,
          startWidthEmu: active.widthEmu,
          startHeightEmu: active.heightEmu,
          startBounds: { x: active.x, y: active.y, width: active.width, height: active.height },
          startPosition: active.position,
          anchorFrameOrigin: active.anchorFrameOrigin,
          deltaXPt: dx,
          deltaYPt: dy,
          transform: active.transform,
          preserveAspect: resizePreservesAspect(
            handle,
            active.aspectLocked,
            event.shiftKey,
            active.textbox
          ),
          kind: active.kind,
        });
        editor.exec({
          type: 'setImageProperties',
          widthEmu: resized.widthEmu,
          heightEmu: resized.heightEmu,
          ...(resized.position?.mode === 'simple'
            ? {
                horizontalEmu: resized.position.horizontalEmu,
                verticalEmu: resized.position.verticalEmu,
              }
            : {}),
          ...(resized.position?.mode === 'frame'
            ? {
                ...(resized.position.horizontalEmu !== undefined
                  ? { horizontalEmu: resized.position.horizontalEmu }
                  : {}),
                ...(resized.position.verticalEmu !== undefined
                  ? { verticalEmu: resized.position.verticalEmu }
                  : {}),
              }
            : {}),
        });
        return;
      }
      if (active.kind !== 'anchored' || !active.canMove || !active.position) return;
      const moved = computeMovedImagePosition(active.position, dx, dy);
      editor.exec({ type: 'setImagePosition', ...moved });
    },
    [clearPreview, editor]
  );

  useEffect(() => {
    if (!preview || !editor?.surface) return undefined;
    const coordinates = editor.surface.overlayCoordinates();
    const onPointerMove = (event: PointerEvent) => {
      const current = previewRef.current;
      const startPointer = pointerStartRef.current;
      if (!current || !startPointer) return;
      const deltaX = cssPixelsToLayoutPoints(
        event.clientX - startPointer.x,
        coordinates.paintScale
      );
      const deltaY = cssPixelsToLayoutPoints(
        event.clientY - startPointer.y,
        coordinates.paintScale
      );
      if (current.session.mode === 'move') {
        let scrollDelta = 0;
        const scrollPort = scrollPortRef.current;
        const scroller = containerRef.current?.closest(
          '.docx-editor__scroll-container'
        ) as HTMLElement | null;
        if (scrollPort && scroller) {
          const scrollerRect = scroller.getBoundingClientRect();
          if (event.clientY > scrollerRect.bottom - AUTO_SCROLL_EDGE_PX)
            scrollDelta = AUTO_SCROLL_MAX_PT;
          else if (event.clientY < scrollerRect.top + AUTO_SCROLL_EDGE_PX)
            scrollDelta = -AUTO_SCROLL_MAX_PT;
          if (scrollDelta !== 0) scrollDelta = scrollPort.scrollBy(scrollDelta);
        }
        const accumulatedScrollPt = current.accumulatedScrollPt + scrollDelta;
        setPreview({
          ...current,
          accumulatedScrollPt,
          bounds: Object.freeze({
            ...current.bounds,
            x: current.session.startBounds.x + deltaX,
            y: current.session.startBounds.y + deltaY + accumulatedScrollPt,
          }),
        });
        return;
      }
      if (!current.session.handle) return;
      const resized = computeImageResizeResult({
        handle: current.session.handle,
        startWidthEmu: current.session.startWidthEmu,
        startHeightEmu: current.session.startHeightEmu,
        startBounds: current.session.startBounds,
        startPosition: current.session.startPosition,
        anchorFrameOrigin: current.session.anchorFrameOrigin,
        deltaXPt: deltaX,
        deltaYPt: deltaY,
        transform: current.session.transform,
        preserveAspect: resizePreservesAspect(
          current.session.handle,
          current.bounds.aspectLocked,
          event.shiftKey,
          current.bounds.textbox
        ),
        kind: current.session.kind,
      });
      setPreview({
        ...current,
        bounds: Object.freeze({
          ...current.bounds,
          x: resized.previewBounds.x,
          y: resized.previewBounds.y,
          width: resized.previewBounds.width,
          height: resized.previewBounds.height,
          widthEmu: resized.widthEmu,
          heightEmu: resized.heightEmu,
        }),
      });
    };
    const finish = (event: PointerEvent) => {
      const current = previewRef.current;
      if (!current) return;
      if (event.type === 'pointerup') {
        const deltaX = cssPixelsToLayoutPoints(
          event.clientX - (pointerStartRef.current?.x ?? event.clientX),
          coordinates.paintScale
        );
        const deltaY = cssPixelsToLayoutPoints(
          event.clientY - (pointerStartRef.current?.y ?? event.clientY),
          coordinates.paintScale
        );
        const finalized = finalizeImageOverlayInteraction({
          session: current.session,
          deltaXPt: deltaX,
          deltaYPt: deltaY,
          accumulatedScrollPt: current.accumulatedScrollPt,
          aspectLocked: current.bounds.aspectLocked,
          textbox: current.bounds.textbox,
          shiftKey: event.shiftKey,
          anchorFrameOrigin: current.session.anchorFrameOrigin,
        });
        commitSession(
          current.session,
          finalized.widthEmu,
          finalized.heightEmu,
          finalized.previewBounds,
          finalized.position
        );
      } else clearPreview();
    };
    window.addEventListener('pointermove', onPointerMove);
    window.addEventListener('pointerup', finish);
    window.addEventListener('pointercancel', finish);
    return () => {
      window.removeEventListener('pointermove', onPointerMove);
      window.removeEventListener('pointerup', finish);
      window.removeEventListener('pointercancel', finish);
    };
  }, [clearPreview, commitSession, containerRef, editor, preview]);

  useEffect(() => {
    if (!target || focusRequestedForDrawingRef.current !== target.id) return;
    focusRequestedForDrawingRef.current = null;
    overlayRef.current?.focus({ preventScroll: true });
  }, [target]);

  const active = preview?.bounds ?? target;
  const rendered = useMemo(() => {
    if (!editor?.surface || !active) return null;
    const layout = editor.surface.publishedLayout();
    const coordinates = editor.surface.overlayCoordinates();
    const sheetRect = overlayFrameToSheetCssPixels(
      layout,
      {
        pageIndex: active.pageIndex,
        x: active.x,
        y: active.y,
        width: active.width,
        height: active.height,
      },
      coordinates
    );
    // Sheet-space is surface-relative; the overlay's containing block is not the surface.
    const rect = {
      left: sheetRect.left + origin.left,
      top: sheetRect.top + origin.top,
      width: sheetRect.width,
      height: sheetRect.height,
    };
    const showHandles = active.canResize;
    const showMove = active.kind === 'anchored' && active.canMove;
    return (
      <div
        ref={overlayRef}
        className="docx-image-selection-overlay"
        data-drawing-node-id={active.id}
        tabIndex={0}
        onKeyDown={onOverlayKeyDown}
      >
        <div
          className={`docx-image-selection-overlay__frame${
            showMove ? ' docx-editor-one-surface__overlay-control' : ''
          }`}
          data-textbox={active.textbox ? 'true' : undefined}
          role="group"
          aria-label={t('imageOverlay.selection')}
          style={{
            left: `${rect.left}px`,
            top: `${rect.top}px`,
            width: `${rect.width}px`,
            height: `${rect.height}px`,
            cursor: showMove ? 'move' : 'default',
          }}
          onPointerDown={(event) => {
            guardToolbarMousedown(event);
            if (!showMove || !active.position) return;
            if (event.button !== 0) return;
            event.preventDefault();
            event.stopPropagation();
            beginSession(
              'move',
              null,
              active,
              event.clientX,
              event.clientY,
              event.currentTarget,
              event.pointerId
            );
          }}
        />
        {showHandles
          ? HANDLES.map((handle) => {
              const pos = handlePosition(handle);
              return (
                <button
                  key={handle}
                  type="button"
                  className="docx-image-selection-overlay__handle"
                  aria-label={t(handleLabelKey(handle))}
                  tabIndex={0}
                  style={{
                    left: `calc(${rect.left}px + ${rect.width}px * ${parseFloat(pos.x) / 100} - 5px)`,
                    top: `calc(${rect.top}px + ${rect.height}px * ${parseFloat(pos.y) / 100} - 5px)`,
                    cursor: cursorForHandle(handle),
                  }}
                  onPointerDown={(event) => {
                    guardToolbarMousedown(event);
                    if (event.button !== 0) return;
                    event.preventDefault();
                    event.stopPropagation();
                    beginSession(
                      'resize',
                      handle,
                      active,
                      event.clientX,
                      event.clientY,
                      event.currentTarget,
                      event.pointerId
                    );
                  }}
                />
              );
            })
          : null}
      </div>
    );
  }, [active, beginSession, editor, onOverlayKeyDown, origin.left, origin.top, t]);

  if (!rendered || !portalRef.current) return null;
  return createPortal(rendered, portalRef.current);
}

// packages/vue/src/editor/images/ImageSelectionOverlay.tsx
// Selection ring and eight resize handles for the selected drawing — geometry from layout records.

import {
  computed,
  defineComponent,
  ref,
  shallowRef,
  Teleport,
  watch,
  type PropType,
  type Ref,
} from 'vue';
import {
  captureImageMutationPreconditions,
  computeMovedImagePosition,
  IMAGE_OVERLAY_NUDGE_PT,
  IMAGE_OVERLAY_NUDGE_SHIFT_PT,
  isStaleImageInteractionCommit,
  selectedDrawingOverlayTargetOf,
  type ImageInteractionSession,
  type ImageOverlayScrollPort,
  type ImageResizeHandle,
  type SelectedDrawingOverlayTarget,
} from '@docx-editor.dev/core/editor';
import {
  computeImageResizeResult,
  createImageOverlayScrollPort,
  cssPixelsToLayoutPoints,
  finalizeImageOverlayInteraction,
  overlayFrameToSheetCssPixels,
  overlayHostOrigin,
  resizePreservesAspect,
} from '@docx-editor.dev/core/editor';
import type { DrawingPositionInput } from '@docx-editor.dev/core/editor';
import { useTranslation } from '../../i18n';
import { useDocxEditor } from '../context';
import { guardToolbarMousedown } from '../toolbar/ToolbarButton';

const HANDLES: readonly ImageResizeHandle[] = ['nw', 'n', 'ne', 'e', 'se', 's', 'sw', 'w'];
const AUTO_SCROLL_EDGE_PX = 40;
const AUTO_SCROLL_MAX_PT = 12;

interface PreviewState {
  readonly session: ImageInteractionSession;
  readonly bounds: SelectedDrawingOverlayTarget;
  readonly accumulatedScrollPt: number;
}

/** @public */
export interface ImageSelectionOverlayProps {
  containerRef: Ref<HTMLElement | null>;
  portalRef: Ref<HTMLElement | null>;
  scrollPort?: ImageOverlayScrollPort;
}

function handleLabelKey(handle: ImageResizeHandle): `imageOverlay.handle.${ImageResizeHandle}` {
  return `imageOverlay.handle.${handle}`;
}

function cursorForHandle(handle: ImageResizeHandle): string {
  switch (handle) {
    case 'nw':
    case 'se':
      return 'nwse-resize';
    case 'ne':
    case 'sw':
      return 'nesw-resize';
    case 'n':
    case 's':
      return 'ns-resize';
    default:
      return 'ew-resize';
  }
}

function handlePosition(handle: ImageResizeHandle): { readonly x: string; readonly y: string } {
  const map: Record<ImageResizeHandle, { x: string; y: string }> = {
    nw: { x: '0%', y: '0%' },
    n: { x: '50%', y: '0%' },
    ne: { x: '100%', y: '0%' },
    e: { x: '100%', y: '50%' },
    se: { x: '100%', y: '100%' },
    s: { x: '50%', y: '100%' },
    sw: { x: '0%', y: '100%' },
    w: { x: '0%', y: '50%' },
  };
  return map[handle];
}

function handleFromDelta(dx: number, dy: number): ImageResizeHandle {
  if (dx > 0 && dy > 0) return 'se';
  if (dx > 0 && dy < 0) return 'ne';
  if (dx < 0 && dy > 0) return 'sw';
  if (dx < 0 && dy < 0) return 'nw';
  if (dx > 0) return 'e';
  if (dx < 0) return 'w';
  if (dy > 0) return 's';
  return 'n';
}

/** @public */
export const ImageSelectionOverlay = defineComponent({
  name: 'ImageSelectionOverlay',
  props: {
    containerRef: { type: Object as PropType<Ref<HTMLElement | null>>, required: true },
    portalRef: { type: Object as PropType<Ref<HTMLElement | null>>, required: true },
    scrollPort: { type: Object as PropType<ImageOverlayScrollPort>, default: undefined },
  },
  setup(props) {
    const editorRef = useDocxEditor();
    const { t } = useTranslation();
    const target = ref<SelectedDrawingOverlayTarget | null>(null);
    const preview = ref<PreviewState | null>(null);
    // Where the surface's box begins inside the overlay's containing block. The surface
    // centres itself with an auto margin, so a viewport resize moves this origin without
    // any engine event firing. Held in a ref and measured in the observer (and once per
    // selection), never per render: `overlayHostOrigin` reads offsetLeft/offsetTop, which
    // forces layout, and preview renders arrive at pointermove frequency during a drag.
    const origin = shallowRef<{ readonly left: number; readonly top: number }>({
      left: 0,
      top: 0,
    });
    const refreshOrigin = (): void => {
      const next = overlayHostOrigin(props.containerRef.value);
      if (next.left !== origin.value.left || next.top !== origin.value.top) {
        origin.value = next;
      }
    };
    const previewRef = shallowRef<PreviewState | null>(null);
    watch(
      preview,
      (next) => {
        previewRef.value = next;
      },
      { flush: 'sync' }
    );
    const pointerStartRef = shallowRef<{ readonly x: number; readonly y: number } | null>(null);
    const captureTargetRef = shallowRef<HTMLElement | null>(null);
    const overlayRef = shallowRef<HTMLDivElement | null>(null);
    const focusRequestedForDrawingRef = shallowRef<string | null>(null);
    const scrollPortRef = shallowRef<ImageOverlayScrollPort | null>(null);

    watch(
      [() => props.containerRef.value, () => target.value?.id],
      ([container], _, onCleanup) => {
        if (!container) return;
        const onPointerDown = (event: PointerEvent): void => {
          const element = event.target instanceof Element ? event.target : null;
          if (element?.closest('.docx-drawing-textbox-content')) {
            focusRequestedForDrawingRef.value = null;
            return;
          }
          const drawingId = element
            ?.closest<HTMLElement>('[data-drawing-node-id]')
            ?.getAttribute('data-drawing-node-id');
          focusRequestedForDrawingRef.value = drawingId ?? null;
          if (drawingId && drawingId === target.value?.id) {
            queueMicrotask(() => overlayRef.value?.focus({ preventScroll: true }));
          }
        };
        container.addEventListener('pointerdown', onPointerDown, { capture: true });
        onCleanup(() =>
          container.removeEventListener('pointerdown', onPointerDown, { capture: true })
        );
      },
      { flush: 'post' }
    );

    watch(
      editorRef,
      (editor, _, onCleanup) => {
        if (!editor) {
          target.value = null;
          return;
        }
        const sync = (): void => {
          target.value = selectedDrawingOverlayTargetOf(editor.surface);
        };
        const syncAfterCommit = (): void => {
          queueMicrotask(sync);
        };
        sync();
        const off = [editor.on('change', syncAfterCommit), editor.on('selectionChange', sync)];
        onCleanup(() => {
          for (const unsubscribe of off) unsubscribe();
        });
      },
      { immediate: true, flush: 'post' }
    );

    watch(
      [() => props.portalRef.value, () => props.containerRef.value],
      ([portal, container], _, onCleanup) => {
        refreshOrigin();
        if ((!portal && !container) || typeof ResizeObserver !== 'function') return;
        const observer = new ResizeObserver(refreshOrigin);
        if (portal) observer.observe(portal);
        // The origin is a function of BOTH boxes: the surface's own width moves the
        // centring margin at a constant portal box (a page-size change), so observe both.
        if (container) observer.observe(container);
        onCleanup(() => observer.disconnect());
      },
      { immediate: true, flush: 'post' }
    );
    // A fresh selection re-measures a moved origin the observer could not see.
    watch(target, refreshOrigin, { flush: 'post' });

    watch(
      [() => props.scrollPort, () => props.containerRef.value, editorRef],
      ([scrollPortOverride, container, editor], _, onCleanup) => {
        if (scrollPortOverride) {
          scrollPortRef.value = scrollPortOverride;
          return;
        }
        if (!container || !editor?.surface) return;
        const scroller = container.closest('.docx-editor__scroll-container') as HTMLElement | null;
        if (!scroller) return;
        const coordinates = editor.surface.overlayCoordinates();
        scrollPortRef.value = createImageOverlayScrollPort(scroller, coordinates.paintScale);
        onCleanup(() => {
          scrollPortRef.value = null;
        });
      },
      { flush: 'post' }
    );

    const clearPreview = (): void => {
      preview.value = null;
      pointerStartRef.value = null;
      const captured = captureTargetRef.value;
      captureTargetRef.value = null;
      if (captured) {
        try {
          captured.releasePointerCapture(
            (captured as HTMLElement & { _lastPointerId?: number })._lastPointerId ?? 0
          );
        } catch {
          // Already released.
        }
      }
    };

    const beginSession = (
      mode: 'move' | 'resize',
      handle: ImageResizeHandle | null,
      active: SelectedDrawingOverlayTarget,
      clientX: number,
      clientY: number,
      captureTarget: HTMLElement,
      pointerId: number
    ): void => {
      const editor = editorRef.value;
      if (!editor?.surface) return;
      // The flushing read FIRST: a pass still parked on the scheduler's timer would
      // otherwise publish mid-drag and fail the commit's staleness check for nothing, so
      // the session is stamped against the flushed layout. Preconditions are captured
      // after it, so a flush that lands buffered input cannot stamp a selection the
      // flush is about to move.
      const scope = editor.surface.activeScope();
      if (scope.kind === 'frame' && !editor.surface.selectDrawing(active.id, scope.hostParagraphId))
        return;
      const layout = editor.surface.layout();
      const pre = captureImageMutationPreconditions(editor);
      if (!pre) return;
      pointerStartRef.value = Object.freeze({ x: clientX, y: clientY });
      captureTargetRef.value = captureTarget;
      (captureTarget as HTMLElement & { _lastPointerId?: number })._lastPointerId = pointerId;
      try {
        captureTarget.setPointerCapture(pointerId);
      } catch {
        // Capture is best-effort.
      }
      preview.value = {
        session: Object.freeze({
          drawingNodeId: active.id,
          startBounds: Object.freeze({
            x: active.x,
            y: active.y,
            width: active.width,
            height: active.height,
          }),
          startWidthEmu: active.widthEmu,
          startHeightEmu: active.heightEmu,
          startPosition: active.position,
          anchorFrameOrigin: active.anchorFrameOrigin,
          transform: active.transform,
          mode,
          handle,
          preconditions: pre,
          layoutRevision: layout.revision,
          packageRevision: editor.surface.session.packageRevision(),
          kind: active.kind,
        }),
        bounds: active,
        accumulatedScrollPt: 0,
      };
      overlayRef.value?.focus({ preventScroll: true });
    };

    const commitSession = (
      session: ImageInteractionSession,
      widthEmu: number,
      heightEmu: number,
      _bounds: {
        readonly x: number;
        readonly y: number;
        readonly width: number;
        readonly height: number;
      },
      position: DrawingPositionInput | null
    ): void => {
      const editor = editorRef.value;
      if (!editor) return;
      if (isStaleImageInteractionCommit(editor, session)) {
        clearPreview();
        return;
      }
      if (session.mode === 'resize') {
        editor.exec({
          type: 'setImageProperties',
          widthEmu,
          heightEmu,
          ...(position?.mode === 'simple'
            ? {
                horizontalEmu: position.horizontalEmu,
                verticalEmu: position.verticalEmu,
              }
            : {}),
          ...(position?.mode === 'frame'
            ? {
                ...(position.horizontalEmu !== undefined
                  ? { horizontalEmu: position.horizontalEmu }
                  : {}),
                ...(position.verticalEmu !== undefined
                  ? { verticalEmu: position.verticalEmu }
                  : {}),
              }
            : {}),
        });
      } else if (session.mode === 'move' && position) {
        editor.exec({ type: 'setImagePosition', ...position });
      }
      clearPreview();
    };

    const onOverlayKeyDown = (event: KeyboardEvent): void => {
      const editor = editorRef.value;
      if (!editor) return;
      const active = previewRef.value?.bounds ?? selectedDrawingOverlayTargetOf(editor.surface);
      if (!active) return;
      if (previewRef.value && event.key === 'Escape') {
        event.preventDefault();
        event.stopPropagation();
        clearPreview();
        return;
      }
      if (previewRef.value) return;
      const step = event.shiftKey ? IMAGE_OVERLAY_NUDGE_SHIFT_PT : IMAGE_OVERLAY_NUDGE_PT;
      if (event.key === 'Delete' || event.key === 'Backspace') {
        event.preventDefault();
        event.stopPropagation();
        editor.exec({ type: 'deleteImage' });
        return;
      }
      if (!['ArrowUp', 'ArrowDown', 'ArrowLeft', 'ArrowRight'].includes(event.key)) return;
      event.preventDefault();
      event.stopPropagation();
      const dx = event.key === 'ArrowLeft' ? -step : event.key === 'ArrowRight' ? step : 0;
      const dy = event.key === 'ArrowUp' ? -step : event.key === 'ArrowDown' ? step : 0;
      if (event.altKey) {
        if (!active.canResize) return;
        const handle = handleFromDelta(dx, dy);
        const resized = computeImageResizeResult({
          handle,
          startWidthEmu: active.widthEmu,
          startHeightEmu: active.heightEmu,
          startBounds: { x: active.x, y: active.y, width: active.width, height: active.height },
          startPosition: active.position,
          anchorFrameOrigin: active.anchorFrameOrigin,
          deltaXPt: dx,
          deltaYPt: dy,
          transform: active.transform,
          preserveAspect: resizePreservesAspect(
            handle,
            active.aspectLocked,
            event.shiftKey,
            active.textbox
          ),
          kind: active.kind,
        });
        editor.exec({
          type: 'setImageProperties',
          widthEmu: resized.widthEmu,
          heightEmu: resized.heightEmu,
          ...(resized.position?.mode === 'simple'
            ? {
                horizontalEmu: resized.position.horizontalEmu,
                verticalEmu: resized.position.verticalEmu,
              }
            : {}),
          ...(resized.position?.mode === 'frame'
            ? {
                ...(resized.position.horizontalEmu !== undefined
                  ? { horizontalEmu: resized.position.horizontalEmu }
                  : {}),
                ...(resized.position.verticalEmu !== undefined
                  ? { verticalEmu: resized.position.verticalEmu }
                  : {}),
              }
            : {}),
        });
        return;
      }
      if (active.kind !== 'anchored' || !active.canMove || !active.position) return;
      const moved = computeMovedImagePosition(active.position, dx, dy);
      editor.exec({ type: 'setImagePosition', ...moved });
    };

    watch(
      [preview, editorRef, () => props.containerRef.value],
      ([currentPreview, editor, container], _, onCleanup) => {
        if (!currentPreview || !editor?.surface) return;
        const coordinates = editor.surface.overlayCoordinates();
        const onPointerMove = (event: PointerEvent) => {
          const current = previewRef.value;
          const startPointer = pointerStartRef.value;
          if (!current || !startPointer) return;
          const deltaX = cssPixelsToLayoutPoints(
            event.clientX - startPointer.x,
            coordinates.paintScale
          );
          const deltaY = cssPixelsToLayoutPoints(
            event.clientY - startPointer.y,
            coordinates.paintScale
          );
          if (current.session.mode === 'move') {
            let scrollDelta = 0;
            const scrollPort = scrollPortRef.value;
            const scroller = container?.closest(
              '.docx-editor__scroll-container'
            ) as HTMLElement | null;
            if (scrollPort && scroller) {
              const scrollerRect = scroller.getBoundingClientRect();
              if (event.clientY > scrollerRect.bottom - AUTO_SCROLL_EDGE_PX)
                scrollDelta = AUTO_SCROLL_MAX_PT;
              else if (event.clientY < scrollerRect.top + AUTO_SCROLL_EDGE_PX)
                scrollDelta = -AUTO_SCROLL_MAX_PT;
              if (scrollDelta !== 0) scrollDelta = scrollPort.scrollBy(scrollDelta);
            }
            const accumulatedScrollPt = current.accumulatedScrollPt + scrollDelta;
            preview.value = {
              ...current,
              accumulatedScrollPt,
              bounds: Object.freeze({
                ...current.bounds,
                x: current.session.startBounds.x + deltaX,
                y: current.session.startBounds.y + deltaY + accumulatedScrollPt,
              }),
            };
            return;
          }
          if (!current.session.handle) return;
          const resized = computeImageResizeResult({
            handle: current.session.handle,
            startWidthEmu: current.session.startWidthEmu,
            startHeightEmu: current.session.startHeightEmu,
            startBounds: current.session.startBounds,
            startPosition: current.session.startPosition,
            anchorFrameOrigin: current.session.anchorFrameOrigin,
            deltaXPt: deltaX,
            deltaYPt: deltaY,
            transform: current.session.transform,
            preserveAspect: resizePreservesAspect(
              current.session.handle,
              current.bounds.aspectLocked,
              event.shiftKey,
              current.bounds.textbox
            ),
            kind: current.session.kind,
          });
          preview.value = {
            ...current,
            bounds: Object.freeze({
              ...current.bounds,
              x: resized.previewBounds.x,
              y: resized.previewBounds.y,
              width: resized.previewBounds.width,
              height: resized.previewBounds.height,
              widthEmu: resized.widthEmu,
              heightEmu: resized.heightEmu,
            }),
          };
        };
        const finish = (event: PointerEvent) => {
          const current = previewRef.value;
          if (!current) return;
          if (event.type === 'pointerup') {
            const deltaX = cssPixelsToLayoutPoints(
              event.clientX - (pointerStartRef.value?.x ?? event.clientX),
              coordinates.paintScale
            );
            const deltaY = cssPixelsToLayoutPoints(
              event.clientY - (pointerStartRef.value?.y ?? event.clientY),
              coordinates.paintScale
            );
            const finalized = finalizeImageOverlayInteraction({
              session: current.session,
              deltaXPt: deltaX,
              deltaYPt: deltaY,
              accumulatedScrollPt: current.accumulatedScrollPt,
              aspectLocked: current.bounds.aspectLocked,
              textbox: current.bounds.textbox,
              shiftKey: event.shiftKey,
              anchorFrameOrigin: current.session.anchorFrameOrigin,
            });
            commitSession(
              current.session,
              finalized.widthEmu,
              finalized.heightEmu,
              finalized.previewBounds,
              finalized.position
            );
          } else clearPreview();
        };
        window.addEventListener('pointermove', onPointerMove);
        window.addEventListener('pointerup', finish);
        window.addEventListener('pointercancel', finish);
        onCleanup(() => {
          window.removeEventListener('pointermove', onPointerMove);
          window.removeEventListener('pointerup', finish);
          window.removeEventListener('pointercancel', finish);
        });
      },
      { flush: 'post' }
    );

    watch(
      target,
      (nextTarget) => {
        if (!nextTarget || focusRequestedForDrawingRef.value !== nextTarget.id) return;
        focusRequestedForDrawingRef.value = null;
        overlayRef.value?.focus({ preventScroll: true });
      },
      { flush: 'post' }
    );

    const active = computed(() => preview.value?.bounds ?? target.value);

    return () => {
      const editor = editorRef.value;
      const current = active.value;
      const portal = props.portalRef.value;
      if (!editor?.surface || !current || !portal) return null;
      const layout = editor.surface.publishedLayout();
      const coordinates = editor.surface.overlayCoordinates();
      const sheetRect = overlayFrameToSheetCssPixels(
        layout,
        {
          pageIndex: current.pageIndex,
          x: current.x,
          y: current.y,
          width: current.width,
          height: current.height,
        },
        coordinates
      );
      // Sheet-space is surface-relative; the overlay's containing block is not the surface.
      // Reading the reactive `origin` re-runs this render when the measured origin moves.
      const rect = {
        left: sheetRect.left + origin.value.left,
        top: sheetRect.top + origin.value.top,
        width: sheetRect.width,
        height: sheetRect.height,
      };
      const showHandles = current.canResize;
      const showMove = current.kind === 'anchored' && current.canMove;
      return (
        <Teleport to={portal}>
          <div
            ref={(el: unknown) => {
              overlayRef.value = el instanceof HTMLDivElement ? el : null;
            }}
            class="docx-image-selection-overlay"
            data-drawing-node-id={current.id}
            tabindex={0}
            onKeydown={onOverlayKeyDown}
          >
            <div
              class={`docx-image-selection-overlay__frame${
                showMove ? ' docx-editor-one-surface__overlay-control' : ''
              }`}
              data-textbox={current.textbox ? 'true' : undefined}
              role="group"
              aria-label={t('imageOverlay.selection')}
              style={{
                left: `${rect.left}px`,
                top: `${rect.top}px`,
                width: `${rect.width}px`,
                height: `${rect.height}px`,
                cursor: showMove ? 'move' : 'default',
              }}
              onPointerdown={(event: PointerEvent) => {
                guardToolbarMousedown(event as unknown as MouseEvent);
                if (!showMove || !current.position) return;
                if (event.button !== 0) return;
                event.preventDefault();
                event.stopPropagation();
                beginSession(
                  'move',
                  null,
                  current,
                  event.clientX,
                  event.clientY,
                  event.currentTarget as HTMLElement,
                  event.pointerId
                );
              }}
            />
            {showHandles
              ? HANDLES.map((handle) => {
                  const pos = handlePosition(handle);
                  return (
                    <button
                      key={handle}
                      type="button"
                      class="docx-image-selection-overlay__handle"
                      aria-label={t(handleLabelKey(handle))}
                      tabindex={0}
                      style={{
                        left: `calc(${rect.left}px + ${rect.width}px * ${parseFloat(pos.x) / 100} - 5px)`,
                        top: `calc(${rect.top}px + ${rect.height}px * ${parseFloat(pos.y) / 100} - 5px)`,
                        cursor: cursorForHandle(handle),
                      }}
                      onPointerdown={(event: PointerEvent) => {
                        guardToolbarMousedown(event as unknown as MouseEvent);
                        if (event.button !== 0) return;
                        event.preventDefault();
                        event.stopPropagation();
                        beginSession(
                          'resize',
                          handle,
                          current,
                          event.clientX,
                          event.clientY,
                          event.currentTarget as HTMLElement,
                          event.pointerId
                        );
                      }}
                    />
                  );
                })
              : null}
          </div>
        </Teleport>
      );
    };
  },
});
