// packages/react/src/editor/images/ImageInsert.tsx
import type { DocxEditorChildren } from '../../docx-editor-children';
import type { ReactNode } from 'react';
// Shared insert-image wiring: hidden file input, preflight, and async dispatch.
//
// Toolbar and menu both trigger the same picker; Content attaches paste/drop to the same path.

import { createContext, useCallback, useContext, useMemo, useRef } from 'react';
import { executeImageCommand, toolbarCommandState } from '@docx-editor.dev/core/editor';
import { useTranslation } from '../../i18n';
import type { TranslationKey } from '../../i18n';
import { useDocxEditor } from '../context';
import { useEditorState } from '../useEditorState';
import { normalizeImageBytes } from './normalizeImageFile';
import { useToolbarLabel } from '../toolbar/toolbar-context';
import { chromeControlForSlot, chromeIcon, guardToolbarMousedown } from '../toolbar/ToolbarButton';
import { Slot } from '../toolbar/Slot';

const ACCEPT = 'image/png,image/jpeg,image/gif';

export interface ImageInsertContextValue {
  readonly openFilePicker: () => void;
  readonly insertFromFileList: (files: FileList | File[] | null | undefined) => Promise<void>;
  readonly insertFromDataTransfer: (data: DataTransfer | null) => Promise<void>;
  readonly isEnabled: boolean;
  readonly disabledReason: string | null;
  readonly inputRef: React.RefObject<HTMLInputElement | null>;
  readonly onInputChange: (event: React.ChangeEvent<HTMLInputElement>) => void;
}

const ImageInsertContext = createContext<ImageInsertContextValue | null>(null);

export function useImageInsert(): ImageInsertContextValue {
  const context = useContext(ImageInsertContext);
  if (!context) {
    throw new Error('useImageInsert must be used within ImageInsertProvider');
  }
  return context;
}

/** Optional hook — returns null outside a provider (Content may mount without toolbar). */
export function useImageInsertOptional(): ImageInsertContextValue | null {
  return useContext(ImageInsertContext);
}

export interface ImageInsertProviderProps {
  children: ReactNode;
}

export function ImageInsertProvider({ children }: ImageInsertProviderProps) {
  const editor = useDocxEditor();
  const { t } = useTranslation();
  const inputRef = useRef<HTMLInputElement | null>(null);
  const busyRef = useRef(false);

  const selectInsertState = useCallback(
    () => toolbarCommandState(editor, 'image.insert'),
    [editor]
  );
  const insertState = useEditorState(
    selectInsertState,
    (a, b) => a.enabled === b.enabled && a.disabledReason === b.disabledReason
  );
  const isEnabled = insertState.enabled;
  const disabledReason = insertState.disabledReason;

  const insertBytes = useCallback(
    async (bytes: Uint8Array) => {
      if (!editor || busyRef.current) return;
      const normalized = normalizeImageBytes(bytes);
      if (!normalized.ok) {
        window.alert(t(normalized.reasonKey as TranslationKey));
        return;
      }
      const command = {
        type: 'insertImage' as const,
        data: normalized.bytes,
        mime: normalized.mime,
        widthPoints: normalized.widthPoints,
        heightPoints: normalized.heightPoints,
      };
      const gate = editor.canExecuteImageCommand?.(command);
      if (gate && !gate.ok) {
        window.alert(gate.reason ?? t('imageInsert.errors.refused'));
        return;
      }
      busyRef.current = true;
      try {
        const result = await executeImageCommand(editor, command);
        if (!result.ok) {
          window.alert(result.reason ?? t('imageInsert.errors.refused'));
        } else {
          editor.focus();
        }
      } finally {
        busyRef.current = false;
      }
    },
    [editor, t]
  );

  const insertFromFileList = useCallback(
    async (files: FileList | File[] | null | undefined) => {
      const file = files?.[0];
      if (!file) return;
      const buffer = await file.arrayBuffer();
      await insertBytes(new Uint8Array(buffer));
    },
    [insertBytes]
  );

  const insertFromDataTransfer = useCallback(
    async (data: DataTransfer | null) => {
      if (!data) return;
      const file = [...data.files].find((candidate) => candidate.type.startsWith('image/'));
      if (file) {
        await insertFromFileList([file]);
        return;
      }
      for (const item of data.items) {
        if (item.kind !== 'file' || !item.type.startsWith('image/')) continue;
        const blob = item.getAsFile();
        if (!blob) continue;
        const buffer = await blob.arrayBuffer();
        await insertBytes(new Uint8Array(buffer));
        return;
      }
    },
    [insertBytes, insertFromFileList]
  );

  const openFilePicker = useCallback(() => {
    if (!isEnabled) return;
    inputRef.current?.click();
  }, [isEnabled]);

  const onInputChange = useCallback(
    async (event: React.ChangeEvent<HTMLInputElement>) => {
      const input = event.currentTarget;
      await insertFromFileList(input.files);
      input.value = '';
    },
    [insertFromFileList]
  );

  const value = useMemo(
    (): ImageInsertContextValue => ({
      openFilePicker,
      insertFromFileList,
      insertFromDataTransfer,
      isEnabled,
      disabledReason,
      inputRef,
      onInputChange,
    }),
    [
      openFilePicker,
      insertFromFileList,
      insertFromDataTransfer,
      isEnabled,
      disabledReason,
      onInputChange,
    ]
  );

  return (
    <ImageInsertContext.Provider value={value}>
      <input
        ref={inputRef}
        type="file"
        accept={ACCEPT}
        className="docx-image-insert__input"
        tabIndex={-1}
        aria-hidden="true"
        onChange={onInputChange}
        onMouseDown={(event) => event.stopPropagation()}
      />
      {children}
    </ImageInsertContext.Provider>
  );
}

/** Props for the toolbar/menu insert trigger. @public */
export interface ImageInsertTriggerProps {
  className?: string;
  hidden?: boolean;
  asChild?: boolean;
  children?: DocxEditorChildren;
}

/** Toolbar insert-image control — opens the shared file picker. @public */
export function ImageInsertTrigger({
  className,
  hidden,
  asChild,
  children,
}: ImageInsertTriggerProps) {
  const { openFilePicker, isEnabled, disabledReason } = useImageInsert();
  const label = useToolbarLabel();
  if (hidden) return null;
  const control = chromeControlForSlot('image.insert');
  const text = label(control?.labelKey ?? 'toolbar.image');
  const shared = {
    type: 'button' as const,
    className: `docx-toolbar__button${className ? ` ${className}` : ''}`,
    'data-slot': 'image.insert',
    disabled: !isEnabled,
    ...(!isEnabled ? { 'data-disabled': '' } : {}),
    'aria-label': text,
    title: disabledReason ?? text,
    onMouseDown: guardToolbarMousedown,
    onClick: openFilePicker,
  };
  if (asChild) return <Slot {...shared}>{children}</Slot>;
  return <button {...shared}>{children ?? chromeIcon(control?.paths)}</button>;
}

ImageInsertTrigger.docxSlot = 'image.insert' as const;

export const ToolbarImageInsert = Object.assign(ImageInsertTrigger, {
  docxSlot: 'image.insert' as const,
});

// packages/vue/src/editor/images/ImageInsert.tsx
import { defineComponent, inject, provide, ref, type InjectionKey } from 'vue';
import { executeImageCommand, toolbarCommandState } from '@docx-editor.dev/core/editor';
import { useTranslation, type TranslationKey } from '../../i18n';
import { useDocxEditor } from '../context';
import { useEditorState } from '../useEditorState';
import { normalizeImageBytes } from './normalizeImageFile';
import { useToolbarLabel } from '../toolbar/toolbar-context';
import { chromeControlForSlot, chromeIcon, guardToolbarMousedown } from '../toolbar/ToolbarButton';
import { Slot } from '../toolbar/Slot';

const ACCEPT = 'image/png,image/jpeg,image/gif';

/** @public */
export interface ImageInsertContextValue {
  readonly openFilePicker: () => void;
  readonly insertFromFileList: (files: FileList | File[] | null | undefined) => Promise<void>;
  readonly insertFromDataTransfer: (data: DataTransfer | null) => Promise<void>;
  readonly isEnabled: boolean;
  readonly disabledReason: string | null;
  readonly inputRef: { readonly value: HTMLInputElement | null };
  readonly onInputChange: (event: Event) => void;
}

const ImageInsertContextKey: InjectionKey<ImageInsertContextValue> = Symbol('ImageInsertContext');

/** @public */
export function useImageInsert(): ImageInsertContextValue {
  const context = inject(ImageInsertContextKey, null);
  if (!context) {
    throw new Error('useImageInsert must be used within ImageInsertProvider');
  }
  return context;
}

/** @public */
export function useImageInsertOptional(): ImageInsertContextValue | null {
  return inject(ImageInsertContextKey, null);
}

/** @public */
export interface ImageInsertProviderProps {
  // children via slots
}

/** @public */
export const ImageInsertProvider = defineComponent({
  name: 'ImageInsertProvider',
  setup(_, { slots }) {
    const editorRef = useDocxEditor();
    const { t } = useTranslation();
    const inputRef = ref<HTMLInputElement | null>(null);
    const busyRef = ref(false);

    const insertState = useEditorState(
      () => toolbarCommandState(editorRef.value, 'image.insert'),
      (a, b) => a.enabled === b.enabled && a.disabledReason === b.disabledReason
    );

    const insertBytes = async (bytes: Uint8Array) => {
      const editor = editorRef.value;
      if (!editor || busyRef.value) return;
      const normalized = normalizeImageBytes(bytes);
      if (!normalized.ok) {
        window.alert(t.value(normalized.reasonKey as TranslationKey));
        return;
      }
      const command = {
        type: 'insertImage' as const,
        data: normalized.bytes,
        mime: normalized.mime,
        widthPoints: normalized.widthPoints,
        heightPoints: normalized.heightPoints,
      };
      const gate = editor.canExecuteImageCommand?.(command);
      if (gate && !gate.ok) {
        window.alert(gate.reason ?? t.value('imageInsert.errors.refused'));
        return;
      }
      busyRef.value = true;
      try {
        const result = await executeImageCommand(editor, command);
        if (!result.ok) {
          window.alert(result.reason ?? t.value('imageInsert.errors.refused'));
        } else {
          editor.focus();
        }
      } finally {
        busyRef.value = false;
      }
    };

    const insertFromFileList = async (files: FileList | File[] | null | undefined) => {
      const file = files?.[0];
      if (!file) return;
      const buffer = await file.arrayBuffer();
      await insertBytes(new Uint8Array(buffer));
    };

    const insertFromDataTransfer = async (data: DataTransfer | null) => {
      if (!data) return;
      const file = [...data.files].find((candidate) => candidate.type.startsWith('image/'));
      if (file) {
        await insertFromFileList([file]);
        return;
      }
      for (const item of data.items) {
        if (item.kind !== 'file' || !item.type.startsWith('image/')) continue;
        const blob = item.getAsFile();
        if (!blob) continue;
        const buffer = await blob.arrayBuffer();
        await insertBytes(new Uint8Array(buffer));
        return;
      }
    };

    const openFilePicker = () => {
      if (!insertState.value.enabled) return;
      inputRef.value?.click();
    };

    const onInputChange = async (event: Event) => {
      const input = event.currentTarget as HTMLInputElement;
      await insertFromFileList(input.files);
      input.value = '';
    };

    const context: ImageInsertContextValue = {
      openFilePicker,
      insertFromFileList,
      insertFromDataTransfer,
      get isEnabled() {
        return insertState.value.enabled;
      },
      get disabledReason() {
        return insertState.value.disabledReason;
      },
      inputRef,
      onInputChange,
    };

    provide(ImageInsertContextKey, context);

    return () => [
      <input
        ref={inputRef}
        type="file"
        accept={ACCEPT}
        class="docx-image-insert__input"
        tabindex={-1}
        aria-hidden="true"
        onChange={onInputChange}
        onMousedown={(event: MouseEvent) => event.stopPropagation()}
      />,
      slots.default?.(),
    ];
  },
});

/** @public */
export interface ImageInsertTriggerProps {
  className?: string;
  hidden?: boolean;
  asChild?: boolean;
}

/** @public */
export const ImageInsertTrigger = defineComponent({
  name: 'ImageInsertTrigger',
  props: {
    className: { type: String, default: undefined },
    hidden: { type: Boolean, default: undefined },
    asChild: { type: Boolean, default: undefined },
  },
  setup(props, { slots }) {
    const insert = useImageInsert();
    const label = useToolbarLabel();
    return () => {
      if (props.hidden) return null;
      const control = chromeControlForSlot('image.insert');
      const text = label(control?.labelKey ?? 'toolbar.image');
      const shared = {
        type: 'button' as const,
        class: `docx-toolbar__button${props.className ? ` ${props.className}` : ''}`,
        'data-slot': 'image.insert',
        disabled: !insert.isEnabled,
        ...(!insert.isEnabled ? { 'data-disabled': '' } : {}),
        'aria-label': text,
        title: insert.disabledReason ?? text,
        onMousedown: guardToolbarMousedown,
        onClick: insert.openFilePicker,
      };
      if (props.asChild) return <Slot {...shared}>{slots.default?.()}</Slot>;
      return <button {...shared}>{slots.default?.() ?? chromeIcon(control?.paths)}</button>;
    };
  },
});
(ImageInsertTrigger as { docxSlot?: string }).docxSlot = 'image.insert';

/** @public */
export const ToolbarImageInsert = Object.assign(ImageInsertTrigger, {
  docxSlot: 'image.insert' as const,
});
