// packages/react/src/components/sidebar/TrackedChangeCard.tsx
import type { Comment } from '@eigenpal/docx-editor-core/types/content';
import { MaterialSymbol } from '../ui/Icons';
import type { SidebarItemRenderProps } from '../../plugin-api/types';
import type { TrackedChangeEntry } from './cardUtils';
import { formatDate, getInitials, avatarStyle, ICON_BUTTON_STYLE, truncateText } from './cardUtils';
import { ReplyThread } from './ReplyThread';
import { ReplyInput } from './ReplyInput';
import { CARD_STYLE_COLLAPSED, CARD_STYLE_EXPANDED } from './cardStyles';
import { useTranslation } from '../../i18n';

export interface TrackedChangeCardProps extends SidebarItemRenderProps {
  change: TrackedChangeEntry;
  replies: Comment[];
  /**
   * @deprecated Prefer `onAcceptById`. Range-based accept only clears
   * marks within `(from, to)` and silently leaves paragraph-mark and
   * coalesced sibling sites behind. Kept as fallback for hosts that
   * haven't migrated to the by-id channel.
   */
  onAccept?: (from: number, to: number) => void;
  /**
   * @deprecated Prefer `onRejectById`. Same caveat as `onAccept`.
   */
  onReject?: (from: number, to: number) => void;
  /**
   * Accept every site of the revision. Walks the doc for all sites
   * sharing the `revisionId` (inline marks + paragraph attrs + table
   * row/cell attrs) and clears them in one transaction. This is the
   * right channel for any coalesced revision.
   */
  onAcceptById?: (revisionId: number) => void;
  /** Reject every site of the revision. Counterpart to `onAcceptById`. */
  onRejectById?: (revisionId: number) => void;
  onReply?: (revisionId: number, text: string) => void;
}

export function TrackedChangeCard({
  change,
  replies,
  isExpanded,
  onToggleExpand,
  measureRef,
  onAccept,
  onReject,
  onAcceptById,
  onRejectById,
  onReply,
}: TrackedChangeCardProps) {
  const { t } = useTranslation();
  const authorName = change.author || t('trackedChanges.unknown');

  // Dispatch by `revisionId` whenever the host wired the by-id handlers.
  // A single coalesced edit can scatter sites across paragraphs (inline
  // marks + pPrIns attrs sharing one id); a range-based accept only clears
  // marks within the entry's (from, to), leaving sibling pPrIns attrs
  // behind so the user would need a second Accept. By-id walks every site
  // sharing the id in one pass — correct for all entry types.
  // Collect every `w:id` the card represents: the primary revisionId, the
  // replacement's distinct insertion id, plus any ids the extractor merged
  // in via (author, date) coalescing (a foreign editor minting fresh ids
  // per atomic edit). Walking the full set keeps Accept/Reject atomic.
  const allRevisionIds = (): number[] => {
    const ids = new Set<number>([change.revisionId]);
    if (change.type === 'replacement' && change.insertionRevisionId != null) {
      ids.add(change.insertionRevisionId);
    }
    for (const id of change.coalescedRevisionIds ?? []) ids.add(id);
    return [...ids];
  };
  const handleAccept = (e: React.MouseEvent) => {
    e.stopPropagation();
    if (onAcceptById) {
      for (const id of allRevisionIds()) onAcceptById(id);
    } else {
      onAccept?.(change.from, change.to);
    }
  };
  const handleReject = (e: React.MouseEvent) => {
    e.stopPropagation();
    if (onRejectById) {
      for (const id of allRevisionIds()) onRejectById(id);
    } else {
      onReject?.(change.from, change.to);
    }
  };

  return (
    <div
      ref={measureRef}
      className="docx-tracked-change-card"
      onClick={() => onToggleExpand()}
      onMouseDown={(e) => e.stopPropagation()}
      style={isExpanded ? CARD_STYLE_EXPANDED : CARD_STYLE_COLLAPSED}
    >
      <div style={{ display: 'flex', alignItems: 'flex-start', gap: 10 }}>
        <div style={avatarStyle(authorName)}>{getInitials(authorName)}</div>
        <div style={{ flex: 1, minWidth: 0 }}>
          <div style={{ fontSize: 13, fontWeight: 600, color: 'var(--doc-text)' }}>
            {authorName}
          </div>
          {change.date && (
            <div style={{ fontSize: 11, color: 'var(--doc-text-muted)' }}>
              {formatDate(change.date)}
            </div>
          )}
        </div>
        {isExpanded && (
          <div style={{ display: 'flex', gap: 4, marginTop: 2 }}>
            <button onClick={handleAccept} title={t('common.accept')} style={ICON_BUTTON_STYLE}>
              <MaterialSymbol name="check" size={20} />
            </button>
            <button onClick={handleReject} title={t('common.reject')} style={ICON_BUTTON_STYLE}>
              <MaterialSymbol name="close" size={20} />
            </button>
          </div>
        )}
      </div>

      <div style={{ fontSize: 13, lineHeight: '20px', color: 'var(--doc-text)', marginTop: 6 }}>
        {change.type === 'replacement' ? (
          <>
            {t('trackedChanges.replaced')}{' '}
            <span style={{ color: 'var(--doc-error)', fontWeight: 500 }}>
              &quot;{truncateText(change.deletedText || '')}&quot;
            </span>{' '}
            {t('trackedChanges.with')}{' '}
            <span style={{ color: 'var(--doc-success)', fontWeight: 500 }}>
              &quot;{truncateText(change.text)}&quot;
            </span>
          </>
        ) : change.type === 'paragraphMarkInsertion' ? (
          <>
            {t('revisions.paragraphMarkInserted')}
            {change.text ? (
              <>
                {': '}
                <span style={{ color: 'var(--doc-success)', fontWeight: 500 }}>
                  &quot;{truncateText(change.text)}&quot;
                </span>
              </>
            ) : null}
          </>
        ) : change.type === 'paragraphMarkDeletion' ? (
          <>
            {t('revisions.paragraphMarkDeleted')}
            {change.text ? (
              <>
                {': '}
                <span style={{ color: 'var(--doc-error)', fontWeight: 500 }}>
                  &quot;{truncateText(change.text)}&quot;
                </span>
              </>
            ) : null}
          </>
        ) : change.type === 'runPropertiesChanged' ? (
          <>
            {t('revisions.runPropertiesChanged')}
            {change.text ? (
              <>
                {': '}
                <span style={{ color: 'var(--doc-text-muted)', fontWeight: 500 }}>
                  &quot;{truncateText(change.text)}&quot;
                </span>
              </>
            ) : null}
          </>
        ) : change.type === 'paragraphPropertiesChanged' ? (
          <>
            {t('revisions.paragraphPropertiesChanged')}
            {change.text ? (
              <>
                {': '}
                <span style={{ color: 'var(--doc-text-muted)', fontWeight: 500 }}>
                  &quot;{truncateText(change.text)}&quot;
                </span>
              </>
            ) : null}
          </>
        ) : change.type === 'rowInserted' ? (
          <span style={{ color: 'var(--doc-success)', fontWeight: 500 }}>
            {t('revisions.rowInserted')}
          </span>
        ) : change.type === 'rowDeleted' ? (
          <span style={{ color: 'var(--doc-error)', fontWeight: 500 }}>
            {t('revisions.rowDeleted')}
          </span>
        ) : change.type === 'cellInserted' ? (
          <span style={{ color: 'var(--doc-success)', fontWeight: 500 }}>
            {t('revisions.cellInserted')}
          </span>
        ) : change.type === 'cellDeleted' ? (
          <span style={{ color: 'var(--doc-error)', fontWeight: 500 }}>
            {t('revisions.cellDeleted')}
          </span>
        ) : change.type === 'cellMerged' ? (
          <span style={{ color: 'var(--doc-text-muted)', fontWeight: 500 }}>
            {t('revisions.cellMerged')}
          </span>
        ) : change.type === 'rowPropertiesChanged' ? (
          <span style={{ color: 'var(--doc-text-muted)' }}>
            {t('revisions.rowPropertiesChanged')}
          </span>
        ) : change.type === 'cellPropertiesChanged' ? (
          <span style={{ color: 'var(--doc-text-muted)' }}>
            {t('revisions.cellPropertiesChanged')}
          </span>
        ) : change.type === 'tablePropertiesChanged' ? (
          <span style={{ color: 'var(--doc-text-muted)' }}>
            {t('revisions.tablePropertiesChanged')}
          </span>
        ) : change.type === 'tableInserted' ? (
          <span style={{ color: 'var(--doc-success)', fontWeight: 500 }}>
            {t('revisions.tableInserted')}
          </span>
        ) : change.type === 'tableDeleted' ? (
          <span style={{ color: 'var(--doc-error)', fontWeight: 500 }}>
            {t('revisions.tableDeleted')}
          </span>
        ) : (
          <>
            {change.type === 'insertion' ? t('trackedChanges.added') : t('trackedChanges.deleted')}{' '}
            <span
              style={{
                color: change.type === 'insertion' ? 'var(--doc-success)' : 'var(--doc-error)',
                fontWeight: 500,
              }}
            >
              &quot;{truncateText(change.text)}&quot;
            </span>
          </>
        )}
      </div>

      <ReplyThread replies={replies} isExpanded={isExpanded} />

      {isExpanded && <ReplyInput onSubmit={(text) => onReply?.(change.revisionId, text)} />}
    </div>
  );
}

// packages/vue/src/components/sidebar/TrackedChangeCard.vue
<!--
  Mirror of packages/react/src/components/sidebar/TrackedChangeCard.tsx.
  Same chrome (collapsed/expanded), same author/date layout,
  insertion/deletion/replacement formatting, accept/reject icon
  buttons in expanded state.
-->
<template>
  <div
    class="tc-card"
    :class="{ 'tc-card--expanded': expanded }"
    @click="$emit('click')"
    @mousedown.stop
  >
    <div class="tc-card__head">
      <Avatar :name="authorName" :size="32" />
      <div class="tc-card__author-block">
        <div class="tc-card__author">{{ authorName }}</div>
        <div v-if="change.date" class="tc-card__date">{{ formatDate(change.date) }}</div>
      </div>
      <div v-if="expanded" class="tc-card__actions">
        <button class="tc-card__icon-btn" :title="t('common.accept')" @click.stop="onAccept">
          <MaterialSymbol name="check" :size="20" />
        </button>
        <button class="tc-card__icon-btn" :title="t('common.reject')" @click.stop="onReject">
          <MaterialSymbol name="close" :size="20" />
        </button>
      </div>
    </div>

    <div class="tc-card__body">
      <template v-if="change.type === 'replacement'">
        {{ t('trackedChanges.replaced') }}
        <span class="tc-card__deleted"
          >&quot;{{ truncateText(change.deletedText || '') }}&quot;</span
        >
        {{ t('trackedChanges.with') }}
        <span class="tc-card__inserted">&quot;{{ truncateText(change.text) }}&quot;</span>
      </template>
      <template v-else-if="change.type === 'paragraphMarkInsertion'">
        {{ t('revisions.paragraphMarkInserted')
        }}<template v-if="change.text"
          >:
          <span class="tc-card__inserted"
            >&quot;{{ truncateText(change.text) }}&quot;</span
          ></template
        >
      </template>
      <template v-else-if="change.type === 'paragraphMarkDeletion'">
        {{ t('revisions.paragraphMarkDeleted')
        }}<template v-if="change.text"
          >:
          <span class="tc-card__deleted"
            >&quot;{{ truncateText(change.text) }}&quot;</span
          ></template
        >
      </template>
      <template v-else-if="change.type === 'runPropertiesChanged'">
        {{ t('revisions.runPropertiesChanged')
        }}<template v-if="change.text"
          >:
          <span class="tc-card__changed"
            >&quot;{{ truncateText(change.text) }}&quot;</span
          ></template
        >
      </template>
      <template v-else-if="change.type === 'paragraphPropertiesChanged'">
        {{ t('revisions.paragraphPropertiesChanged')
        }}<template v-if="change.text"
          >:
          <span class="tc-card__changed"
            >&quot;{{ truncateText(change.text) }}&quot;</span
          ></template
        >
      </template>
      <template v-else-if="change.type === 'rowInserted'">
        <span class="tc-card__inserted">{{ t('revisions.rowInserted') }}</span>
      </template>
      <template v-else-if="change.type === 'rowDeleted'">
        <span class="tc-card__deleted">{{ t('revisions.rowDeleted') }}</span>
      </template>
      <template v-else-if="change.type === 'cellInserted'">
        <span class="tc-card__inserted">{{ t('revisions.cellInserted') }}</span>
      </template>
      <template v-else-if="change.type === 'cellDeleted'">
        <span class="tc-card__deleted">{{ t('revisions.cellDeleted') }}</span>
      </template>
      <template v-else-if="change.type === 'cellMerged'">
        <span class="tc-card__changed">{{ t('revisions.cellMerged') }}</span>
      </template>
      <template v-else-if="change.type === 'rowPropertiesChanged'">
        <span class="tc-card__changed">{{ t('revisions.rowPropertiesChanged') }}</span>
      </template>
      <template v-else-if="change.type === 'cellPropertiesChanged'">
        <span class="tc-card__changed">{{ t('revisions.cellPropertiesChanged') }}</span>
      </template>
      <template v-else-if="change.type === 'tablePropertiesChanged'">
        <span class="tc-card__changed">{{ t('revisions.tablePropertiesChanged') }}</span>
      </template>
      <template v-else-if="change.type === 'tableInserted'">
        <span class="tc-card__inserted">{{ t('revisions.tableInserted') }}</span>
      </template>
      <template v-else-if="change.type === 'tableDeleted'">
        <span class="tc-card__deleted">{{ t('revisions.tableDeleted') }}</span>
      </template>
      <template v-else>
        {{ change.type === 'insertion' ? t('trackedChanges.added') : t('trackedChanges.deleted') }}
        <span :class="change.type === 'insertion' ? 'tc-card__inserted' : 'tc-card__deleted'">
          &quot;{{ truncateText(change.text) }}&quot;
        </span>
      </template>
    </div>

    <!-- Threaded replies + reply input — mirrors React
         TrackedChangeCard.tsx. Replies are child comments keyed by
         parentId === revisionId. -->
    <ReplyThread :replies="replies" :is-expanded="expanded" />

    <ReplyInput
      v-if="expanded"
      @submit="(text: string) => $emit('reply', change.revisionId, text)"
    />
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import type { Comment } from '@eigenpal/docx-editor-core/types/content';
import type { TrackedChangeEntry } from './sidebarUtils';
import { formatDate, truncateText } from './sidebarUtils';
import Avatar from './Avatar.vue';
import MaterialSymbol from '../ui/MaterialSymbol.vue';
import ReplyThread from './ReplyThread.vue';
import ReplyInput from './ReplyInput.vue';
import { useTranslation } from '../../i18n';

const { t } = useTranslation();

// `replies` is always supplied by UnifiedSidebar (`item.replies ?? []`),
// matching the sibling CommentCard. Required, like React's TrackedChangeCard.
const props = defineProps<{
  change: TrackedChangeEntry;
  expanded: boolean;
  replies: Comment[];
}>();

const emit = defineEmits<{
  (e: 'click'): void;
  (e: 'accept-by-id', revisionId: number): void;
  (e: 'reject-by-id', revisionId: number): void;
  (e: 'reply', revisionId: number, text: string): void;
}>();

const authorName = computed(() => props.change.author || t('trackedChanges.unknown'));

// Dispatch by `revisionId` whenever the host wired the by-id channel.
// Walks every id the card represents: the primary, the replacement's
// distinct insertion id, plus any ids the extractor merged in via
// (author, date) coalescing.
function allRevisionIds(): number[] {
  const ids = new Set<number>([props.change.revisionId]);
  if (props.change.type === 'replacement' && props.change.insertionRevisionId != null) {
    ids.add(props.change.insertionRevisionId);
  }
  for (const id of props.change.coalescedRevisionIds ?? []) ids.add(id);
  return [...ids];
}

function onAccept() {
  for (const id of allRevisionIds()) emit('accept-by-id', id);
}

function onReject() {
  for (const id of allRevisionIds()) emit('reject-by-id', id);
}
</script>

<style scoped>
.tc-card {
  padding: 8px 10px;
  border-radius: 8px;
  background: var(--doc-card);
  cursor: pointer;
  box-shadow: var(--doc-card-shadow);
  margin-bottom: 6px;
  transition:
    box-shadow 0.15s ease,
    background-color 0.15s ease,
    padding 0.15s ease;
}
.tc-card--expanded {
  padding: 10px 12px;
  background: var(--doc-surface);
  box-shadow: var(--doc-card-shadow-strong);
}
.tc-card__head {
  display: flex;
  align-items: flex-start;
  gap: 10px;
}
.tc-card__author-block {
  flex: 1;
  min-width: 0;
}
.tc-card__author {
  font-size: 13px;
  font-weight: 600;
  color: var(--doc-text);
}
.tc-card__date {
  font-size: 11px;
  color: var(--doc-text-muted);
}
.tc-card__actions {
  display: flex;
  gap: 4px;
  margin-top: 2px;
}
.tc-card__icon-btn {
  background: none;
  border: none;
  cursor: pointer;
  padding: 4px;
  color: var(--doc-text-muted);
  display: flex;
  border-radius: 50%;
}
.tc-card__icon-btn:hover {
  background: var(--doc-shadow-subtle);
}
.tc-card__body {
  font-size: 13px;
  line-height: 20px;
  color: var(--doc-text);
  margin-top: 6px;
}
.tc-card__deleted {
  color: var(--doc-error);
  font-weight: 500;
}
.tc-card__inserted {
  color: var(--doc-success);
  font-weight: 500;
}
.tc-card__changed {
  color: var(--doc-text-muted);
  font-weight: 500;
}
</style>
