// packages/pro/src/react/review-compose-boxes.tsx
/*
Copyright (c) 2026 EigenPal, Inc. All rights reserved.
Licensed under the EigenPal Pro Evaluation License 1.0 — see packages/pro/LICENSE.md.
Production use requires a commercial agreement: licensing@eigenpal.com
*/

import { useCallback, useEffect, useId, useRef, useState } from 'react';
import type { MouseEvent as ReactMouseEvent } from 'react';
import type { TranslationKey } from '@docx-editor.dev/i18n';
import type { ReviewAuthorInfo } from '@docx-editor.dev/core/editor';
import type { ReviewPartProps } from './review-types.ts';
import type { ReviewItemView } from './useReview.ts';
import { COMPACT_CARD_WIDTH } from './use-rail-geometry.ts';
import { authorCardStyle } from './review-author-styles.ts';
import { SEND_ICON, icon } from './review-icons.tsx';
import { initialsOf } from './review-shared.ts';

interface ComposePartDeps {
  readonly useRail: () => {
    readonly review: {
      readonly comment: (text: string, author?: string) => boolean;
      readonly reply: (item: ReviewItemView, text: string, author?: string) => boolean;
      readonly setActive: (key: string | null) => boolean;
    };
    readonly endDraft: () => void;
    readonly measure: (node: HTMLElement | null, key: string) => void;
    readonly readOnly: boolean;
    readonly draftAuthor: string | null;
    readonly draftAuthorInfo: ReviewAuthorInfo | undefined;
    readonly draftAuthorSlot: number;
  };
  readonly useItem: () => ReviewItemView | null;
  readonly useLabel: () => (key: TranslationKey) => string;
  readonly guardMousedown: (event: ReactMouseEvent) => void;
  readonly composeKey: string;
}

/** Build the draft and reply compose boxes against the rail's private contexts. */
export function createReviewComposeParts(deps: ComposePartDeps) {
  /** The compose box for a new comment. @public */
  function ReviewDraft({
    top = 0,
    left = null,
    className,
    hidden,
  }: ReviewPartProps & {
    top?: number;
    /**
     * Rail-local `left` for the COMPACT rail, where the strip is 32px wide and a box laid
     * out at column width would be cut by the viewport's edge. Null keeps the box in the
     * rail's own column, which is right whenever the column exists.
     */
    left?: number | null;
  }) {
    const { review, endDraft, measure, readOnly, draftAuthor, draftAuthorInfo, draftAuthorSlot } =
      deps.useRail();
    const t = deps.useLabel();
    const [text, setText] = useState('');
    const [refused, setRefused] = useState(false);
    const fieldRef = useRef<HTMLInputElement | null>(null);
    const fieldId = useId();

    // Mount-only: focus when a new draft opens in an editable document. Mode toggles keep the
    // same compose instance mounted, so this must not track `readOnly` or returning to editing
    // steals focus from the toolbar, a reply box, or the document.
    useEffect(() => {
      if (readOnly) return;
      fieldRef.current?.focus({ preventScroll: true });
      // eslint-disable-next-line react-hooks/exhaustive-deps -- open identity, not mode transitions
    }, []);

    const submit = useCallback(() => {
      if (readOnly || text.trim().length === 0) return;
      const landed = review.comment(text.trim());
      setRefused(!landed);
      if (landed) {
        setText('');
        endDraft();
      }
    }, [readOnly, text, review, endDraft]);

    if (hidden) return null;
    return (
      <div
        className={`docx-review__slot${className ? ` ${className}` : ''}${left === null ? '' : ' docx-review__slot--compact'}`}
        style={{
          position: 'absolute',
          top,
          ...(left === null ? {} : { left, width: COMPACT_CARD_WIDTH }),
        }}
        ref={(node) => {
          measure(node, deps.composeKey);
        }}
      >
        <div
          className="docx-review__card"
          data-testid="review-draft"
          data-draft=""
          {...(draftAuthor
            ? {
                'data-review-author': draftAuthor,
                'data-review-author-slot': draftAuthorSlot,
              }
            : {})}
          style={authorCardStyle(draftAuthor ?? undefined, draftAuthorInfo, draftAuthorSlot)}
        >
          <form
            className="docx-review__reply-box"
            onSubmit={(event) => {
              event.preventDefault();
              submit();
            }}
          >
            <label className="docx-editor-sr-only" htmlFor={fieldId}>
              {t('comments.addComment')}
            </label>
            <input
              id={fieldId}
              ref={fieldRef}
              data-testid="review-draft-input"
              className="docx-review__input"
              value={text}
              placeholder={t('comments.addComment')}
              readOnly={readOnly}
              {...(refused ? { 'aria-invalid': true } : {})}
              onChange={(event) => {
                if (readOnly) return;
                setRefused(false);
                setText(event.target.value);
              }}
              onKeyDown={(event) => {
                if (event.key === 'Escape') {
                  event.preventDefault();
                  endDraft();
                  return;
                }
                if (readOnly || event.key !== 'Enter') return;
                event.preventDefault();
                submit();
              }}
            />
            <div className="docx-review__reply-actions">
              <button
                type="button"
                data-testid="review-draft-cancel"
                className="docx-review__text-button"
                onMouseDown={deps.guardMousedown}
                onClick={endDraft}
              >
                {t('common.cancel')}
              </button>
              <button
                type="submit"
                data-testid="review-draft-submit"
                className="docx-review__submit"
                disabled={readOnly || text.trim().length === 0}
                title={readOnly ? t('editingMode.viewingHint') : undefined}
              >
                {t('common.comment')}
              </button>
            </div>
            {refused ? (
              <span className="docx-review__refused" role="alert">
                {t('review.commentRefused')}
              </span>
            ) : null}
          </form>
        </div>
      </div>
    );
  }
  ReviewDraft.docxReviewPart = 'Draft' as const;

  /** Draft state and submission for one reply line, held by whichever part owns it. */
  function useReplyDraft(entry: ReviewItemView | null) {
    const { review, readOnly } = deps.useRail();
    const [draft, setDraft] = useState('');
    const [refused, setRefused] = useState(false);
    const submit = useCallback(() => {
      if (!entry || readOnly || draft.trim().length === 0) return;
      const landed = review.reply(entry, draft.trim());
      setRefused(!landed);
      if (landed) setDraft('');
    }, [entry, readOnly, draft, review]);
    return { draft, setDraft, refused, setRefused, submit };
  }

  /**
   * The compact reply line the open card and the change balloon share: the configured
   * author's avatar, a borderless field, Cancel only while there is text, and a round send
   * button. Enter sends too.
   */
  function ReplyLine({
    state,
    className,
    onCancel,
  }: {
    readonly state: ReturnType<typeof useReplyDraft>;
    readonly className?: string;
    readonly onCancel?: () => void;
  }) {
    const { readOnly, draftAuthor, draftAuthorInfo, draftAuthorSlot } = deps.useRail();
    const t = deps.useLabel();
    const fieldId = useId();
    const { draft, setDraft, refused, setRefused, submit } = state;
    const avatarUrl = draftAuthorInfo?.style?.avatarUrl;
    return (
      <form
        className={`docx-review__reply-box${className ? ` ${className}` : ''}`}
        data-reply-line=""
        onSubmit={(event) => {
          event.preventDefault();
          submit();
        }}
      >
        <label className="docx-editor-sr-only" htmlFor={fieldId}>
          {t('comments.replyPlaceholder')}
        </label>
        {draftAuthor ? (
          <span
            className="docx-review__avatar docx-review__reply-avatar"
            data-testid="review-reply-avatar"
            aria-hidden="true"
            style={authorCardStyle(draftAuthor, draftAuthorInfo, draftAuthorSlot)}
          >
            {avatarUrl ? (
              <img
                className="docx-review__avatar-img"
                src={avatarUrl}
                alt=""
                loading="lazy"
                decoding="async"
                referrerPolicy="no-referrer"
              />
            ) : (
              initialsOf(draftAuthor)
            )}
          </span>
        ) : null}
        <input
          id={fieldId}
          data-testid="review-reply-input"
          className="docx-review__input"
          value={draft}
          placeholder={t('comments.replyPlaceholder')}
          readOnly={readOnly}
          {...(refused ? { 'aria-invalid': true, 'data-refused': '' } : {})}
          onChange={(event) => {
            if (readOnly) return;
            setRefused(false);
            setDraft(event.target.value);
          }}
          onClick={(event) => event.stopPropagation()}
          onKeyDown={(event) => {
            // The first Escape clears a draft, so a stray key never loses it with the card or
            // balloon. On an empty line it closes the card; in a balloon it bubbles to the
            // balloon, which closes itself.
            if (event.key === 'Escape' && !event.nativeEvent.isComposing) {
              if (draft.length > 0) {
                event.preventDefault();
                setDraft('');
                setRefused(false);
                return;
              }
              if (onCancel) {
                event.preventDefault();
                onCancel();
                return;
              }
            }
            if (readOnly || event.key !== 'Enter') return;
            event.preventDefault();
            submit();
          }}
        />
        {draft.length > 0 ? (
          <button
            type="button"
            data-testid="review-reply-cancel"
            className="docx-review__text-button"
            onMouseDown={deps.guardMousedown}
            onClick={(event) => {
              event.stopPropagation();
              setDraft('');
              setRefused(false);
              onCancel?.();
            }}
          >
            {t('common.cancel')}
          </button>
        ) : null}
        <button
          type="submit"
          data-testid="review-reply-submit"
          className="docx-review__send"
          aria-label={t('review.reply')}
          disabled={readOnly || draft.trim().length === 0}
          title={readOnly ? t('editingMode.viewingHint') : t('review.reply')}
        >
          {icon(SEND_ICON)}
        </button>
        {refused ? (
          <span className="docx-review__refused" role="alert" data-testid="review-reply-refused">
            {t('review.replyRefused')}
          </span>
        ) : null}
      </form>
    );
  }

  /** The reply box on the active card. @public */
  function ReviewReply({ className, hidden, children }: ReviewPartProps) {
    const { review } = deps.useRail();
    const entry = deps.useItem();
    // Held here, not in the line: the draft survives the card closing and reopening.
    const state = useReplyDraft(entry);
    if (hidden || !entry || !entry.isActive || (entry.kind === 'comment' && entry.resolved)) {
      return null;
    }
    if (children) return <>{children}</>;
    return (
      <ReplyLine state={state} className={className} onCancel={() => review.setActive(null)} />
    );
  }
  ReviewReply.docxReviewPart = 'Reply' as const;

  /**
   * The change balloon's reply line. Open whenever the balloon is; not a rail part.
   *
   * `orphaned` marks a change that was resolved, for example by another participant, while
   * the reader was typing. The line keeps the text, posts nothing, and says why, so a draft
   * is never dropped without notice. `onDraft` reports whether the line holds text.
   */
  function ReviewBalloonReply({
    entry,
    orphaned = false,
    onDraft,
  }: {
    readonly entry: ReviewItemView;
    readonly orphaned?: boolean;
    readonly onDraft?: (hasText: boolean) => void;
  }) {
    const t = deps.useLabel();
    const state = useReplyDraft(orphaned ? null : entry);
    const hasText = state.draft.trim().length > 0;
    useEffect(() => onDraft?.(hasText), [hasText, onDraft]);
    return (
      <>
        <ReplyLine state={state} />
        {orphaned ? (
          <span className="docx-review__refused" role="alert" data-testid="review-reply-orphaned">
            {t('review.replyTargetResolved')}
          </span>
        ) : null}
      </>
    );
  }

  return { ReviewDraft, ReviewReply, ReviewBalloonReply };
}

// packages/pro/src/vue/review-compose-boxes.tsx
/*
Copyright (c) 2026 EigenPal, Inc. All rights reserved.
Licensed under the EigenPal Pro Evaluation License 1.0 — see packages/pro/LICENSE.md.
Production use requires a commercial agreement: licensing@eigenpal.com
*/

import {
  defineComponent,
  getCurrentInstance,
  h,
  onBeforeUnmount,
  onMounted,
  ref,
  watch,
  type ComputedRef,
  type PropType,
} from 'vue';
import { useDocxEditor } from '@docx-editor.dev/vue';
import type { TranslationKey } from '@docx-editor.dev/i18n';
import type { ReviewRailValue } from './review-context.ts';
import type { ReviewItemView } from './useReview.ts';
import { useReviewStableId } from './stable-id.ts';
import { useEditorRenderRevision } from './useEditorRenderRevision.ts';
import {
  COMPACT_CARD_WIDTH,
  COMPOSE_KEY,
  guardMousedown,
  initialsOf,
  markPart,
} from './review-shared.ts';
import { authorCardStyle } from './review-author-styles.ts';
import { SEND_ICON, icon } from './review-icons.tsx';

interface ComposePartDeps {
  readonly useRail: () => ComputedRef<ReviewRailValue>;
  readonly useItem: () => ComputedRef<ReviewItemView | null>;
  readonly useLabel: () => (key: TranslationKey) => string;
}

/** Build the draft and reply compose boxes against the rail's private contexts. */
export function createReviewComposeParts(deps: ComposePartDeps) {
  const ReviewDraft = markPart(
    defineComponent({
      name: 'ReviewDraft',
      props: {
        top: { type: Number, default: 0 },
        left: { type: Number as PropType<number | null>, default: null },
        className: String,
        hidden: Boolean,
      },
      setup(props) {
        const rail = deps.useRail();
        const t = deps.useLabel();
        const text = ref('');
        const refused = ref(false);
        const fieldId = useReviewStableId('draft');
        let measuredBy: ReviewRailValue['measure'] | null = null;

        onMounted(() => {
          const root = getCurrentInstance()?.proxy?.$el;
          if (root instanceof HTMLElement) {
            measuredBy = rail.value.measure;
            measuredBy(root, COMPOSE_KEY);
          }
          if (rail.value.readOnly) return;
          const input =
            root instanceof HTMLElement
              ? root.querySelector('[data-testid="review-draft-input"]')
              : null;
          (input as HTMLInputElement | null)?.focus({ preventScroll: true });
        });
        onBeforeUnmount(() => {
          measuredBy?.(null, COMPOSE_KEY);
        });

        const submit = () => {
          const { review, endDraft, readOnly } = rail.value;
          if (readOnly || text.value.trim().length === 0) return;
          const landed = review.comment(text.value.trim());
          refused.value = !landed;
          if (landed) {
            text.value = '';
            endDraft();
          }
        };

        return () => {
          if (props.hidden) return null;
          const { readOnly, draftAuthor, draftAuthorInfo, draftAuthorSlot } = rail.value;
          return h(
            'div',
            {
              class: `docx-review__slot${props.left === null ? '' : ' docx-review__slot--compact'}${props.className ? ` ${props.className}` : ''}`,
              style: {
                position: 'absolute',
                top: `${props.top}px`,
                ...(props.left === null
                  ? {}
                  : { left: `${props.left}px`, width: `${COMPACT_CARD_WIDTH}px` }),
              },
            },
            [
              h(
                'div',
                {
                  class: 'docx-review__card',
                  'data-testid': 'review-draft',
                  'data-draft': '',
                  ...(draftAuthor
                    ? {
                        'data-review-author': draftAuthor,
                        'data-review-author-slot': draftAuthorSlot,
                      }
                    : {}),
                  style: authorCardStyle(
                    draftAuthor ?? undefined,
                    draftAuthorInfo,
                    draftAuthorSlot
                  ),
                },
                [
                  h(
                    'form',
                    {
                      class: 'docx-review__reply-box',
                      onSubmit: (event: Event) => {
                        event.preventDefault();
                        submit();
                      },
                    },
                    [
                      h(
                        'label',
                        { class: 'docx-editor-sr-only', for: fieldId },
                        t('comments.addComment')
                      ),
                      h('input', {
                        id: fieldId,
                        'data-testid': 'review-draft-input',
                        class: 'docx-review__input',
                        value: text.value,
                        placeholder: t('comments.addComment'),
                        readonly: readOnly,
                        ...(refused.value ? { 'aria-invalid': true } : {}),
                        onInput: (event: Event) => {
                          if (readOnly) return;
                          refused.value = false;
                          text.value = (event.target as HTMLInputElement).value;
                        },
                        onKeydown: (event: KeyboardEvent) => {
                          if (event.key === 'Escape') {
                            event.preventDefault();
                            rail.value.endDraft();
                            return;
                          }
                          if (readOnly || event.key !== 'Enter') return;
                          event.preventDefault();
                          submit();
                        },
                      }),
                      h('div', { class: 'docx-review__reply-actions' }, [
                        h(
                          'button',
                          {
                            type: 'button',
                            'data-testid': 'review-draft-cancel',
                            class: 'docx-review__text-button',
                            onMousedown: guardMousedown,
                            onClick: () => rail.value.endDraft(),
                          },
                          t('common.cancel')
                        ),
                        h(
                          'button',
                          {
                            type: 'submit',
                            'data-testid': 'review-draft-submit',
                            class: 'docx-review__submit',
                            disabled: readOnly || text.value.trim().length === 0,
                            title: readOnly ? t('editingMode.viewingHint') : undefined,
                          },
                          t('common.comment')
                        ),
                      ]),
                      refused.value
                        ? h(
                            'span',
                            { class: 'docx-review__refused', role: 'alert' },
                            t('review.commentRefused')
                          )
                        : null,
                    ]
                  ),
                ]
              ),
            ]
          );
        };
      },
    }),
    'Draft'
  );

  /** Draft state and submission for one reply line, held by whichever part owns it. */
  function useReplyDraft(entryRef: () => ReviewItemView | null) {
    const rail = deps.useRail();
    const editorRef = useDocxEditor();
    const draft = ref('');
    const refused = ref(false);
    const submit = (root: ParentNode | null) => {
      const entry = entryRef();
      const { review, readOnly, byId } = rail.value;
      const input = root?.querySelector<HTMLInputElement>('[data-testid="review-reply-input"]');
      const text = (input?.value ?? draft.value).trim();
      const live = entry ? (byId.get(entry.id) ?? entry) : null;
      if (!live || readOnly || text.length === 0) return;
      const landed =
        editorRef.value?.replyToReviewItem(live.key, text).ok ?? review.reply(live, text);
      refused.value = !landed;
      if (landed) {
        draft.value = '';
        if (input) input.value = '';
      }
    };
    return { draft, refused, submit };
  }

  /**
   * The compact reply line the open card and the change balloon share: the configured
   * author's avatar, a borderless field, Cancel only while there is text, and a round send
   * button. Enter sends too.
   */
  function renderReplyLine(
    state: ReturnType<typeof useReplyDraft>,
    rail: ComputedRef<ReviewRailValue>,
    t: (key: TranslationKey) => string,
    fieldId: string,
    options: { readonly className?: string; readonly onCancel?: () => void } = {}
  ) {
    const { readOnly, draftAuthor, draftAuthorInfo, draftAuthorSlot } = rail.value;
    const { draft, refused, submit } = state;
    const avatarUrl = draftAuthorInfo?.style?.avatarUrl;
    const lineOf = (event: Event) =>
      (event.currentTarget as HTMLElement).closest('.docx-review__reply-box');
    return (
      <div
        class={`docx-review__reply-box${options.className ? ` ${options.className}` : ''}`}
        data-reply-line=""
      >
        <label class="docx-editor-sr-only" for={fieldId}>
          {t('comments.replyPlaceholder')}
        </label>
        {draftAuthor ? (
          <span
            class="docx-review__avatar docx-review__reply-avatar"
            data-testid="review-reply-avatar"
            aria-hidden="true"
            style={authorCardStyle(draftAuthor, draftAuthorInfo, draftAuthorSlot)}
          >
            {avatarUrl ? (
              <img
                class="docx-review__avatar-img"
                src={avatarUrl}
                alt=""
                loading="lazy"
                decoding="async"
                referrerpolicy="no-referrer"
              />
            ) : (
              initialsOf(draftAuthor)
            )}
          </span>
        ) : null}
        <input
          id={fieldId}
          data-testid="review-reply-input"
          class="docx-review__input"
          placeholder={t('comments.replyPlaceholder')}
          readonly={readOnly}
          {...(refused.value ? { 'aria-invalid': true, 'data-refused': '' } : {})}
          onInput={(event) => {
            if (readOnly) return;
            refused.value = false;
            draft.value = (event.target as HTMLInputElement).value;
          }}
          onClick={(event) => event.stopPropagation()}
          onKeydown={(event) => {
            // The first Escape clears a draft, so a stray key never loses it with the card or
            // balloon. On an empty line it closes the card; in a balloon it bubbles to the
            // balloon, which closes itself.
            if (event.key === 'Escape' && !event.isComposing) {
              if (draft.value.length > 0) {
                event.preventDefault();
                (event.currentTarget as HTMLInputElement).value = '';
                draft.value = '';
                refused.value = false;
                return;
              }
              if (options.onCancel) {
                event.preventDefault();
                options.onCancel();
                return;
              }
            }
            if (readOnly || event.key !== 'Enter') return;
            event.preventDefault();
            submit(lineOf(event));
          }}
        />
        {draft.value.length > 0 ? (
          <button
            type="button"
            data-testid="review-reply-cancel"
            class="docx-review__text-button"
            onMousedown={guardMousedown}
            onClick={(event) => {
              event.stopPropagation();
              const input = lineOf(event)?.querySelector<HTMLInputElement>(
                '[data-testid="review-reply-input"]'
              );
              if (input) input.value = '';
              draft.value = '';
              refused.value = false;
              options.onCancel?.();
            }}
          >
            {t('common.cancel')}
          </button>
        ) : null}
        <button
          type="button"
          data-testid="review-reply-submit"
          class="docx-review__send"
          aria-label={t('review.reply')}
          disabled={readOnly || draft.value.trim().length === 0}
          title={readOnly ? t('editingMode.viewingHint') : t('review.reply')}
          onClick={(event) => {
            event.preventDefault();
            event.stopPropagation();
            submit(lineOf(event));
          }}
        >
          {icon(SEND_ICON)}
        </button>
        {refused.value ? (
          <span class="docx-review__refused" role="alert" data-testid="review-reply-refused">
            {t('review.replyRefused')}
          </span>
        ) : null}
      </div>
    );
  }

  const ReviewReply = markPart(
    defineComponent({
      name: 'ReviewReply',
      props: {
        className: String,
        hidden: Boolean,
      },
      setup(props, { slots }) {
        const rail = deps.useRail();
        const entryRef = deps.useItem();
        const t = deps.useLabel();
        const fieldId = useReviewStableId('reply');
        const editorRevision = useEditorRenderRevision();
        // Held here, not in the line: the draft survives the card closing and reopening.
        const state = useReplyDraft(() => entryRef.value);

        return () => {
          void editorRevision.value;
          const entry = entryRef.value;
          if (
            props.hidden ||
            !entry ||
            !entry.isActive ||
            (entry.kind === 'comment' && entry.resolved)
          ) {
            return null;
          }
          const custom = slots.default?.();
          if (custom?.length) return custom;
          return renderReplyLine(state, rail, t, fieldId, {
            ...(props.className ? { className: props.className } : {}),
            onCancel: () => rail.value.review.setActive(null),
          });
        };
      },
    }),
    'Reply'
  );

  /**
   * The change balloon's reply line. Open whenever the balloon is; not a rail part.
   *
   * `orphaned` marks a change that was resolved, for example by another participant, while
   * the reader was typing. The line keeps the text, posts nothing, and says why, so a draft
   * is never dropped without notice. `onDraft` reports whether the line holds text.
   */
  const ReviewBalloonReply = defineComponent({
    name: 'ReviewBalloonReply',
    props: {
      entry: { type: Object as PropType<ReviewItemView>, required: true },
      orphaned: { type: Boolean, default: false },
      onDraft: { type: Function as PropType<(hasText: boolean) => void>, default: undefined },
    },
    setup(props) {
      const rail = deps.useRail();
      const t = deps.useLabel();
      const fieldId = useReviewStableId('balloon-reply');
      const state = useReplyDraft(() => (props.orphaned ? null : props.entry));
      watch(
        () => state.draft.value.trim().length > 0,
        (hasText) => props.onDraft?.(hasText),
        { immediate: true }
      );
      return () => [
        renderReplyLine(state, rail, t, fieldId),
        props.orphaned
          ? h(
              'span',
              {
                class: 'docx-review__refused',
                role: 'alert',
                'data-testid': 'review-reply-orphaned',
              },
              t('review.replyTargetResolved')
            )
          : null,
      ];
    },
  });

  return { ReviewDraft, ReviewReply, ReviewBalloonReply };
}
