// examples/shared/DocxAdapterHarness.tsx
// Browser harness for the PRODUCTION React adapter (comprehensive 4.4/4.8). Unlike DocxEditable
// (which drives the engine mount directly), this renders the real @docx-editor.dev/react DocxEditor
// with DOCX bytes and exposes the stable engine-neutral EditorDriver on window, so a browser test
// exercises the actual published package entry: props -> createEditor -> layout -> paint -> save.

import React, { useEffect, useState } from 'react';
import {
  DocxEditor,
  DocxEditorMenuBar,
  DocxEditorShell,
  DocxEditorSidebar,
  DocxEditorTitleBar,
  DocxEditorToolbar,
  HorizontalRuler,
  PageIndicator,
  VerticalRuler,
} from '@docx-editor.dev/react';
import { createEditorDriver, type EditorDriver } from '@docx-editor.dev/engine-editor';
import en from '../../packages/i18n/en.json';

/**
 * Resolve an i18n key against `packages/i18n/en.json`, imported directly.
 *
 * The HOST owns localization, not the adapter: the published adapters hold only
 * i18n keys so they ship no English of their own (CLAUDE.md forbids hardcoded
 * user-facing English in components, and `en.json` is the single source of truth).
 * The demo is the host here, so it does the resolving.
 */
function translate(key: string): string {
  const value = key.split('.').reduce<unknown>((node, part) => {
    return node && typeof node === 'object' ? (node as Record<string, unknown>)[part] : undefined;
  }, en as Record<string, unknown>);
  // Surfacing the key is deliberate when a string is missing: a silent fallback to
  // the key's last segment reads like a real label and hides the gap.
  return typeof value === 'string' ? value : key;
}
import type { Editor } from '@docx-editor.dev/react';

declare global {
  interface Window {
    __docxAdapterDriver?: EditorDriver;
    /**
     * The public `Editor` facade, exposed so browser gates can dispatch a real
     * interaction and assert the TYPED OUTCOME, not just the visible result. A
     * silent no-op and a typed rejection look identical on screen; the
     * one-surface specs have to tell them apart.
     */
    __docxAdapterEditor?: Editor;
    __docxAdapterHarness?: {
      setZoom(zoom: number): void;
      getZoom(): number;
    };
  }
}

export function DocxAdapterHarness({
  fixtureUrl,
  initialZoom = 1,
}: {
  readonly fixtureUrl: string;
  readonly initialZoom?: number;
}): React.ReactElement {
  const [bytes, setBytes] = useState<Uint8Array | null>(null);
  const [status, setStatus] = useState('Loading…');
  const [zoom, setZoom] = useState(initialZoom);
  // The document title is SHELL state: the engine owns no title contract (M4.0).
  const [title, setTitle] = useState('Untitled document');
  const [editor, setEditor] = useState<Editor | null>(null);

  useEffect(() => {
    let cancelled = false;
    void (async () => {
      try {
        const b = new Uint8Array(await (await fetch(fixtureUrl)).arrayBuffer());
        if (!cancelled) setBytes(b);
      } catch (e) {
        if (!cancelled) setStatus(`Could not fetch fixture (${(e as Error).message}).`);
      }
    })();
    return () => {
      cancelled = true;
      delete window.__docxAdapterDriver;
      delete window.__docxAdapterEditor;
      delete window.__docxAdapterHarness;
    };
  }, [fixtureUrl]);

  useEffect(() => {
    window.__docxAdapterHarness = {
      setZoom: (next) => setZoom(next),
      getZoom: () => zoom,
    };
  }, [zoom]);

  const onReady = (editor: Editor): void => {
    const driver = createEditorDriver(editor);
    window.__docxAdapterDriver = driver;
    window.__docxAdapterEditor = editor;
    setEditor(editor);
    setStatus(driver.editable() ? 'Editable (paragraphs)' : 'Read-only (contains tables/SDTs)');
  };

  const onSave = (): void => {
    void editor?.save();
  };

  return (
    <div style={{ display: 'flex', flexDirection: 'column', height: '100%', minHeight: 0 }}>
      <div style={{ padding: '8px 12px', font: '13px system-ui, sans-serif', color: '#333', borderBottom: '1px solid #e0e0e0' }}>
        <span data-testid="adapter-status">{status}</span>
      </div>
      <DocxEditorShell
        titleBar={
          <>
            <DocxEditorTitleBar title={title} onTitleChange={setTitle} />
            <DocxEditorMenuBar t={translate} />
          </>
        }
        sidebar={<DocxEditorSidebar editor={editor} open t={translate} />}
        toolbar={<DocxEditorToolbar editor={editor} t={translate} onSave={onSave} />}
        horizontalRuler={<HorizontalRuler editor={editor} zoom={zoom} />}
        verticalRuler={<VerticalRuler editor={editor} zoom={zoom} />}
        pageIndicator={<PageIndicator editor={editor} />}
      >
        {bytes && <DocxEditor document={bytes} zoom={zoom} onReady={onReady} />}
      </DocxEditorShell>
    </div>
  );
}

// examples/shared/DocxAdapterHarness.vue
<!--
  Browser harness for the PRODUCTION Vue adapter (comprehensive 4.4/4.8), behavior-identical to its
  React counterpart DocxAdapterHarness.tsx: mount the real @docx-editor.dev/vue DocxEditor with DOCX
  bytes and expose the stable engine-neutral EditorDriver on window, so a browser test exercises the
  actual published package entry (props -> createEditor -> layout -> paint -> save).
-->
<script setup lang="ts">
import { onBeforeUnmount, onMounted, ref, watch } from 'vue';
import {
  DocxEditor,
  DocxEditorShell,
  DocxEditorTitleBar,
  DocxEditorToolbar,
  HorizontalRuler,
  VerticalRuler,
  PageIndicator,
} from '@docx-editor.dev/vue';
import { createEditorDriver, type EditorDriver } from '@docx-editor.dev/engine-editor';
import en from '../../packages/i18n/en.json';

/**
 * Resolve an i18n key against `packages/i18n/en.json`, imported directly.
 *
 * The HOST owns localization: the published adapters hold only i18n keys so they
 * ship no English of their own (CLAUDE.md forbids hardcoded user-facing English in
 * components, and en.json is the single source of truth). Identical to the React
 * harness's resolver, so the two demos localize the same way.
 */
function translate(key: string): string {
  const value = key.split('.').reduce<unknown>((node, part) => {
    return node && typeof node === 'object' ? (node as Record<string, unknown>)[part] : undefined;
  }, en as Record<string, unknown>);
  // Surfacing the key is deliberate when a string is missing: falling back to the
  // last segment reads like a real label and hides the gap.
  return typeof value === 'string' ? value : key;
}
import type { Editor } from '@docx-editor.dev/vue';

const props = defineProps<{ fixtureUrl: string; initialZoom?: number }>();

const bytes = ref<Uint8Array | null>(null);
const status = ref('Loading…');
const zoom = ref(props.initialZoom ?? 1);
// The document title is SHELL state: the engine owns no title contract (M4.0).
const title = ref('Untitled document');
const editorInstance = ref<Editor | null>(null);

async function load(url: string): Promise<void> {
  try {
    bytes.value = new Uint8Array(await (await fetch(url)).arrayBuffer());
  } catch (e) {
    status.value = `Could not fetch fixture (${(e as Error).message}).`;
  }
}

function syncHarness(): void {
  (window as unknown as { __docxAdapterHarness?: { setZoom(z: number): void; getZoom(): number } }).__docxAdapterHarness = {
    setZoom: (next) => {
      zoom.value = next;
    },
    getZoom: () => zoom.value,
  };
}

function onReady(editor: Editor): void {
  const driver = createEditorDriver(editor);
  (window as unknown as { __docxAdapterDriver?: EditorDriver }).__docxAdapterDriver = driver;
  // The public Editor facade, so browser gates can assert TYPED OUTCOMES and not
  // just visible results — matching the React harness.
  (window as unknown as { __docxAdapterEditor?: Editor }).__docxAdapterEditor = editor;
  editorInstance.value = editor;
  status.value = driver.editable() ? 'Editable (paragraphs)' : 'Read-only (contains tables/SDTs)';
}

function onSave(): void {
  void editorInstance.value?.save();
}

onMounted(() => {
  syncHarness();
  void load(props.fixtureUrl);
});
watch(() => props.fixtureUrl, (url) => void load(url));
watch(zoom, syncHarness);
onBeforeUnmount(() => {
  delete (window as unknown as { __docxAdapterDriver?: EditorDriver }).__docxAdapterDriver;
  delete (window as unknown as { __docxAdapterEditor?: Editor }).__docxAdapterEditor;
  delete (window as unknown as { __docxAdapterHarness?: unknown }).__docxAdapterHarness;
});
</script>

<template>
  <div style="display: flex; flex-direction: column; height: 100%; min-height: 0">
    <div style="padding: 8px 12px; font: 13px system-ui, sans-serif; color: #333; border-bottom: 1px solid #e0e0e0">
      <span data-testid="adapter-status">{{ status }}</span>
    </div>
    <DocxEditorShell>
      <template #titleBar><DocxEditorTitleBar v-model:title="title" /></template>
      <template #toolbar><DocxEditorToolbar :editor="editorInstance" :t="translate" :on-save="onSave" /></template>
      <template #verticalRuler><VerticalRuler :editor="editorInstance" :zoom="zoom" /></template>
      <template #horizontalRuler><HorizontalRuler :editor="editorInstance" :zoom="zoom" /></template>
      <template #pageIndicator><PageIndicator :editor="editorInstance" /></template>
      <DocxEditor v-if="bytes" :document="bytes" :zoom="zoom" @ready="onReady" />
    </DocxEditorShell>
  </div>
</template>
