// packages/vue/src/components/HorizontalRuler.vue
<template>
  <div class="hruler" :style="{ height: `${RULER_H}px` }">
    <div class="hruler__track" ref="trackRef" :style="trackStyle">
      <!-- Left margin zone -->
      <div class="hruler__margin" :style="{ left: 0, width: `${leftMarginPx}px` }" />
      <!-- Right margin zone -->
      <div class="hruler__margin" :style="{ right: 0, width: `${rightMarginPx}px` }" />

      <!-- Tick marks -->
      <svg class="hruler__ticks" :viewBox="`0 0 ${pageWidthPx} ${RULER_H}`" preserveAspectRatio="none">
        <template v-for="tick in ticks" :key="tick.x">
          <line :x1="tick.x" :y1="tick.major ? 2 : 6" :x2="tick.x" :y2="RULER_H - 2" stroke="#9ca3af" :stroke-width="tick.major ? 0.8 : 0.5" />
          <text v-if="tick.label" :x="tick.x + 3" :y="10" font-size="8" fill="#9ca3af">{{ tick.label }}</text>
        </template>
      </svg>

      <!-- Left indent handle (▲) -->
      <div
        v-if="editable"
        class="hruler__handle hruler__handle--left-indent"
        :style="{ left: `${leftMarginPx + leftIndentPx}px` }"
        title="Left indent"
        @mousedown.prevent="startDrag('leftIndent', $event)"
      >&#x25B2;</div>

      <!-- First-line indent handle (▼) -->
      <div
        v-if="editable && showFirstLineIndent"
        class="hruler__handle hruler__handle--first-line"
        :style="{ left: `${leftMarginPx + firstLineIndentPx}px` }"
        title="First-line indent"
        @mousedown.prevent="startDrag('firstLineIndent', $event)"
      >&#x25BC;</div>

      <!-- Right indent handle (▼) -->
      <div
        v-if="editable"
        class="hruler__handle hruler__handle--right-indent"
        :style="{ right: `${rightMarginPx + rightIndentPx}px` }"
        title="Right indent"
        @mousedown.prevent="startDrag('rightIndent', $event)"
      >&#x25BC;</div>

      <!-- Tab stops -->
      <div
        v-for="(tab, i) in tabStopPositions"
        :key="i"
        class="hruler__tab"
        :style="{ left: `${tab.px}px` }"
        :title="`Tab stop: ${tab.label}`"
        @dblclick.prevent="$emit('tab-stop-remove', tab.twips)"
      >&#x2514;</div>

      <!-- Drag tooltip -->
      <div v-if="dragging" class="hruler__tooltip" :style="{ left: `${tooltipX}px` }">
        {{ tooltipText }}
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted, onBeforeUnmount } from 'vue';
import type { SectionProperties, TabStop } from '@eigenpal/docx-core/types/document';

const props = withDefaults(
  defineProps<{
    sectionProps?: SectionProperties | null;
    zoom?: number;
    editable?: boolean;
    showFirstLineIndent?: boolean;
    firstLineIndent?: number;
    indentLeft?: number;
    indentRight?: number;
    unit?: 'inch' | 'cm';
    tabStops?: TabStop[] | null;
  }>(),
  {
    zoom: 1,
    editable: true,
    showFirstLineIndent: true,
    firstLineIndent: 0,
    indentLeft: 0,
    indentRight: 0,
    unit: 'inch',
  }
);

const emit = defineEmits<{
  (e: 'left-margin-change', twips: number): void;
  (e: 'right-margin-change', twips: number): void;
  (e: 'first-line-indent-change', twips: number): void;
  (e: 'indent-left-change', twips: number): void;
  (e: 'indent-right-change', twips: number): void;
  (e: 'tab-stop-remove', twips: number): void;
}>();

const RULER_H = 22;
const TWIPS_PER_INCH = 1440;
const TWIPS_PER_CM = 567;
const DEFAULT_PAGE_WIDTH = 12240;
const DEFAULT_MARGIN = 1440;

const trackRef = ref<HTMLElement | null>(null);
const dragging = ref(false);
const dragType = ref<string | null>(null);
const dragStartX = ref(0);
const dragStartValue = ref(0);
const tooltipX = ref(0);
const tooltipText = ref('');

function tw2px(twips: number): number {
  return Math.round((twips / TWIPS_PER_INCH) * 96 * props.zoom);
}
function px2tw(px: number): number {
  return Math.round((px / (96 * props.zoom)) * TWIPS_PER_INCH);
}

const pageWidthTw = computed(() => props.sectionProps?.pageWidth ?? DEFAULT_PAGE_WIDTH);
const leftMarginTw = computed(() => props.sectionProps?.marginLeft ?? DEFAULT_MARGIN);
const rightMarginTw = computed(() => props.sectionProps?.marginRight ?? DEFAULT_MARGIN);

const pageWidthPx = computed(() => tw2px(pageWidthTw.value));
const leftMarginPx = computed(() => tw2px(leftMarginTw.value));
const rightMarginPx = computed(() => tw2px(rightMarginTw.value));
const leftIndentPx = computed(() => tw2px(props.indentLeft ?? 0));
const rightIndentPx = computed(() => tw2px(props.indentRight ?? 0));
const firstLineIndentPx = computed(() => tw2px(props.firstLineIndent ?? 0));

const trackStyle = computed(() => ({
  width: `${pageWidthPx.value}px`,
  height: `${RULER_H}px`,
}));

const ticks = computed(() => {
  const result: { x: number; major: boolean; label?: string }[] = [];
  const perUnit = props.unit === 'cm' ? TWIPS_PER_CM : TWIPS_PER_INCH;
  const steps = Math.ceil(pageWidthTw.value / perUnit) + 1;
  for (let i = 0; i <= steps; i++) {
    const tw = i * perUnit;
    if (tw > pageWidthTw.value) break;
    result.push({ x: tw2px(tw), major: true, label: i > 0 ? String(i) : undefined });
    // Half-unit tick
    const halfTw = tw + perUnit / 2;
    if (halfTw < pageWidthTw.value) {
      result.push({ x: tw2px(halfTw), major: false });
    }
  }
  return result;
});

const tabStopPositions = computed(() => {
  if (!props.tabStops?.length) return [];
  return props.tabStops.map(ts => ({
    px: tw2px((ts as any).position ?? ts.pos ?? 0) + leftMarginPx.value,
    twips: (ts as any).position ?? ts.pos ?? 0,
    label: formatValue((ts as any).position ?? ts.pos ?? 0),
  }));
});

function formatValue(twips: number): string {
  if (props.unit === 'cm') return (twips / TWIPS_PER_CM).toFixed(1) + ' cm';
  return (twips / TWIPS_PER_INCH).toFixed(2) + '"';
}

function startDrag(type: string, event: MouseEvent) {
  if (!props.editable) return;
  dragging.value = true;
  dragType.value = type;
  dragStartX.value = event.clientX;

  if (type === 'leftIndent') dragStartValue.value = props.indentLeft ?? 0;
  else if (type === 'rightIndent') dragStartValue.value = props.indentRight ?? 0;
  else if (type === 'firstLineIndent') dragStartValue.value = props.firstLineIndent ?? 0;

  tooltipX.value = event.clientX - (trackRef.value?.getBoundingClientRect().left ?? 0);
  tooltipText.value = formatValue(dragStartValue.value);
}

function handleMouseMove(event: MouseEvent) {
  if (!dragging.value || !dragType.value) return;
  const dx = event.clientX - dragStartX.value;
  const dTwips = px2tw(dx);
  const newValue = Math.max(0, dragStartValue.value + dTwips);

  tooltipX.value = event.clientX - (trackRef.value?.getBoundingClientRect().left ?? 0);
  tooltipText.value = formatValue(newValue);
}

function handleMouseUp(event: MouseEvent) {
  if (!dragging.value || !dragType.value) return;
  const dx = event.clientX - dragStartX.value;
  const dTwips = px2tw(dx);
  const newValue = Math.max(0, dragStartValue.value + dTwips);

  switch (dragType.value) {
    case 'leftIndent': emit('indent-left-change', newValue); break;
    case 'rightIndent': emit('indent-right-change', newValue); break;
    case 'firstLineIndent': emit('first-line-indent-change', newValue); break;
  }

  dragging.value = false;
  dragType.value = null;
}

onMounted(() => {
  window.addEventListener('mousemove', handleMouseMove);
  window.addEventListener('mouseup', handleMouseUp);
});
onBeforeUnmount(() => {
  window.removeEventListener('mousemove', handleMouseMove);
  window.removeEventListener('mouseup', handleMouseUp);
});
</script>

<style scoped>
.hruler {
  display: flex;
  justify-content: center;
  background: #f9fafb;
  border-bottom: 1px solid #e5e7eb;
  user-select: none;
  overflow: hidden;
}
.hruler__track {
  position: relative;
  background: #fff;
  border-left: 1px solid #d1d5db;
  border-right: 1px solid #d1d5db;
}
.hruler__margin {
  position: absolute;
  top: 0;
  bottom: 0;
  background: rgba(0,0,0,0.03);
}
.hruler__ticks {
  position: absolute;
  inset: 0;
  width: 100%;
  height: 100%;
  pointer-events: none;
}
.hruler__handle {
  position: absolute;
  cursor: col-resize;
  font-size: 8px;
  color: #4285f4;
  width: 10px;
  text-align: center;
  z-index: 2;
}
.hruler__handle:hover { color: #2a56c6; }
.hruler__handle--left-indent { bottom: 0; transform: translateX(-5px); }
.hruler__handle--first-line { top: 0; transform: translateX(-5px); }
.hruler__handle--right-indent { top: 0; }
.hruler__tab {
  position: absolute;
  bottom: 2px;
  font-size: 8px;
  color: #6b7280;
  cursor: pointer;
  transform: translateX(-4px);
  z-index: 1;
}
.hruler__tab:hover { color: #374151; }
.hruler__tooltip {
  position: absolute;
  top: -22px;
  transform: translateX(-50%);
  background: #1f2937;
  color: #fff;
  padding: 2px 6px;
  border-radius: 3px;
  font-size: 10px;
  white-space: nowrap;
  z-index: 10;
  pointer-events: none;
}
</style>

// packages/react/src/components/ui/HorizontalRuler.tsx
/**
 * HorizontalRuler Component — Google Docs style
 *
 * 3 handles only:
 * - Left side: first-line indent (▼ down at top) + left indent (▲ up at bottom)
 * - Right side: right indent (▼ down at top)
 *
 * Margins shown as gray zones on the ruler edges.
 * Drag the boundary between gray/white to adjust page margins.
 * Drag tooltip shows value during any drag.
 */

import React, { useState, useRef, useCallback, useEffect } from 'react';
import type { CSSProperties } from 'react';
import type { SectionProperties, TabMark } from '@eigenpal/docx-core/types/document';
import { twipsToPixels, pixelsToTwips, formatPx } from '@eigenpal/docx-core/utils/units';
import { useTranslation } from '../../i18n';

// ============================================================================
// TYPES
// ============================================================================

export interface HorizontalRulerProps {
  sectionProps?: SectionProperties | null;
  zoom?: number;
  editable?: boolean;
  onLeftMarginChange?: (marginTwips: number) => void;
  onRightMarginChange?: (marginTwips: number) => void;
  onFirstLineIndentChange?: (indentTwips: number) => void;
  showFirstLineIndent?: boolean;
  firstLineIndent?: number;
  hangingIndent?: boolean;
  indentLeft?: number;
  indentRight?: number;
  onIndentLeftChange?: (indentTwips: number) => void;
  onIndentRightChange?: (indentTwips: number) => void;
  unit?: 'inch' | 'cm';
  className?: string;
  style?: CSSProperties;
  tabMarks?: TabMark[] | null;
  onTabMarkRemove?: (positionTwips: number) => void;
}

type MarkerType = 'leftMargin' | 'rightMargin' | 'firstLineIndent' | 'leftIndent' | 'rightIndent';

// ============================================================================
// CONSTANTS
// ============================================================================

const DEFAULT_PAGE_WIDTH_TWIPS = 12240;
const DEFAULT_MARGIN_TWIPS = 1440;
const TWIPS_PER_INCH = 1440;
const TWIPS_PER_CM = 567;

const RULER_HEIGHT = 22;
const RULER_TEXT_COLOR = 'var(--doc-text-muted)';
const RULER_TICK_COLOR = 'var(--doc-text-subtle)';
const MARGIN_ZONE_COLOR = 'rgba(0, 0, 0, 0.02)';
const INDENT_COLOR = '#4285f4';
const INDENT_HOVER_COLOR = '#3367d6';
const INDENT_ACTIVE_COLOR = '#2a56c6';

const TRI_SIZE = 5; // triangle half-width in px

// ============================================================================
// HELPERS
// ============================================================================

function formatValueForTooltip(twips: number, unit: 'inch' | 'cm'): string {
  if (unit === 'inch') {
    return (twips / TWIPS_PER_INCH).toFixed(2) + '"';
  }
  return (twips / TWIPS_PER_CM).toFixed(1) + ' cm';
}

// ============================================================================
// MAIN COMPONENT
// ============================================================================

export function HorizontalRuler({
  sectionProps,
  zoom = 1,
  editable = false,
  onLeftMarginChange,
  onRightMarginChange,
  onFirstLineIndentChange,
  showFirstLineIndent = false,
  firstLineIndent = 0,
  hangingIndent = false,
  indentLeft = 0,
  indentRight = 0,
  onIndentLeftChange,
  onIndentRightChange,
  unit = 'inch',
  className = '',
  style,
  tabMarks,
  onTabMarkRemove,
}: HorizontalRulerProps): React.ReactElement {
  const { t } = useTranslation();
  const [dragging, setDragging] = useState<MarkerType | null>(null);
  const [hoveredMarker, setHoveredMarker] = useState<MarkerType | null>(null);
  const [dragValue, setDragValue] = useState<number | null>(null);
  const [dragPositionPx, setDragPositionPx] = useState<number | null>(null);
  const rulerRef = useRef<HTMLDivElement>(null);

  // Page dimensions
  const pageWidthTwips = sectionProps?.pageWidth ?? DEFAULT_PAGE_WIDTH_TWIPS;
  const leftMarginTwips = sectionProps?.marginLeft ?? DEFAULT_MARGIN_TWIPS;
  const rightMarginTwips = sectionProps?.marginRight ?? DEFAULT_MARGIN_TWIPS;
  const contentTwips = pageWidthTwips - leftMarginTwips - rightMarginTwips;

  // Pixel conversions
  const pageWidthPx = twipsToPixels(pageWidthTwips) * zoom;
  const leftMarginPx = twipsToPixels(leftMarginTwips) * zoom;
  const rightMarginPx = twipsToPixels(rightMarginTwips) * zoom;
  const indentLeftPx = twipsToPixels(indentLeft) * zoom;
  const indentRightPx = twipsToPixels(indentRight) * zoom;

  // First line indent: hanging goes left, normal goes right
  const effectiveFirstLineIndent = hangingIndent ? -firstLineIndent : firstLineIndent;
  const firstLineIndentPx = twipsToPixels(effectiveFirstLineIndent) * zoom;

  // Handle positions (in px from ruler left edge)
  const leftIndentPosPx = leftMarginPx + indentLeftPx;
  const rightIndentPosPx = pageWidthPx - rightMarginPx - indentRightPx;
  const firstLinePosPx = leftMarginPx + indentLeftPx + firstLineIndentPx;

  const handleDragStart = useCallback(
    (e: React.MouseEvent, marker: MarkerType) => {
      if (!editable) return;
      e.preventDefault();
      e.stopPropagation();
      setDragging(marker);
    },
    [editable]
  );

  const handleDrag = useCallback(
    (e: MouseEvent) => {
      if (!dragging || !rulerRef.current) return;

      const rect = rulerRef.current.getBoundingClientRect();
      const x = e.clientX - rect.left;
      setDragPositionPx(x);
      const positionTwips = pixelsToTwips(x / zoom);

      if (dragging === 'leftMargin') {
        const maxMargin = pageWidthTwips - rightMarginTwips - 720;
        const rounded = Math.round(Math.max(0, Math.min(positionTwips, maxMargin)));
        setDragValue(rounded);
        onLeftMarginChange?.(rounded);
      } else if (dragging === 'rightMargin') {
        const fromRight = pageWidthTwips - positionTwips;
        const maxMargin = pageWidthTwips - leftMarginTwips - 720;
        const rounded = Math.round(Math.max(0, Math.min(fromRight, maxMargin)));
        setDragValue(rounded);
        onRightMarginChange?.(rounded);
      } else if (dragging === 'firstLineIndent') {
        const base = leftMarginTwips + indentLeft;
        const indentFromBase = positionTwips - base;
        const maxIndent = contentTwips - indentLeft - indentRight - 720;
        const rounded = Math.round(Math.max(-indentLeft, Math.min(indentFromBase, maxIndent)));
        setDragValue(rounded);
        onFirstLineIndentChange?.(rounded);
      } else if (dragging === 'leftIndent') {
        const indentFromMargin = positionTwips - leftMarginTwips;
        const maxIndent = contentTwips - indentRight - 720;
        const rounded = Math.round(Math.max(0, Math.min(indentFromMargin, maxIndent)));
        setDragValue(rounded);
        onIndentLeftChange?.(rounded);
      } else if (dragging === 'rightIndent') {
        const rightEdge = pageWidthTwips - rightMarginTwips;
        const indentFromRight = rightEdge - positionTwips;
        const maxIndent = contentTwips - indentLeft - 720;
        const rounded = Math.round(Math.max(0, Math.min(indentFromRight, maxIndent)));
        setDragValue(rounded);
        onIndentRightChange?.(rounded);
      }
    },
    [
      dragging,
      zoom,
      pageWidthTwips,
      leftMarginTwips,
      rightMarginTwips,
      contentTwips,
      indentLeft,
      indentRight,
      onLeftMarginChange,
      onRightMarginChange,
      onFirstLineIndentChange,
      onIndentLeftChange,
      onIndentRightChange,
    ]
  );

  const handleDragEnd = useCallback(() => {
    setDragging(null);
    setDragValue(null);
    setDragPositionPx(null);
  }, []);

  useEffect(() => {
    if (dragging) {
      document.addEventListener('mousemove', handleDrag);
      document.addEventListener('mouseup', handleDragEnd);
      return () => {
        document.removeEventListener('mousemove', handleDrag);
        document.removeEventListener('mouseup', handleDragEnd);
      };
    }
  }, [dragging, handleDrag, handleDragEnd]);

  const ticks = generateTicks(pageWidthTwips, zoom, unit);

  return (
    <div
      ref={rulerRef}
      className={`docx-horizontal-ruler ${className}`}
      style={{
        position: 'relative',
        width: formatPx(pageWidthPx),
        height: RULER_HEIGHT,
        backgroundColor: 'transparent',
        overflow: 'visible',
        userSelect: 'none',
        cursor: dragging ? 'ew-resize' : 'default',
        ...style,
      }}
      role="slider"
      aria-label={t('ruler.horizontal')}
      aria-valuemin={0}
      aria-valuemax={pageWidthTwips}
    >
      {/* Gray margin zones — click & drag anywhere in the gray area to adjust margin */}
      <div
        style={{
          position: 'absolute',
          top: 0,
          left: 0,
          width: formatPx(leftMarginPx),
          height: RULER_HEIGHT,
          backgroundColor: MARGIN_ZONE_COLOR,
          borderRight: '1px solid rgba(0,0,0,0.06)',
          cursor: editable ? 'ew-resize' : 'default',
          zIndex: 1,
        }}
        onMouseDown={
          editable && onLeftMarginChange ? (e) => handleDragStart(e, 'leftMargin') : undefined
        }
      />
      <div
        style={{
          position: 'absolute',
          top: 0,
          right: 0,
          width: formatPx(rightMarginPx),
          height: RULER_HEIGHT,
          backgroundColor: MARGIN_ZONE_COLOR,
          borderLeft: '1px solid rgba(0,0,0,0.06)',
          cursor: editable ? 'ew-resize' : 'default',
          zIndex: 1,
        }}
        onMouseDown={
          editable && onRightMarginChange ? (e) => handleDragStart(e, 'rightMargin') : undefined
        }
      />

      {/* Tick marks */}
      <div style={{ position: 'absolute', inset: 0, pointerEvents: 'none' }}>
        {ticks.map((tick, i) => (
          <RulerTick key={i} tick={tick} />
        ))}
      </div>

      {/* === 3 INDENT HANDLES (Google Docs style) === */}

      {/* First-line indent — ▼ down triangle at top-left */}
      {showFirstLineIndent && (
        <IndentTriangle
          direction="down"
          positionPx={firstLinePosPx}
          editable={editable}
          isDragging={dragging === 'firstLineIndent'}
          isHovered={hoveredMarker === 'firstLineIndent'}
          onMouseEnter={() => setHoveredMarker('firstLineIndent')}
          onMouseLeave={() => setHoveredMarker(null)}
          onMouseDown={(e) => handleDragStart(e, 'firstLineIndent')}
          label={t('ruler.firstLineIndent')}
        />
      )}

      {/* Left indent — ▲ up triangle at bottom-left */}
      {editable && onIndentLeftChange && (
        <IndentTriangle
          direction="up"
          positionPx={leftIndentPosPx}
          editable={editable}
          isDragging={dragging === 'leftIndent'}
          isHovered={hoveredMarker === 'leftIndent'}
          onMouseEnter={() => setHoveredMarker('leftIndent')}
          onMouseLeave={() => setHoveredMarker(null)}
          onMouseDown={(e) => handleDragStart(e, 'leftIndent')}
          label={t('ruler.leftIndent')}
        />
      )}

      {/* Right indent — ▼ down triangle at top-right */}
      {editable && onIndentRightChange && (
        <IndentTriangle
          direction="down"
          positionPx={rightIndentPosPx}
          editable={editable}
          isDragging={dragging === 'rightIndent'}
          isHovered={hoveredMarker === 'rightIndent'}
          onMouseEnter={() => setHoveredMarker('rightIndent')}
          onMouseLeave={() => setHoveredMarker(null)}
          onMouseDown={(e) => handleDragStart(e, 'rightIndent')}
          label={t('ruler.rightIndent')}
        />
      )}

      {/* Tab stop markers (display only) */}
      {tabMarks?.map((tab) => (
        <TabMarker
          key={tab.position}
          tabMark={tab}
          positionPx={twipsToPixels(tab.position) * zoom}
          onDoubleClick={() => onTabMarkRemove?.(tab.position)}
        />
      ))}

      {/* Drag tooltip */}
      {dragging && dragValue !== null && dragPositionPx !== null && (
        <DragTooltip value={formatValueForTooltip(dragValue, unit)} positionPx={dragPositionPx} />
      )}
    </div>
  );
}

// ============================================================================
// SUB-COMPONENTS
// ============================================================================

interface TickData {
  position: number;
  height: number;
  label?: string;
}

function RulerTick({ tick }: { tick: TickData }): React.ReactElement {
  return (
    <>
      <div
        style={{
          position: 'absolute',
          left: formatPx(tick.position),
          bottom: 0,
          width: 1,
          height: tick.height,
          backgroundColor: RULER_TICK_COLOR,
        }}
      />
      {tick.label && (
        <div
          style={{
            position: 'absolute',
            left: formatPx(tick.position),
            top: 3,
            transform: 'translateX(-50%)',
            fontSize: '9px',
            color: RULER_TEXT_COLOR,
            fontFamily: 'sans-serif',
            whiteSpace: 'nowrap',
          }}
        >
          {tick.label}
        </div>
      )}
    </>
  );
}

/**
 * Indent triangle handle — Google Docs style.
 * direction="down": ▼ anchored at top (first-line indent, right indent)
 * direction="up":   ▲ anchored at bottom (left indent)
 */
interface IndentTriangleProps {
  direction: 'up' | 'down';
  positionPx: number;
  editable: boolean;
  isDragging: boolean;
  isHovered: boolean;
  onMouseEnter: () => void;
  onMouseLeave: () => void;
  onMouseDown: (e: React.MouseEvent) => void;
  label: string;
}

function IndentTriangle({
  direction,
  positionPx,
  editable,
  isDragging,
  isHovered,
  onMouseEnter,
  onMouseLeave,
  onMouseDown,
  label,
}: IndentTriangleProps): React.ReactElement {
  const color = isDragging ? INDENT_ACTIVE_COLOR : isHovered ? INDENT_HOVER_COLOR : INDENT_COLOR;
  const triHeight = Math.round(TRI_SIZE * 1.6);

  const containerStyle: CSSProperties = {
    position: 'absolute',
    left: formatPx(positionPx - TRI_SIZE),
    width: TRI_SIZE * 2,
    height: triHeight + 2,
    cursor: editable ? 'ew-resize' : 'default',
    zIndex: isDragging ? 10 : 4,
    ...(direction === 'down' ? { top: 0 } : { bottom: 0 }),
  };

  const triangleStyle: CSSProperties =
    direction === 'down'
      ? {
          position: 'absolute',
          top: 1,
          left: 0,
          width: 0,
          height: 0,
          borderLeft: `${TRI_SIZE}px solid transparent`,
          borderRight: `${TRI_SIZE}px solid transparent`,
          borderTop: `${triHeight}px solid ${color}`,
          transition: 'border-top-color 0.1s',
        }
      : {
          position: 'absolute',
          bottom: 1,
          left: 0,
          width: 0,
          height: 0,
          borderLeft: `${TRI_SIZE}px solid transparent`,
          borderRight: `${TRI_SIZE}px solid transparent`,
          borderBottom: `${triHeight}px solid ${color}`,
          transition: 'border-bottom-color 0.1s',
        };

  return (
    <div
      className="docx-ruler-indent"
      style={containerStyle}
      onMouseEnter={onMouseEnter}
      onMouseLeave={onMouseLeave}
      onMouseDown={onMouseDown}
      role="slider"
      aria-label={label}
      aria-orientation="horizontal"
      tabIndex={editable ? 0 : -1}
    >
      <div style={triangleStyle} />
    </div>
  );
}

function DragTooltip({
  value,
  positionPx,
}: {
  value: string;
  positionPx: number;
}): React.ReactElement {
  return (
    <div
      style={{
        position: 'absolute',
        left: formatPx(positionPx),
        top: -22,
        transform: 'translateX(-50%)',
        backgroundColor: '#333',
        color: '#fff',
        fontSize: '10px',
        fontFamily: 'sans-serif',
        padding: '2px 6px',
        borderRadius: 3,
        whiteSpace: 'nowrap',
        pointerEvents: 'none',
        zIndex: 20,
      }}
    >
      {value}
    </div>
  );
}

interface TabMarkerProps {
  tabMark: TabMark;
  positionPx: number;
  onDoubleClick: () => void;
}

const TAB_SYMBOLS: Record<string, string> = {
  left: 'L',
  center: 'C',
  right: 'R',
  decimal: 'D',
  bar: '|',
};

function TabMarker({
  tabMark,
  positionPx,
  onDoubleClick,
}: TabMarkerProps): React.ReactElement {
  return (
    <div
      style={{
        position: 'absolute',
        left: formatPx(positionPx - 5),
        bottom: 0,
        width: 10,
        height: 12,
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        fontSize: 8,
        fontWeight: 700,
        color: '#555',
        cursor: 'pointer',
        userSelect: 'none',
      }}
      onDoubleClick={(e) => {
        e.stopPropagation();
        onDoubleClick();
      }}
      title={`${tabMark.alignment} tab at ${(tabMark.position / 1440).toFixed(2)}"`}
    >
      {TAB_SYMBOLS[tabMark.alignment] || 'L'}
    </div>
  );
}

// ============================================================================
// UTILITY FUNCTIONS
// ============================================================================

function generateTicks(pageWidthTwips: number, zoom: number, unit: 'inch' | 'cm'): TickData[] {
  const ticks: TickData[] = [];

  if (unit === 'inch') {
    const eighthInchTwips = TWIPS_PER_INCH / 8;
    const totalEighths = Math.ceil(pageWidthTwips / eighthInchTwips);
    for (let i = 0; i <= totalEighths; i++) {
      const twipsPos = i * eighthInchTwips;
      if (twipsPos > pageWidthTwips) break;
      const pxPos = twipsToPixels(twipsPos) * zoom;
      if (i % 8 === 0) {
        ticks.push({ position: pxPos, height: 10, label: i / 8 > 0 ? String(i / 8) : undefined });
      } else if (i % 4 === 0) {
        ticks.push({ position: pxPos, height: 6 });
      } else if (i % 2 === 0) {
        ticks.push({ position: pxPos, height: 4 });
      } else {
        ticks.push({ position: pxPos, height: 2 });
      }
    }
  } else {
    const mmTwips = TWIPS_PER_CM / 10;
    const totalMm = Math.ceil(pageWidthTwips / mmTwips);
    for (let i = 0; i <= totalMm; i++) {
      const twipsPos = i * mmTwips;
      if (twipsPos > pageWidthTwips) break;
      const pxPos = twipsToPixels(twipsPos) * zoom;
      if (i % 10 === 0) {
        ticks.push({ position: pxPos, height: 10, label: i / 10 > 0 ? String(i / 10) : undefined });
      } else if (i % 5 === 0) {
        ticks.push({ position: pxPos, height: 6 });
      } else {
        ticks.push({ position: pxPos, height: 3 });
      }
    }
  }

  return ticks;
}

export function positionToMargin(
  positionPx: number,
  side: 'left' | 'right',
  pageWidthPx: number,
  zoom: number
): number {
  const positionTwips = pixelsToTwips(positionPx / zoom);
  if (side === 'left') return Math.max(0, positionTwips);
  return Math.max(0, pixelsToTwips(pageWidthPx / zoom) - positionTwips);
}

export function getRulerDimensions(
  sectionProps?: SectionProperties | null,
  zoom: number = 1
): { width: number; leftMargin: number; rightMargin: number; contentWidth: number } {
  const pw = sectionProps?.pageWidth ?? DEFAULT_PAGE_WIDTH_TWIPS;
  const lm = sectionProps?.marginLeft ?? DEFAULT_MARGIN_TWIPS;
  const rm = sectionProps?.marginRight ?? DEFAULT_MARGIN_TWIPS;
  const width = twipsToPixels(pw) * zoom;
  const leftMargin = twipsToPixels(lm) * zoom;
  const rightMargin = twipsToPixels(rm) * zoom;
  return { width, leftMargin, rightMargin, contentWidth: width - leftMargin - rightMargin };
}

export function getMarginInUnits(marginTwips: number, unit: 'inch' | 'cm'): string {
  return unit === 'inch'
    ? (marginTwips / TWIPS_PER_INCH).toFixed(2) + '"'
    : (marginTwips / TWIPS_PER_CM).toFixed(1) + ' cm';
}

export function parseMarginFromUnits(value: string, unit: 'inch' | 'cm'): number | null {
  const num = parseFloat(value.replace(/[^\d.]/g, ''));
  if (isNaN(num)) return null;
  return Math.round(num * (unit === 'inch' ? TWIPS_PER_INCH : TWIPS_PER_CM));
}

export default HorizontalRuler;
