// packages/react/src/editor/DocxEditorInvalidTextFormFieldDialog.tsx
import { useEffect, useRef, useState } from 'react';
import type { CSSProperties } from 'react';
import type { InvalidTextFormFieldSession } from '@docx-editor.dev/core/editor';
import type { DocxEditorChildren } from '../docx-editor-children';
import { useFormControlTranslate } from './form-control-translate';
import { DialogFrame } from './dialog-parts';

/** Invalid-value acknowledgement with editor-owned clearing and focus restoration. @public */
export interface DocxEditorInvalidTextFormFieldDialogProps {
  session: InvalidTextFormFieldSession;
  className?: string;
  style?: CSSProperties;
  children?: DocxEditorChildren;
}
/** Default acknowledgement shell for a custom popup renderer. @public */
export function DocxEditorInvalidTextFormFieldDialog(
  props: DocxEditorInvalidTextFormFieldDialogProps
) {
  const [session, setSession] = useState(props.session);
  const [generation, setGeneration] = useState(0);
  if (session !== props.session) {
    setSession(props.session);
    setGeneration(generation + 1);
  }
  return <InvalidForm key={generation} {...props} />;
}
function InvalidForm({
  session,
  className,
  style,
  children,
}: DocxEditorInvalidTextFormFieldDialogProps) {
  const t = useFormControlTranslate();
  const [closed, setClosed] = useState(session.signal.aborted);
  const panelRef = useRef<HTMLDialogElement | null>(null);
  useEffect(() => {
    const abort = () => setClosed(true);
    session.signal.addEventListener('abort', abort, { once: true });
    if (session.signal.aborted) abort();
    return () => session.signal.removeEventListener('abort', abort);
  }, [session]);
  if (closed) return null;
  return (
    <DialogFrame
      kind="invalidTextFormField"
      role="alertdialog"
      label={t('textFormField.invalidTitle')}
      className={className}
      style={style}
      panelRef={panelRef}
      dismissOutside={false}
      onClose={session.acknowledge}
      sessionSignal={session.signal}
      restoreFocus={false}
      onKeyDown={(event) => {
        if (event.key === 'Enter' && !event.nativeEvent.isComposing) {
          event.preventDefault();
          session.acknowledge();
        }
      }}
    >
      {children ?? (
        <>
          <header className="docx-dialog__header">
            <h2 className="docx-dialog__title">{t('textFormField.invalidTitle')}</h2>
          </header>
          <div className="docx-dialog__body">
            {t(
              session.type === 'number'
                ? 'textFormField.invalidNumber'
                : 'textFormField.invalidDate'
            )}
          </div>
          <footer className="docx-dialog__footer">
            <button
              type="button"
              className="docx-dialog__button docx-dialog__button--primary"
              onClick={session.acknowledge}
            >
              {t('textFormField.apply')}
            </button>
          </footer>
        </>
      )}
    </DialogFrame>
  );
}

// packages/vue/src/editor/DocxEditorInvalidTextFormFieldDialog.tsx
import { defineComponent, ref, watch, type CSSProperties, type PropType } from 'vue';
import type { InvalidTextFormFieldSession } from '@docx-editor.dev/core/editor';
import type { DocxEditorChildren } from '../docx-editor-children';
import { NativeDialog } from './dialog-parts';
import { useFormControlTranslate } from './form-control-translate';
/** Invalid-value acknowledgement with editor-owned clearing and focus restoration. @public */
export interface DocxEditorInvalidTextFormFieldDialogProps {
  session: InvalidTextFormFieldSession;
  className?: string;
  style?: CSSProperties;
  children?: DocxEditorChildren;
}
/** Default acknowledgement shell for a custom popup renderer. @public */
export const DocxEditorInvalidTextFormFieldDialog = defineComponent({
  name: 'DocxEditorInvalidTextFormFieldDialog',
  props: {
    session: { type: Object as PropType<InvalidTextFormFieldSession>, required: true },
    className: String,
    style: Object as PropType<CSSProperties>,
    children: Object as PropType<DocxEditorChildren>,
  },
  setup(props, { slots }) {
    const t = useFormControlTranslate();
    const closed = ref(false);
    watch(
      () => props.session,
      (session, _old, onCleanup) => {
        closed.value = session.signal.aborted;
        const abort = () => {
          closed.value = true;
        };
        session.signal.addEventListener('abort', abort, { once: true });
        onCleanup(() => session.signal.removeEventListener('abort', abort));
      },
      { immediate: true }
    );
    return () =>
      closed.value ? null : (
        <NativeDialog
          kind="invalidTextFormField"
          label={t('textFormField.invalidTitle')}
          role="alertdialog"
          class={props.className}
          style={props.style}
          onClose={() => props.session.acknowledge()}
          sessionSignal={props.session.signal}
          restoreFocus={false}
          dismissOutside={false}
          onKeydown={(event) => {
            if (event.key === 'Enter' && !event.isComposing) {
              event.preventDefault();
              props.session.acknowledge();
            }
          }}
          content={() =>
            slots.default?.() ??
            props.children ?? (
              <>
                <header class="docx-dialog__header">
                  <h2 class="docx-dialog__title">{t('textFormField.invalidTitle')}</h2>
                </header>
                <div class="docx-dialog__body">
                  {t(
                    props.session.type === 'number'
                      ? 'textFormField.invalidNumber'
                      : 'textFormField.invalidDate'
                  )}
                </div>
                <footer class="docx-dialog__footer">
                  <button
                    class="docx-dialog__button docx-dialog__button--primary"
                    type="button"
                    onClick={() => props.session.acknowledge()}
                  >
                    {t('textFormField.apply')}
                  </button>
                </footer>
              </>
            )
          }
        />
      );
  },
});
