// packages/react/src/editor/DocxEditorContentControlWidget.tsx
import { useEffect, useLayoutEffect, useRef, useState } from 'react';
import type { CSSProperties, ReactNode } from 'react';
import type { ContentControlWidgetSession } from '@docx-editor.dev/core/editor';
import type { DocxEditorChildren } from '../docx-editor-children';
import { useFormControlTranslate } from './form-control-translate';
import { absolutePointInScroller } from './scroller-geometry';
import {
  ContentControlWidgetProvider,
  useContentControlWidgetState,
  type UseContentControlWidgetResult,
} from './content-control-widget/context';
import {
  ContentControlWidgetApply,
  ContentControlWidgetCalendar,
  ContentControlWidgetCancel,
  ContentControlWidgetDay,
  ContentControlWidgetError,
  ContentControlWidgetFooter,
  ContentControlWidgetGrid,
  ContentControlWidgetHeader,
  ContentControlWidgetInput,
  ContentControlWidgetItem,
  ContentControlWidgetList,
  ContentControlWidgetNextMonth,
  ContentControlWidgetPreviousMonth,
  ContentControlWidgetTitle,
  ContentControlWidgetToday,
  ContentControlWidgetWeekdays,
} from './content-control-widget/parts';

/** Value-widget session and optional replacement controls. @public */
export interface DocxEditorContentControlWidgetProps {
  session: ContentControlWidgetSession;
  className?: string;
  style?: CSSProperties;
  /**
   * Replaces the packaged arrangement. Compose it from the compound's parts
   * (`DocxEditorContentControlWidget.Calendar`, `.List`, …) or from `useContentControlWidget()`.
   */
  children?: DocxEditorChildren;
}

/**
 * The packaged value pop-up for a dropdown, combo-box, date or checkbox content control.
 *
 * Anchored below the control inside the editor's scroll container. Without `children` it
 * renders the same arrangement the engine paints on its own — a list, a list with free-text
 * entry, or a month calendar with a Today button — from the same stylesheet classes, so one
 * theme covers both. A checkbox session applies its toggle at once and shows nothing.
 * @public
 */
function ContentControlWidgetRoot(props: DocxEditorContentControlWidgetProps) {
  const [session, setSession] = useState(props.session);
  const [generation, setGeneration] = useState(0);
  if (session !== props.session) {
    setSession(props.session);
    setGeneration(generation + 1);
  }
  return <WidgetPanel key={generation} {...props} />;
}

function WidgetPanel({ session, className, style, children }: DocxEditorContentControlWidgetProps) {
  const t = useFormControlTranslate();
  const widget = useContentControlWidgetState(session);
  const [closed, setClosed] = useState(session.signal.aborted);
  const panelRef = useRef<HTMLDivElement | null>(null);
  const [opener] = useState(() =>
    typeof document === 'undefined' ? null : (document.activeElement as HTMLElement | null)
  );
  const [position, setPosition] = useState<CSSProperties>({});
  // A checkbox has no pop-up: the packaged arrangement IS the toggle, so configuring this
  // popup for a restyled dropdown never makes checkboxes stop working. A host that renders
  // its own children owns the decision instead.
  const immediate = session.kind === 'checkbox' && children === undefined;
  useEffect(() => {
    const abort = () => setClosed(true);
    session.signal.addEventListener('abort', abort, { once: true });
    if (session.signal.aborted) abort();
    return () => session.signal.removeEventListener('abort', abort);
  }, [session]);
  useEffect(() => {
    if (!immediate || session.signal.aborted) return;
    session.apply(session.value === 'true' ? 'false' : 'true');
  }, [immediate, session]);
  useLayoutEffect(() => {
    if (closed || immediate) return;
    const panel = panelRef.current;
    const owner = panel?.ownerDocument;
    const scroller = panel?.closest<HTMLElement>('.docx-editor__scroll-container');
    const anchor = session.anchor;
    if (anchor && scroller) {
      const rect = anchor.getBoundingClientRect();
      const sheet = anchor.closest('.docx-page')?.getBoundingClientRect();
      const left = sheet
        ? Math.max(sheet.left, Math.min(rect.left, sheet.right - panel!.offsetWidth))
        : rect.left;
      setPosition(absolutePointInScroller(scroller, left, rect.bottom));
    }
    // The calendar grid places its own roving focus; everything else takes the first control.
    if (!panel?.querySelector('[data-docx-part="grid"]')) {
      panel?.querySelector<HTMLElement>('input,select,button')?.focus({ preventScroll: true });
    }
    return () => {
      const active = owner?.activeElement;
      if (opener?.isConnected && (active === owner?.body || (active && panel?.contains(active)))) {
        opener.focus({ preventScroll: true });
      }
    };
  }, [session, closed, immediate, opener]);
  useEffect(() => {
    const panel = panelRef.current;
    if (!panel || closed || immediate) return;
    const dismiss = (event: PointerEvent) => {
      if (!panel.contains(event.target as Node)) session.cancel();
    };
    panel.ownerDocument.addEventListener('pointerdown', dismiss, true);
    return () => panel.ownerDocument.removeEventListener('pointerdown', dismiss, true);
  }, [session, closed, immediate]);
  if (closed || immediate) return null;
  const label = t(`contentControl.types.${session.kind}`);
  return (
    <ContentControlWidgetProvider value={widget}>
      <div
        ref={panelRef}
        role="dialog"
        aria-label={label}
        className={`docx-content-control-widget-popup${className ? ` ${className}` : ''}`}
        style={{ ...position, ...style }}
        data-docx-popup="contentControlWidget"
        data-kind={session.kind}
        onPointerDown={(event) => event.stopPropagation()}
        onKeyDown={(event) => {
          if (event.nativeEvent.isComposing) return;
          if (event.key === 'Escape') {
            event.preventDefault();
            event.stopPropagation();
            session.cancel();
          }
          if (event.key === 'Enter' && event.target instanceof HTMLInputElement) {
            event.preventDefault();
            widget.apply();
          }
        }}
      >
        {children ?? defaultArrangement(widget)}
      </div>
    </ContentControlWidgetProvider>
  );
}

function defaultArrangement(widget: UseContentControlWidgetResult): ReactNode {
  if (widget.kind === 'date') return <ContentControlWidgetCalendar />;
  if (widget.kind === 'comboBox') {
    return (
      <>
        <ContentControlWidgetInput />
        <ContentControlWidgetList />
        <ContentControlWidgetError />
        <ContentControlWidgetFooter />
      </>
    );
  }
  return (
    <>
      <ContentControlWidgetList />
      <ContentControlWidgetError />
    </>
  );
}

/** The compound pop-up with its parts attached as statics. @public */
export interface DocxEditorContentControlWidgetNamespace {
  (props: DocxEditorContentControlWidgetProps): ReactNode;
  readonly Calendar: typeof ContentControlWidgetCalendar;
  readonly Header: typeof ContentControlWidgetHeader;
  readonly PreviousMonth: typeof ContentControlWidgetPreviousMonth;
  readonly Title: typeof ContentControlWidgetTitle;
  readonly NextMonth: typeof ContentControlWidgetNextMonth;
  readonly Weekdays: typeof ContentControlWidgetWeekdays;
  readonly Grid: typeof ContentControlWidgetGrid;
  readonly Day: typeof ContentControlWidgetDay;
  readonly Today: typeof ContentControlWidgetToday;
  readonly List: typeof ContentControlWidgetList;
  readonly Item: typeof ContentControlWidgetItem;
  readonly Input: typeof ContentControlWidgetInput;
  readonly Error: typeof ContentControlWidgetError;
  readonly Footer: typeof ContentControlWidgetFooter;
  readonly Apply: typeof ContentControlWidgetApply;
  readonly Cancel: typeof ContentControlWidgetCancel;
}

/** Compact value editor for a configured content-control popup. @public */
export const DocxEditorContentControlWidget: DocxEditorContentControlWidgetNamespace =
  Object.assign(ContentControlWidgetRoot, {
    Calendar: ContentControlWidgetCalendar,
    Header: ContentControlWidgetHeader,
    PreviousMonth: ContentControlWidgetPreviousMonth,
    Title: ContentControlWidgetTitle,
    NextMonth: ContentControlWidgetNextMonth,
    Weekdays: ContentControlWidgetWeekdays,
    Grid: ContentControlWidgetGrid,
    Day: ContentControlWidgetDay,
    Today: ContentControlWidgetToday,
    List: ContentControlWidgetList,
    Item: ContentControlWidgetItem,
    Input: ContentControlWidgetInput,
    Error: ContentControlWidgetError,
    Footer: ContentControlWidgetFooter,
    Apply: ContentControlWidgetApply,
    Cancel: ContentControlWidgetCancel,
  });

// packages/vue/src/editor/DocxEditorContentControlWidget.tsx
import {
  computed,
  defineComponent,
  onBeforeUnmount,
  ref,
  toRef,
  watch,
  type CSSProperties,
  type PropType,
  type VNode,
  type VNodeChild,
} from 'vue';
import type { ContentControlWidgetSession } from '@docx-editor.dev/core/editor';
import type { DocxEditorChildren } from '../docx-editor-children';
import { useFormControlTranslate } from './form-control-translate';
import { absolutePointInScroller } from './scroller-geometry';
import {
  provideContentControlWidget,
  useContentControlWidgetState,
  type UseContentControlWidgetResult,
} from './content-control-widget/context';
import {
  ContentControlWidgetApply,
  ContentControlWidgetCalendar,
  ContentControlWidgetCancel,
  ContentControlWidgetDay,
  ContentControlWidgetError,
  ContentControlWidgetFooter,
  ContentControlWidgetGrid,
  ContentControlWidgetHeader,
  ContentControlWidgetInput,
  ContentControlWidgetItem,
  ContentControlWidgetList,
  ContentControlWidgetNextMonth,
  ContentControlWidgetPreviousMonth,
  ContentControlWidgetTitle,
  ContentControlWidgetToday,
  ContentControlWidgetWeekdays,
} from './content-control-widget/parts';

/** Value-widget session and optional replacement controls. @public */
export interface DocxEditorContentControlWidgetProps {
  session: ContentControlWidgetSession;
  className?: string;
  style?: CSSProperties;
  /**
   * Replaces the packaged arrangement. Compose it from the compound's parts
   * (`DocxEditorContentControlWidget.Calendar`, `.List`, …) or from `useContentControlWidget()`.
   */
  children?: DocxEditorChildren;
}

function defaultArrangement(widget: UseContentControlWidgetResult): VNodeChild {
  const kind = widget.kind.value;
  if (kind === 'date') return <ContentControlWidgetCalendar />;
  if (kind === 'comboBox') {
    return (
      <>
        <ContentControlWidgetInput />
        <ContentControlWidgetList />
        <ContentControlWidgetError />
        <ContentControlWidgetFooter />
      </>
    );
  }
  return (
    <>
      <ContentControlWidgetList />
      <ContentControlWidgetError />
    </>
  );
}

/**
 * The packaged value pop-up for a dropdown, combo-box, date or checkbox content control.
 *
 * Anchored below the control inside the editor's scroll container. Without children it
 * renders the same arrangement the engine paints on its own — a list, a list with free-text
 * entry, or a month calendar with a Today button — from the same stylesheet classes, so one
 * theme covers both. A checkbox session applies its toggle at once and shows nothing.
 * @public
 */
const ContentControlWidgetRoot = defineComponent({
  name: 'DocxEditorContentControlWidget',
  props: {
    session: { type: Object as PropType<ContentControlWidgetSession>, required: true },
    className: String,
    style: Object as PropType<CSSProperties>,
    children: [Object, Array, String] as PropType<DocxEditorChildren>,
  },
  setup(props, { slots }) {
    const t = useFormControlTranslate();
    const session = toRef(props, 'session');
    const widget = useContentControlWidgetState(session);
    provideContentControlWidget(widget);
    const closed = ref(props.session.signal.aborted);
    const panel = ref<HTMLDivElement | null>(null);
    const position = ref<CSSProperties>({});
    // A checkbox has no pop-up: the packaged arrangement IS the toggle, so configuring this
    // popup for a restyled dropdown never makes checkboxes stop working. A host that renders
    // its own children owns the decision instead.
    const immediate = computed(
      () => props.session.kind === 'checkbox' && !slots.default && props.children === undefined
    );
    let opener: HTMLElement | null =
      typeof document === 'undefined' ? null : (document.activeElement as HTMLElement | null);
    let focusPanel: HTMLDivElement | null = null;
    const restoreFocus = () => {
      const previous = opener;
      const element = focusPanel;
      opener = null;
      focusPanel = null;
      if (!previous?.isConnected || !element) return;
      const active = element.ownerDocument.activeElement;
      if (active === element.ownerDocument.body || (active && element.contains(active)))
        previous.focus({ preventScroll: true });
    };
    onBeforeUnmount(restoreFocus);
    watch(
      session,
      (current, _old, onCleanup) => {
        closed.value = current.signal.aborted;
        const abort = () => {
          closed.value = true;
        };
        current.signal.addEventListener('abort', abort, { once: true });
        onCleanup(() => current.signal.removeEventListener('abort', abort));
        if (immediate.value && !current.signal.aborted) {
          current.apply(current.value === 'true' ? 'false' : 'true');
        }
      },
      { immediate: true }
    );
    watch(
      [panel, session],
      ([element, current]) => {
        if (!element) {
          restoreFocus();
          return;
        }
        if (focusPanel) {
          restoreFocus();
          const active = element.ownerDocument.activeElement;
          opener = active instanceof HTMLElement ? active : null;
        }
        focusPanel = element;
        const scroller = element.closest<HTMLElement>('.docx-editor__scroll-container');
        if (current.anchor && scroller) {
          const rect = current.anchor.getBoundingClientRect();
          const sheet = current.anchor.closest('.docx-page')?.getBoundingClientRect();
          const left = sheet
            ? Math.max(sheet.left, Math.min(rect.left, sheet.right - element.offsetWidth))
            : rect.left;
          position.value = absolutePointInScroller(scroller, left, rect.bottom);
        }
        // The calendar grid places its own roving focus; everything else takes the first control.
        if (!element.querySelector('[data-docx-part="grid"]')) {
          element.querySelector<HTMLElement>('input,select,button')?.focus({ preventScroll: true });
        }
      },
      { flush: 'post' }
    );
    watch(
      [panel, closed],
      ([element, isClosed], _old, onCleanup) => {
        if (!element || isClosed) return;
        const dismiss = (event: Event) => {
          if (!element.contains(event.target as Node)) props.session.cancel();
        };
        element.ownerDocument.addEventListener('pointerdown', dismiss, true);
        onCleanup(() => element.ownerDocument.removeEventListener('pointerdown', dismiss, true));
      },
      { flush: 'post' }
    );
    return () => {
      if (closed.value || immediate.value) return null;
      const current = props.session;
      const label = t(`contentControl.types.${current.kind}`);
      return (
        <div
          ref={panel}
          role="dialog"
          aria-label={label}
          class={['docx-content-control-widget-popup', props.className]}
          style={{ ...position.value, ...props.style }}
          data-docx-popup="contentControlWidget"
          data-kind={current.kind}
          onPointerdown={(event) => event.stopPropagation()}
          onKeydown={(event) => {
            if (event.isComposing) return;
            if (event.key === 'Escape') {
              event.preventDefault();
              event.stopPropagation();
              current.cancel();
            }
            if (event.key === 'Enter' && event.target instanceof HTMLInputElement) {
              event.preventDefault();
              widget.apply();
            }
          }}
        >
          {slots.default?.() ?? props.children ?? defaultArrangement(widget)}
        </div>
      );
    };
  },
});

/** The compound pop-up with its parts attached as statics. @public */
export interface DocxEditorContentControlWidgetNamespace {
  (props: DocxEditorContentControlWidgetProps): VNode | null;
  readonly Calendar: typeof ContentControlWidgetCalendar;
  readonly Header: typeof ContentControlWidgetHeader;
  readonly PreviousMonth: typeof ContentControlWidgetPreviousMonth;
  readonly Title: typeof ContentControlWidgetTitle;
  readonly NextMonth: typeof ContentControlWidgetNextMonth;
  readonly Weekdays: typeof ContentControlWidgetWeekdays;
  readonly Grid: typeof ContentControlWidgetGrid;
  readonly Day: typeof ContentControlWidgetDay;
  readonly Today: typeof ContentControlWidgetToday;
  readonly List: typeof ContentControlWidgetList;
  readonly Item: typeof ContentControlWidgetItem;
  readonly Input: typeof ContentControlWidgetInput;
  readonly Error: typeof ContentControlWidgetError;
  readonly Footer: typeof ContentControlWidgetFooter;
  readonly Apply: typeof ContentControlWidgetApply;
  readonly Cancel: typeof ContentControlWidgetCancel;
}

/** Compact value editor for a configured content-control popup. @public */
export const DocxEditorContentControlWidget = Object.assign(ContentControlWidgetRoot, {
  Calendar: ContentControlWidgetCalendar,
  Header: ContentControlWidgetHeader,
  PreviousMonth: ContentControlWidgetPreviousMonth,
  Title: ContentControlWidgetTitle,
  NextMonth: ContentControlWidgetNextMonth,
  Weekdays: ContentControlWidgetWeekdays,
  Grid: ContentControlWidgetGrid,
  Day: ContentControlWidgetDay,
  Today: ContentControlWidgetToday,
  List: ContentControlWidgetList,
  Item: ContentControlWidgetItem,
  Input: ContentControlWidgetInput,
  Error: ContentControlWidgetError,
  Footer: ContentControlWidgetFooter,
  Apply: ContentControlWidgetApply,
  Cancel: ContentControlWidgetCancel,
}) as unknown as DocxEditorContentControlWidgetNamespace;
