// packages/react/src/editor/DocxEditorTextFormFieldDialog.tsx
import { useEditorState } from './useEditorState';
import { useEffect, useState } from 'react';
import type { TextFormFieldDialogSession } from '@docx-editor.dev/core/editor';
import { TEXT_FORM_FORMATS } from '@docx-editor.dev/core/editor';
import type { TextFormFieldOptions } from '@docx-editor.dev/core/store';
import { useFormControlTranslate } from './form-control-translate';
import {
  createDialogParts,
  DialogFrame,
  type DialogCustomizationProps,
  type UseDialogReturn,
} from './dialog-parts';

/** Draft values for legacy text Field Options. @public */
export interface TextFormFieldDialogFields {
  defaultText: string;
  type: string;
  maxLength: number;
  format: string;
  enabled: boolean;
}
/** Field Options session and presentation. @public */
export interface DocxEditorTextFormFieldDialogProps extends DialogCustomizationProps {
  session: TextFormFieldDialogSession | null;
}
/** Field Options draft and actions. @public */
export interface UseTextFormFieldDialogReturn extends UseDialogReturn<TextFormFieldDialogFields> {}
const parts = createDialogParts<keyof TextFormFieldDialogFields, UseTextFormFieldDialogReturn>();
/** Read the enclosing Field Options draft. @public */
export function useTextFormFieldDialog(): UseTextFormFieldDialogReturn {
  return parts.useState();
}

function TextFormFieldDialogRoot({ session, ...props }: DocxEditorTextFormFieldDialogProps) {
  // A new request creates a new draft even if the same field opens again.
  const [current, setCurrent] = useState(session);
  const [generation, setGeneration] = useState(0);
  if (current !== session) {
    setCurrent(session);
    setGeneration(generation + 1);
  }
  return session ? <TextFormFieldForm key={generation} session={session} {...props} /> : null;
}
function TextFormFieldForm({
  session,
  children,
  preset,
  className,
  style,
}: DialogCustomizationProps & { session: TextFormFieldDialogSession }) {
  const t = useFormControlTranslate();
  const isEnabled = useEditorState(() => session.canApply());
  const [values, setValues] = useState<TextFormFieldDialogFields>(() => ({
    defaultText: session.field.defaultText,
    type: session.field.type,
    maxLength: session.field.maxLength,
    format: session.field.format,
    enabled: session.field.enabled,
  }));
  const [closed, setClosed] = useState(session.signal.aborted);
  const [refused, setRefused] = useState(false);
  useEffect(() => {
    const close = () => setClosed(true);
    session.signal.addEventListener('abort', close);
    if (session.signal.aborted) close();
    return () => session.signal.removeEventListener('abort', close);
  }, [session]);
  const apply = () => {
    if (session.signal.aborted) return;
    const accepted =
      Number.isInteger(values.maxLength) &&
      values.maxLength >= 0 &&
      values.maxLength <= 32767 &&
      session.apply(values.defaultText, {
        type: values.type as TextFormFieldOptions['type'],
        maxLength: values.maxLength,
        format: values.format,
        enabled: values.enabled,
      });
    setRefused(!accepted);
  };
  const state: UseTextFormFieldDialogReturn = {
    values,
    setValue(name, value) {
      setValues((previous) => ({
        ...previous,
        [name]: value,
        ...(name === 'type' ? { format: '' } : {}),
      }));
      setRefused(false);
    },
    errors: refused ? { form: t('textFormField.invalidOptions') } : {},
    isEnabled: !closed && isEnabled,
    apply,
    cancel: session.cancel,
  };
  if (closed) return null;
  const formats: readonly string[] =
    TEXT_FORM_FORMATS[values.type as keyof typeof TEXT_FORM_FORMATS] ?? [];
  const formatKeys = {
    Uppercase: 'textFormField.uppercase',
    Lowercase: 'textFormField.lowercase',
    'First capital': 'textFormField.firstCapital',
    'Title case': 'textFormField.titleCase',
  } as const;
  const row = (name: keyof TextFormFieldDialogFields, control: React.ReactNode) => (
    <label data-docx-part="field" data-docx-field={name} className="docx-dialog__row">
      <span className="docx-dialog__label">{t(`textFormField.${name}`)}</span>
      {control}
    </label>
  );
  return (
    <DialogFrame
      kind="textFormField"
      className={className}
      style={style}
      label={t('textFormField.title')}
      onClose={session.cancel}
      dismissOutside={false}
      sessionSignal={session.signal}
      restoreFocus={false}
      onKeyDown={(event) => {
        if (event.key === 'Escape') {
          event.preventDefault();
          session.cancel();
        }
        if (event.key === 'Enter' && event.target instanceof HTMLInputElement) {
          event.preventDefault();
          apply();
        }
      }}
    >
      <parts.Composition
        state={state}
        preset={preset}
        defaults={
          <>
            <div data-docx-part="header" className="docx-dialog__header">
              <span data-docx-part="title" className="docx-dialog__title">
                {t('textFormField.title')}
              </span>
            </div>
            <div data-docx-part="body" className="docx-dialog__body">
              {row(
                'defaultText',
                <input
                  className="docx-dialog__input"
                  value={values.defaultText}
                  onChange={(e) => state.setValue('defaultText', e.target.value)}
                />
              )}
              {row(
                'type',
                <select
                  className="docx-dialog__input"
                  value={values.type}
                  onChange={(e) => state.setValue('type', e.target.value)}
                >
                  {(['regular', 'number', 'date'] as const).map((type) => (
                    <option key={type} value={type}>
                      {t(`textFormField.${type}`)}
                    </option>
                  ))}
                  {!Object.hasOwn(TEXT_FORM_FORMATS, values.type) ? (
                    <option value={values.type} disabled>
                      {t('textFormField.preservedType')}
                    </option>
                  ) : null}
                </select>
              )}
              {row(
                'maxLength',
                <input
                  className="docx-dialog__input"
                  type="number"
                  min={0}
                  max={32767}
                  step={1}
                  value={Number.isNaN(values.maxLength) ? '' : values.maxLength}
                  onChange={(e) => state.setValue('maxLength', e.target.valueAsNumber)}
                />
              )}
              {row(
                'format',
                <select
                  className="docx-dialog__input"
                  value={values.format}
                  onChange={(e) => state.setValue('format', e.target.value)}
                >
                  {formats.map((format) => (
                    <option key={format} value={format}>
                      {formatKeys[format as keyof typeof formatKeys]
                        ? t(formatKeys[format as keyof typeof formatKeys])
                        : format || t('textFormField.noFormat')}
                    </option>
                  ))}
                  {!formats.includes(values.format) ? (
                    <option value={values.format} disabled>
                      {values.format || t('textFormField.noFormat')}
                    </option>
                  ) : null}
                </select>
              )}
              <label
                data-docx-part="field"
                data-docx-field="enabled"
                className="docx-dialog__checkbox-row"
              >
                <input
                  type="checkbox"
                  checked={values.enabled}
                  onChange={(e) => state.setValue('enabled', e.target.checked)}
                />
                {t('textFormField.enabled')}
              </label>
            </div>
            <div data-docx-part="footer" className="docx-dialog__footer">
              <span data-docx-part="error" className="docx-dialog__error" role="alert">
                {state.errors.form}
              </span>
              <button
                data-docx-part="cancel"
                className="docx-dialog__button"
                type="button"
                onClick={session.cancel}
              >
                {t('textFormField.cancel')}
              </button>
              <button
                disabled={!isEnabled}
                data-docx-part="apply"
                className="docx-dialog__button docx-dialog__apply"
                type="button"
                onClick={apply}
              >
                {t('textFormField.apply')}
              </button>
            </div>
          </>
        }
      >
        {children}
      </parts.Composition>
    </DialogFrame>
  );
}
/** Legacy text Field Options with replaceable controls and layout. @public */
export const DocxEditorTextFormFieldDialog = Object.assign(TextFormFieldDialogRoot, {
  Header: parts.Header,
  Title: parts.Title,
  Body: parts.Body,
  Footer: parts.Footer,
  Apply: parts.Apply,
  Cancel: parts.Cancel,
  Error: parts.Error,
  Field: parts.Field,
});

// packages/vue/src/editor/DocxEditorTextFormFieldDialog.tsx
import type { DocxEditorChildren } from '../docx-editor-children';
import { useEditorState } from './useEditorState';
import {
  Fragment,
  computed,
  defineComponent,
  ref,
  watch,
  type CSSProperties,
  type PropType,
  type VNode,
} from 'vue';
import { TEXT_FORM_FORMATS, type TextFormFieldDialogSession } from '@docx-editor.dev/core/editor';
import type { TextFormFieldOptions, TextFormFieldType } from '@docx-editor.dev/core/store';
import { useFormControlTranslate } from './form-control-translate';
import {
  createDialogComposition,
  NativeDialog,
  type DialogCustomizationProps,
  type UseDialogReturn,
} from './dialog-parts';
/** Editable Field Options draft. @public */
export interface TextFormFieldDialogFields {
  defaultText: string;
  type: string;
  maxLength: number;
  format: string;
  enabled: boolean;
}
/** Field Options draft state and actions. @public */
export interface UseTextFormFieldDialogReturn extends UseDialogReturn<TextFormFieldDialogFields> {}
const composition = createDialogComposition<TextFormFieldDialogFields>('TextFormFieldDialog');
/** Access the Field Options draft and actions. @public */
export function useTextFormFieldDialog(): UseTextFormFieldDialogReturn {
  return composition.useContext();
}
/** Controlled Field Options dialog. @public */
export interface DocxEditorTextFormFieldDialogProps extends DialogCustomizationProps {
  session: TextFormFieldDialogSession | null;
}
const Impl = defineComponent({
  name: 'DocxEditorTextFormFieldDialog',
  props: {
    children: Object as PropType<DocxEditorChildren>,
    session: { type: Object as PropType<TextFormFieldDialogSession | null>, default: null },
    preset: { type: Boolean, default: true },
    className: String,
    style: Object as PropType<CSSProperties>,
  },
  setup(p, { slots }) {
    const t = useFormControlTranslate();
    const values = ref<TextFormFieldDialogFields>({
      defaultText: '',
      type: 'regular',
      maxLength: 0,
      format: '',
      enabled: true,
    });
    const refused = ref(false);
    const closed = ref(false);
    watch(
      () => p.session,
      (session, _old, onCleanup) => {
        refused.value = false;
        closed.value = false;
        if (!session) return;
        const { defaultText, type, maxLength, format, enabled } = session.field;
        values.value = { defaultText, type, maxLength, format, enabled };
        const abort = () => {
          closed.value = true;
        };
        session.signal.addEventListener('abort', abort, { once: true });
        onCleanup(() => session.signal.removeEventListener('abort', abort));
      },
      { immediate: true }
    );
    const isEnabled = useEditorState(() => p.session?.canApply() ?? false, Object.is, {
      extraDeps: () => p.session,
    });
    const cancel = () => p.session?.cancel();
    const apply = () => {
      if (!p.session?.canApply()) {
        refused.value = true;
        return;
      }
      const { defaultText, ...options } = values.value;
      refused.value = !p.session?.apply(defaultText, options as TextFormFieldOptions);
    };
    const renderParts = composition.provideContext({
      values,
      errors: computed(() => (refused.value ? { form: t('textFormField.invalidOptions') } : {})),
      isEnabled,
      setValue: (name, value) => {
        values.value = {
          ...values.value,
          [name]: value,
          ...(name === 'type' ? { format: '' } : {}),
        };
      },
      apply,
      cancel,
    });
    return () => {
      if (!p.session || p.session.signal.aborted || closed.value) return null;
      const v = values.value;
      const field = (name: keyof TextFormFieldDialogFields, input: VNode) => (
        <label data-docx-part="field" data-docx-field={name} class="docx-dialog__row">
          <span class="docx-dialog__label">{t(`textFormField.${name}`)}</span>
          {input}
        </label>
      );
      const regularLabels = {
        Uppercase: 'textFormField.uppercase',
        Lowercase: 'textFormField.lowercase',
        'First capital': 'textFormField.firstCapital',
        'Title case': 'textFormField.titleCase',
      } as const;
      const formatLabel = (format: string) => {
        const key = regularLabels[format as keyof typeof regularLabels];
        return key ? t(key) : format || t('textFormField.noFormat');
      };
      const formats: readonly string[] = TEXT_FORM_FORMATS[v.type as TextFormFieldType] ?? [];
      const defaults = (
        <Fragment>
          <div data-docx-part="header" class="docx-dialog__header">
            <span data-docx-part="title" class="docx-dialog__title">
              {t('textFormField.title')}
            </span>
          </div>
          <div data-docx-part="body" class="docx-dialog__body">
            {field(
              'defaultText',
              <input
                class="docx-dialog__input"
                value={v.defaultText}
                onInput={(e) => {
                  v.defaultText = (e.target as HTMLInputElement).value;
                }}
              />
            )}
            {field(
              'type',
              <select
                class="docx-dialog__input"
                value={v.type}
                onChange={(e) => {
                  v.type = (e.target as HTMLSelectElement).value;
                  v.format = '';
                }}
              >
                {(['regular', 'number', 'date'] as const).map((type) => (
                  <option value={type}>{t(`textFormField.${type}`)}</option>
                ))}
                {!['regular', 'number', 'date'].includes(v.type) ? (
                  <option value={v.type} disabled>
                    {t('textFormField.preservedType')}
                  </option>
                ) : null}
              </select>
            )}
            {field(
              'maxLength',
              <input
                class="docx-dialog__input"
                type="number"
                min={0}
                max={32767}
                step={1}
                value={v.maxLength}
                onInput={(e) => {
                  v.maxLength = Number((e.target as HTMLInputElement).value);
                }}
              />
            )}
            {field(
              'format',
              <select
                class="docx-dialog__input"
                value={v.format}
                onChange={(e) => {
                  v.format = (e.target as HTMLSelectElement).value;
                }}
              >
                {formats.map((format) => (
                  <option value={format}>{formatLabel(format)}</option>
                ))}
                {!formats.includes(v.format) ? (
                  <option value={v.format} disabled>
                    {v.format}
                  </option>
                ) : null}
              </select>
            )}
            {field(
              'enabled',
              <input
                type="checkbox"
                checked={v.enabled}
                onChange={(e) => {
                  v.enabled = (e.target as HTMLInputElement).checked;
                }}
              />
            )}
          </div>
          <div data-docx-part="footer" class="docx-dialog__footer">
            <span data-docx-part="error" role="alert" class="docx-dialog__error">
              {refused.value ? t('textFormField.invalidOptions') : null}
            </span>
            <button
              data-docx-part="cancel"
              class="docx-dialog__button docx-dialog__cancel"
              type="button"
              onClick={cancel}
            >
              {t('common.cancel')}
            </button>
            <button
              data-docx-part="apply"
              class="docx-dialog__button docx-dialog__apply"
              type="button"
              disabled={!isEnabled.value}
              onClick={apply}
            >
              {t('common.apply')}
            </button>
          </div>
        </Fragment>
      );
      return (
        <NativeDialog
          restoreFocus={false}
          sessionSignal={p.session.signal}
          dismissOutside={false}
          kind="textFormField"
          label={t('textFormField.title')}
          onClose={cancel}
          class={p.className}
          style={p.style}
          onKeydown={(e) => {
            if (
              e.key === 'Enter' &&
              !e.isComposing &&
              !(e.target instanceof HTMLButtonElement) &&
              !(e.target instanceof HTMLSelectElement)
            ) {
              e.preventDefault();
              apply();
            }
          }}
          content={() =>
            renderParts(defaults, slots.default?.() ?? (p.children ? [p.children] : []), p.preset)
          }
        />
      );
    };
  },
});
/** Customizable legacy text field options. @public */
export const DocxEditorTextFormFieldDialog = Object.assign(Impl, composition.parts);
