// packages/react/src/editor/toolbar/ContentControlParts.tsx
// Toolbar parts for the `contentControl.*` chrome slots.
//
// Show-all and form-fill are surface toggles: enabled state comes from
// `useEditorCommand` / `toolbarCommandState`; pressed state and the click go through
// `useContentControl` so direct `setShowAll` / `setFormFill` and the toolbar stay aligned.
// They are shaped (not bare `ToolbarButton`) so `aria-pressed` reflects the mode —
// `ToolbarButton` only wires pressed-ness for marks and alignment.
//
// Inspector is adapter-shaped: `runToolbarCommand` only validates a control is at the
// caret; this part opens the shared inspector panel (same pattern as `text.link`).
//
// Remove is a live `ToolbarButton` — can-before-exec and the engine's reason are enough.

import type { ChromeSlotId } from '@docx-editor.dev/core-contract/editor';
import { useEditorCommand } from '../useEditorCommand';
import { useContentControl, CONTENT_CONTROL_SLOTS } from '../useContentControl';
import { useToolbarLabel } from './toolbar-context';
import { Slot } from './Slot';
import { chromeControlForSlot, chromeIcon, guardToolbarMousedown } from './ToolbarButton';
import type { ToolbarPartComponent, ToolbarPartProps } from './parts';

function asSlot(id: string): ChromeSlotId {
  return id as ChromeSlotId;
}

function defineTogglePart(slotId: string, mode: 'showAll' | 'formFill'): ToolbarPartComponent {
  const slot = asSlot(slotId);
  const Part = ({ className, hidden, icon, asChild, children }: ToolbarPartProps) => {
    // Enabled state stays on the command table; pressed state comes from the shared hook so
    // `useContentControl().setShowAll` and the toolbar button cannot drift.
    const { isEnabled, disabledReason } = useEditorCommand(slot);
    const chrome = useContentControl();
    const pressed = mode === 'showAll' ? chrome.showAll : chrome.formFill;
    const label = useToolbarLabel();
    if (hidden) return null;
    const control = chromeControlForSlot(slot);
    const text = label(control?.labelKey ?? slotId);
    const shared = {
      type: 'button' as const,
      className: `docx-toolbar__button${className ? ` ${className}` : ''}`,
      'data-slot': slotId,
      disabled: !isEnabled,
      ...(!isEnabled ? { 'data-disabled': '' } : {}),
      ...(pressed ? { 'data-active': '' } : {}),
      'aria-pressed': pressed,
      'aria-label': text,
      title: disabledReason ?? text,
      onMouseDown: guardToolbarMousedown,
      onClick: () => {
        if (mode === 'showAll') chrome.toggleShowAll();
        else chrome.toggleFormFill();
      },
    };
    if (asChild) return <Slot {...shared}>{children}</Slot>;
    return <button {...shared}>{icon ?? children ?? chromeIcon(control?.paths)}</button>;
  };
  return Object.assign(Part, { docxSlot: slot });
}

function ToolbarContentControlInspectorImpl({
  className,
  hidden,
  icon,
  asChild,
  children,
}: ToolbarPartProps) {
  const slot = asSlot(CONTENT_CONTROL_SLOTS.inspector);
  const { isEnabled, disabledReason } = useEditorCommand(slot);
  const { inspectorOpen, openInspector } = useContentControl();
  const label = useToolbarLabel();
  if (hidden) return null;
  const registry = chromeControlForSlot(slot);
  const text = label(registry?.labelKey ?? 'contentControl.inspector');
  const shared = {
    type: 'button' as const,
    className: `docx-toolbar__button${className ? ` ${className}` : ''}`,
    'data-slot': CONTENT_CONTROL_SLOTS.inspector,
    disabled: !isEnabled,
    ...(!isEnabled ? { 'data-disabled': '' } : {}),
    ...(inspectorOpen ? { 'data-active': '' } : {}),
    'aria-pressed': inspectorOpen,
    'aria-label': text,
    title: disabledReason ?? text,
    onMouseDown: guardToolbarMousedown,
    onClick: () => openInspector(),
  };
  if (asChild) return <Slot {...shared}>{children}</Slot>;
  return <button {...shared}>{icon ?? children ?? chromeIcon(registry?.paths)}</button>;
}

function ToolbarContentControlRemoveImpl({
  className,
  hidden,
  icon,
  asChild,
  children,
}: ToolbarPartProps) {
  const { canRemove, removeDisabledReason, remove } = useContentControl();
  const label = useToolbarLabel();
  if (hidden) return null;
  const slot = asSlot(CONTENT_CONTROL_SLOTS.remove);
  const registry = chromeControlForSlot(slot);
  const text = label(registry?.labelKey ?? 'contentControl.remove');
  const shared = {
    type: 'button' as const,
    className: `docx-toolbar__button${className ? ` ${className}` : ''}`,
    'data-slot': CONTENT_CONTROL_SLOTS.remove,
    disabled: !canRemove,
    ...(!canRemove ? { 'data-disabled': '' } : {}),
    'aria-label': text,
    title: removeDisabledReason ?? text,
    onMouseDown: guardToolbarMousedown,
    onClick: () => {
      remove();
    },
  };
  if (asChild) return <Slot {...shared}>{children}</Slot>;
  return <button {...shared}>{icon ?? children ?? chromeIcon(registry?.paths)}</button>;
}

export const ToolbarContentControlShowAll = defineTogglePart(
  CONTENT_CONTROL_SLOTS.showAll,
  'showAll'
);
export const ToolbarContentControlFormFill = defineTogglePart(
  CONTENT_CONTROL_SLOTS.formFill,
  'formFill'
);
export const ToolbarContentControlRemove: ToolbarPartComponent = Object.assign(
  ToolbarContentControlRemoveImpl,
  { docxSlot: asSlot(CONTENT_CONTROL_SLOTS.remove) }
);
export const ToolbarContentControlInspector: ToolbarPartComponent = Object.assign(
  ToolbarContentControlInspectorImpl,
  { docxSlot: asSlot(CONTENT_CONTROL_SLOTS.inspector) }
);

export const CONTENT_CONTROL_SHAPED_PARTS: Partial<
  Record<
    ChromeSlotId,
    (props: { hidden?: boolean }) => ReturnType<typeof ToolbarContentControlInspectorImpl>
  >
> = {
  [asSlot(CONTENT_CONTROL_SLOTS.showAll)]: ToolbarContentControlShowAll,
  [asSlot(CONTENT_CONTROL_SLOTS.formFill)]: ToolbarContentControlFormFill,
  [asSlot(CONTENT_CONTROL_SLOTS.inspector)]: ToolbarContentControlInspector,
  [asSlot(CONTENT_CONTROL_SLOTS.remove)]: ToolbarContentControlRemove,
};

// packages/vue/src/editor/toolbar/ContentControlParts.tsx
import { defineComponent, h, type PropType, type VNode } from 'vue';
import type { DocxEditorChildren } from '../../docx-editor-children';
import { type ChromeSlotId } from '@docx-editor.dev/core/editor';
import { useEditorCommand } from '../useEditorCommand';
import { useContentControl, CONTENT_CONTROL_SLOTS } from '../useContentControl';
import { useToolbarLabel } from './toolbar-context';
import { Slot } from './Slot';
import { chromeControlForSlot, chromeIcon, guardToolbarMousedown } from './ToolbarButton';
import type { ToolbarPartComponent } from './parts';

function asSlot(id: string): ChromeSlotId {
  return id as ChromeSlotId;
}

function defineTogglePart(slotId: string, mode: 'showAll' | 'formFill'): ToolbarPartComponent {
  const slot = asSlot(slotId);
  const Part = defineComponent({
    name: `ContentControlToggle_${mode}`,
    props: {
      className: { type: String, default: undefined },
      hidden: { type: Boolean, default: undefined },
      icon: { type: Object as PropType<VNode>, default: undefined },
      asChild: { type: Boolean, default: undefined },
    },
    setup(props, { slots }) {
      const command = useEditorCommand(slot);
      const chrome = useContentControl();
      const label = useToolbarLabel();
      return () => {
        if (props.hidden) return null;
        const pressed = mode === 'showAll' ? chrome.showAll.value : chrome.formFill.value;
        const control = chromeControlForSlot(slot);
        const text = label(control?.labelKey ?? slotId);
        const shared = {
          type: 'button',
          class: `docx-toolbar__button${props.className ? ` ${props.className}` : ''}`,
          'data-slot': slotId,
          disabled: !command.isEnabled.value,
          ...(!command.isEnabled.value ? { 'data-disabled': '' } : {}),
          ...(pressed ? { 'data-active': '' } : {}),
          'aria-pressed': pressed,
          'aria-label': text,
          title: command.disabledReason.value ?? text,
          onMousedown: guardToolbarMousedown,
          onClick: () => {
            if (mode === 'showAll') chrome.toggleShowAll();
            else chrome.toggleFormFill();
          },
        };
        const content = props.icon ?? slots.default?.() ?? chromeIcon(control?.paths);
        if (props.asChild) return h(Slot, shared, slots.default);
        return h('button', shared, content ?? undefined);
      };
    },
  });
  (Part as unknown as ToolbarPartComponent).docxSlot = slot;
  return Part as unknown as ToolbarPartComponent;
}

/** @public */
export const ToolbarContentControlShowAll = defineTogglePart(
  CONTENT_CONTROL_SLOTS.showAll,
  'showAll'
);
/** @public */
export const ToolbarContentControlFormFill = defineTogglePart(
  CONTENT_CONTROL_SLOTS.formFill,
  'formFill'
);

/** @public */
export const ToolbarContentControlInspector = defineComponent({
  name: 'ToolbarContentControlInspector',
  props: {
    className: { type: String, default: undefined },
    hidden: { type: Boolean, default: undefined },
    icon: { type: Object as PropType<VNode>, default: undefined },
    asChild: { type: Boolean, default: undefined },
  },
  setup(props, { slots }) {
    const slot = asSlot(CONTENT_CONTROL_SLOTS.inspector);
    const command = useEditorCommand(slot);
    const { inspectorOpen, openInspector } = useContentControl();
    const label = useToolbarLabel();
    return () => {
      if (props.hidden) return null;
      const registry = chromeControlForSlot(slot);
      const text = label(registry?.labelKey ?? 'contentControl.inspector');
      const shared = {
        type: 'button',
        class: `docx-toolbar__button${props.className ? ` ${props.className}` : ''}`,
        'data-slot': CONTENT_CONTROL_SLOTS.inspector,
        disabled: !command.isEnabled.value,
        ...(!command.isEnabled.value ? { 'data-disabled': '' } : {}),
        ...(inspectorOpen.value ? { 'data-active': '' } : {}),
        'aria-pressed': inspectorOpen.value,
        'aria-label': text,
        title: command.disabledReason.value ?? text,
        onMousedown: guardToolbarMousedown,
        onClick: () => openInspector(),
      };
      const content = props.icon ?? slots.default?.() ?? chromeIcon(registry?.paths);
      if (props.asChild) return h(Slot, shared, slots.default);
      return h('button', shared, content ?? undefined);
    };
  },
}) as unknown as ToolbarPartComponent;

(ToolbarContentControlInspector as unknown as ToolbarPartComponent).docxSlot = asSlot(
  CONTENT_CONTROL_SLOTS.inspector
);

/** @public */
export const ToolbarContentControlRemove = defineComponent({
  name: 'ToolbarContentControlRemove',
  props: {
    className: { type: String, default: undefined },
    hidden: { type: Boolean, default: undefined },
    icon: { type: Object as PropType<VNode>, default: undefined },
    asChild: { type: Boolean, default: undefined },
  },
  setup(props, { slots }) {
    const { canRemove, removeDisabledReason, remove } = useContentControl();
    const label = useToolbarLabel();
    return () => {
      if (props.hidden) return null;
      const slot = asSlot(CONTENT_CONTROL_SLOTS.remove);
      const registry = chromeControlForSlot(slot);
      const text = label(registry?.labelKey ?? 'contentControl.remove');
      const shared = {
        type: 'button',
        class: `docx-toolbar__button${props.className ? ` ${props.className}` : ''}`,
        'data-slot': CONTENT_CONTROL_SLOTS.remove,
        disabled: !canRemove.value,
        ...(!canRemove.value ? { 'data-disabled': '' } : {}),
        'aria-label': text,
        title: removeDisabledReason.value ?? text,
        onMousedown: guardToolbarMousedown,
        onClick: () => remove(),
      };
      const content = props.icon ?? slots.default?.() ?? chromeIcon(registry?.paths);
      if (props.asChild) return h(Slot, shared, slots.default);
      return h('button', shared, content ?? undefined);
    };
  },
}) as unknown as ToolbarPartComponent;

(ToolbarContentControlRemove as unknown as ToolbarPartComponent).docxSlot = asSlot(
  CONTENT_CONTROL_SLOTS.remove
);

export const CONTENT_CONTROL_SHAPED_PARTS: Partial<
  Record<ChromeSlotId, (props: { hidden?: boolean }) => DocxEditorChildren | null>
> = {
  [asSlot(CONTENT_CONTROL_SLOTS.showAll)]: ToolbarContentControlShowAll,
  [asSlot(CONTENT_CONTROL_SLOTS.formFill)]: ToolbarContentControlFormFill,
  [asSlot(CONTENT_CONTROL_SLOTS.inspector)]: ToolbarContentControlInspector,
  [asSlot(CONTENT_CONTROL_SLOTS.remove)]: ToolbarContentControlRemove,
};
