// packages/react/src/editor/toolbar/Reviewers.tsx
// Word for Mac's Review > Markup Options > Reviewers menu.

import { useCallback, useEffect, useRef, useState } from 'react';
import type { DocxEditorChildren } from '../../docx-editor-children';
import { localizeDisabledReason } from '@docx-editor.dev/i18n';
import { toolbarCommandState } from '@docx-editor.dev/core/editor';
import type { EditorSnapshot } from '@docx-editor.dev/core/contracts/editor';
import { useTranslation } from '../../i18n';
import { useDocxEditor } from '../context';
import { useEditorState } from '../useEditorState';
import { useReviewAuthors } from '../useReviewAuthors';
import { useToolbarLabel } from './toolbar-context';
import { chromeControlForSlot, chromeIcon, guardToolbarMousedown } from './ToolbarButton';
import { usePopupEscape } from './usePopupEscape';

const selectHiddenAuthors = (snapshot: EditorSnapshot): readonly string[] =>
  snapshot.hiddenReviewAuthors ?? [];

/** Props for `DocxEditor.Toolbar.Reviewers`. @public */
export type ToolbarReviewersProps = {
  className?: string;
  hidden?: boolean;
  /** Custom trigger icon. */
  icon?: DocxEditorChildren;
};

/** The reviewer visibility menu. It changes view state only. @public */
export function ToolbarReviewers({ className, hidden, icon }: ToolbarReviewersProps) {
  const editor = useDocxEditor();
  const authors = useReviewAuthors();
  const hiddenAuthors = useEditorState(selectHiddenAuthors);
  const hiddenSet = new Set(hiddenAuthors);
  const allVisible = authors.every((info) => !hiddenSet.has(info.author));
  const [open, setOpen] = useState(false);
  const rootRef = useRef<HTMLDivElement | null>(null);
  const triggerRef = useRef<HTMLButtonElement | null>(null);
  const menuRef = useRef<HTMLDivElement | null>(null);
  const label = useToolbarLabel();
  const { t } = useTranslation();

  useEffect(() => {
    if (!open) return undefined;
    menuRef.current?.querySelector<HTMLButtonElement>('[role="menuitemcheckbox"]')?.focus();
    const onMouseDown = (event: MouseEvent): void => {
      if (rootRef.current?.contains(event.target as Node)) return;
      setOpen(false);
    };
    document.addEventListener('mousedown', onMouseDown, true);
    return () => {
      document.removeEventListener('mousedown', onMouseDown, true);
    };
  }, [open]);
  // Escape through the shared rule: a host input keeps its own Escape.
  usePopupEscape(open, rootRef, (fromInside) => {
    setOpen(false);
    if (fromInside) triggerRef.current?.focus();
  });

  const onMenuKeyDown = useCallback((event: React.KeyboardEvent): void => {
    const items = [
      ...(menuRef.current?.querySelectorAll<HTMLButtonElement>('[role="menuitemcheckbox"]') ?? []),
    ];
    const at = items.indexOf(document.activeElement as HTMLButtonElement);
    const move = (to: number): void => {
      event.preventDefault();
      items[(to + items.length) % items.length]?.focus();
    };
    if (event.key === 'ArrowDown') move(at + 1);
    else if (event.key === 'ArrowUp') move(at - 1);
    else if (event.key === 'Home') move(0);
    else if (event.key === 'End') move(items.length - 1);
    else if (event.key === 'Tab') setOpen(false);
  }, []);

  if (hidden) return null;
  const control = chromeControlForSlot('review.authors');
  const state = toolbarCommandState(editor, 'review.authors');
  const disabledReason = localizeDisabledReason(state.disabledReason, t);
  const text = label(control?.labelKey ?? 'reviewers.label');
  return (
    <div
      ref={rootRef}
      className={`docx-toolbar__reviewers${className ? ` ${className}` : ''}`}
      data-slot="review.authors"
    >
      <button
        ref={triggerRef}
        type="button"
        className="docx-toolbar__picker"
        data-testid="reviewers-trigger"
        aria-haspopup="menu"
        aria-expanded={open}
        aria-label={text}
        disabled={!state.enabled}
        title={disabledReason ?? text}
        onMouseDown={guardToolbarMousedown}
        onClick={() => setOpen((value) => !value)}
      >
        {icon ?? chromeIcon(control?.paths)}
        <span className="docx-toolbar__picker-value">{text}</span>
        <span className="docx-toolbar__picker-caret" aria-hidden="true">
          ▾
        </span>
      </button>
      {open ? (
        <div
          ref={menuRef}
          className="docx-toolbar__reviewers-menu"
          role="menu"
          aria-label={text}
          data-testid="reviewers-menu"
          onKeyDown={onMenuKeyDown}
        >
          <ReviewerRow
            checked={allVisible}
            label={t('reviewers.all')}
            testId="reviewer-all"
            onChoose={() => editor?.setAllReviewAuthorsVisible(!allVisible)}
          />
          <div className="docx-toolbar__menu-separator" role="separator" />
          {authors.map((info) => (
            <ReviewerRow
              key={info.author}
              checked={!hiddenSet.has(info.author)}
              label={info.author || '—'}
              testId={`reviewer-${info.slot}`}
              color={info.color}
              onChoose={() =>
                editor?.setReviewAuthorVisible(info.author, hiddenSet.has(info.author))
              }
            />
          ))}
        </div>
      ) : null}
    </div>
  );
}
ToolbarReviewers.docxSlot = 'review.authors' as const;

function ReviewerRow(props: {
  checked: boolean;
  label: string;
  testId: string;
  color?: string;
  onChoose: () => void;
}) {
  return (
    <button
      type="button"
      role="menuitemcheckbox"
      aria-checked={props.checked}
      className="docx-toolbar__reviewer-item"
      data-testid={props.testId}
      onMouseDown={guardToolbarMousedown}
      onClick={props.onChoose}
    >
      <span className="docx-toolbar__menu-check" aria-hidden="true">
        {props.checked ? '✓' : ''}
      </span>
      {props.color ? (
        <span className="docx-toolbar__reviewer-swatch" style={{ background: props.color }} />
      ) : null}
      <span className="docx-toolbar__reviewer-name">{props.label}</span>
    </button>
  );
}

// packages/vue/src/editor/toolbar/Reviewers.tsx
import { computed, defineComponent, nextTick, ref, watch, type PropType } from 'vue';
import type { DocxEditorChildren } from '../../docx-editor-children';
import type { EditorSnapshot } from '@docx-editor.dev/core/contracts/editor';
import { localizeDisabledReason } from '@docx-editor.dev/i18n';
import { toolbarCommandState } from '@docx-editor.dev/core/editor';
import { useTranslation } from '../../i18n';
import { useDocxEditor } from '../context';
import { useEditorState } from '../useEditorState';
import { useReviewAuthors } from '../useReviewAuthors';
import { useToolbarLabel } from './toolbar-context';
import { chromeControlForSlot, chromeIcon, guardToolbarMousedown } from './ToolbarButton';
import { usePopupEscape } from './usePopupEscape';

const selectHiddenAuthors = (snapshot: EditorSnapshot): readonly string[] =>
  snapshot.hiddenReviewAuthors ?? [];

/** @public */
export type ToolbarReviewersProps = {
  className?: string;
  hidden?: boolean;
  icon?: DocxEditorChildren;
};

/** Word for Mac's reviewer visibility menu. It changes view state only. @public */
export const ToolbarReviewers = Object.assign(
  defineComponent({
    name: 'ToolbarReviewers',
    props: {
      className: { type: String, default: undefined },
      hidden: { type: Boolean, default: undefined },
      icon: { type: Object as PropType<DocxEditorChildren>, default: undefined },
    },
    setup(props, { slots }) {
      const editorRef = useDocxEditor();
      const authors = useReviewAuthors();
      const hiddenAuthors = useEditorState(selectHiddenAuthors);
      const hiddenSet = computed(() => new Set(hiddenAuthors.value));
      const open = ref(false);
      const rootRef = ref<HTMLDivElement | null>(null);
      const triggerRef = ref<HTMLButtonElement | null>(null);
      const menuRef = ref<HTMLDivElement | null>(null);
      const label = useToolbarLabel();
      const { t } = useTranslation();

      watch(
        open,
        (isOpen, _, onCleanup) => {
          if (!isOpen) return;
          menuRef.value?.querySelector<HTMLButtonElement>('[role="menuitemcheckbox"]')?.focus();
          const onMouseDown = (event: MouseEvent) => {
            if (rootRef.value?.contains(event.target as Node)) return;
            open.value = false;
          };
          document.addEventListener('mousedown', onMouseDown, true);
          onCleanup(() => {
            document.removeEventListener('mousedown', onMouseDown, true);
          });
        },
        { flush: 'post' }
      );
      // Escape through the shared rule: a host input keeps its own Escape.
      usePopupEscape(
        () => open.value,
        rootRef,
        (fromInside) => {
          open.value = false;
          if (fromInside) void nextTick(() => triggerRef.value?.focus());
        }
      );

      const onMenuKeyDown = (event: KeyboardEvent) => {
        const items = [
          ...(menuRef.value?.querySelectorAll<HTMLButtonElement>('[role="menuitemcheckbox"]') ??
            []),
        ];
        const at = items.indexOf(document.activeElement as HTMLButtonElement);
        const move = (to: number) => {
          event.preventDefault();
          items[(to + items.length) % items.length]?.focus();
        };
        if (event.key === 'ArrowDown') move(at + 1);
        else if (event.key === 'ArrowUp') move(at - 1);
        else if (event.key === 'Home') move(0);
        else if (event.key === 'End') move(items.length - 1);
        else if (event.key === 'Tab') open.value = false;
      };

      return () => {
        if (props.hidden) return null;
        const reviewerAuthors = authors.value;
        const control = chromeControlForSlot('review.authors');
        const state = toolbarCommandState(editorRef.value, 'review.authors');
        const disabledReason = localizeDisabledReason(state.disabledReason, t);
        const text = label(control?.labelKey ?? 'reviewers.label');
        return (
          <div
            ref={rootRef}
            class={`docx-toolbar__reviewers${props.className ? ` ${props.className}` : ''}`}
            data-slot="review.authors"
          >
            <button
              ref={triggerRef}
              type="button"
              class="docx-toolbar__picker"
              data-testid="reviewers-trigger"
              aria-haspopup="menu"
              aria-expanded={open.value}
              aria-label={text}
              disabled={!state.enabled}
              title={disabledReason ?? text}
              onMousedown={guardToolbarMousedown}
              onClick={() => {
                open.value = !open.value;
              }}
            >
              {props.icon ?? slots.default?.() ?? chromeIcon(control?.paths)}
              <span class="docx-toolbar__picker-value">{text}</span>
              <span class="docx-toolbar__picker-caret" aria-hidden="true">
                ▾
              </span>
            </button>
            {open.value ? (
              <div
                ref={menuRef}
                class="docx-toolbar__reviewers-menu"
                role="menu"
                aria-label={text}
                data-testid="reviewers-menu"
                onKeydown={onMenuKeyDown}
              >
                <ReviewerRow
                  checked={reviewerAuthors.every((info) => !hiddenSet.value.has(info.author))}
                  label={t('reviewers.all')}
                  testId="reviewer-all"
                  onChoose={() =>
                    editorRef.value?.setAllReviewAuthorsVisible(
                      !reviewerAuthors.every((info) => !hiddenSet.value.has(info.author))
                    )
                  }
                />
                <div class="docx-toolbar__menu-separator" role="separator" />
                {reviewerAuthors.map((info) => (
                  <ReviewerRow
                    key={info.author}
                    checked={!hiddenSet.value.has(info.author)}
                    label={info.author || '—'}
                    testId={`reviewer-${info.slot}`}
                    color={info.color}
                    onChoose={() =>
                      editorRef.value?.setReviewAuthorVisible(
                        info.author,
                        hiddenSet.value.has(info.author)
                      )
                    }
                  />
                ))}
              </div>
            ) : null}
          </div>
        );
      };
    },
  }),
  { docxSlot: 'review.authors' as const }
);

const ReviewerRow = defineComponent({
  name: 'ReviewerRow',
  props: {
    checked: { type: Boolean, required: true },
    label: { type: String, required: true },
    testId: { type: String, required: true },
    color: { type: String, default: undefined },
    onChoose: { type: Function as PropType<() => void>, required: true },
  },
  setup(props) {
    return () => (
      <button
        type="button"
        role="menuitemcheckbox"
        aria-checked={props.checked}
        class="docx-toolbar__reviewer-item"
        data-testid={props.testId}
        onMousedown={guardToolbarMousedown}
        onClick={props.onChoose}
      >
        <span class="docx-toolbar__menu-check" aria-hidden="true">
          {props.checked ? '✓' : ''}
        </span>
        {props.color ? (
          <span class="docx-toolbar__reviewer-swatch" style={{ background: props.color }} />
        ) : null}
        <span class="docx-toolbar__reviewer-name">{props.label}</span>
      </button>
    );
  },
});
