// packages/vue/src/editor/menu/MenuExportDialog.tsx
import { defineComponent, type PropType } from 'vue';
import type { ChromeExportFormat } from '@docx-editor.dev/core/editor';
import { useTranslation } from '../../i18n';
import { NativeDialog } from '../dialog-parts';

/** Export progress stays outside the menu's layout and keyboard navigation. */
export const MenuExportDialog = defineComponent({
  name: 'MenuExportDialog',
  props: {
    format: { type: String as PropType<ChromeExportFormat>, required: true },
    error: { type: String, required: true },
    onClose: { type: Function as PropType<() => void>, required: true },
  },
  setup(props) {
    const { t } = useTranslation();
    return () => {
      const title = props.error
        ? t(props.format === 'pdf' ? 'toolbar.exportPdfFailed' : 'toolbar.exportMarkdownFailed')
        : t(props.format === 'pdf' ? 'toolbar.exportingPdf' : 'toolbar.exportingMarkdown');
      return (
        <NativeDialog
          kind="export"
          label={title}
          role={props.error ? 'alertdialog' : 'dialog'}
          class="docx-export-dialog"
          dismissOutside={false}
          onClose={props.onClose}
          content={() => (
            <>
              <header class="docx-dialog__header">
                <h2 class="docx-dialog__title docx-export-dialog__title">
                  {!props.error && <span class="docx-export-dialog__spinner" aria-hidden="true" />}
                  {title}
                </h2>
              </header>
              <div class="docx-dialog__body">
                <p class="docx-export-dialog__message" role={props.error ? 'alert' : 'status'}>
                  {props.error || t('toolbar.exportDownloadHint')}
                </p>
              </div>
              <footer class="docx-dialog__footer">
                <button type="button" class="docx-dialog__button" onClick={props.onClose}>
                  {t(props.error ? 'common.close' : 'toolbar.exportContinueEditing')}
                </button>
              </footer>
            </>
          )}
        />
      );
    };
  },
});

// packages/react/src/editor/menu/MenuExportDialog.tsx
import type { ChromeExportFormat } from '@docx-editor.dev/core/editor';
import { useTranslation } from '../../i18n';
import { DialogFrame } from '../dialog-parts';

/** Export progress stays outside the menu's layout and keyboard navigation. */
export function MenuExportDialog({
  format,
  error,
  onClose,
}: {
  format: ChromeExportFormat;
  error: string;
  onClose(): void;
}) {
  const { t } = useTranslation();
  const title = error
    ? t(format === 'pdf' ? 'toolbar.exportPdfFailed' : 'toolbar.exportMarkdownFailed')
    : t(format === 'pdf' ? 'toolbar.exportingPdf' : 'toolbar.exportingMarkdown');
  return (
    <DialogFrame
      kind="export"
      label={title}
      role={error ? 'alertdialog' : 'dialog'}
      className="docx-export-dialog"
      dismissOutside={false}
      onClose={onClose}
    >
      <header className="docx-dialog__header">
        <h2 className="docx-dialog__title docx-export-dialog__title">
          {!error && <span className="docx-export-dialog__spinner" aria-hidden="true" />}
          {title}
        </h2>
      </header>
      <div className="docx-dialog__body">
        <p className="docx-export-dialog__message" role={error ? 'alert' : 'status'}>
          {error || t('toolbar.exportDownloadHint')}
        </p>
      </div>
      <footer className="docx-dialog__footer">
        <button type="button" className="docx-dialog__button" onClick={onClose}>
          {t(error ? 'common.close' : 'toolbar.exportContinueEditing')}
        </button>
      </footer>
    </DialogFrame>
  );
}
