// packages/vue/src/editor/navigation/DocxEditorNavigation.tsx
import {
  computed,
  defineComponent,
  provide,
  type CSSProperties,
  type PropType,
  type VNode,
} from 'vue';
import type { DocxEditorChildren } from '../../docx-editor-children';
import { useFormControlTranslate } from '../form-control-translate';
import { useScopeClassName } from '../scope-context';
import { NavigationContext, type NavigationContextValue } from './navigation-context';
import { NAVIGATION_PANE_INSET, navigationPaneReservation } from './navigation-geometry';
import { useDocumentOutline } from './useDocumentOutline';
import { useDocumentSearch, type DocumentSearchHighlight } from './useDocumentSearch';
import { useNavigationFocus } from './useNavigationFocus';
import { useNavigationPane, type UseNavigationPaneOptions } from './useNavigationPane';
import type { NavigationPartProps } from './parts';
import {
  NavigationClose,
  NavigationFind,
  NavigationHeader,
  NavigationHeadings,
  NavigationTab,
  NavigationTabs,
  NavigationTitle,
  NavigationToggle,
} from './parts';

/** Props for `DocxEditor.Navigation`. @public */
export interface DocxEditorNavigationProps extends UseNavigationPaneOptions {
  /**
   * Label resolver. Defaults to the `translate` given to `DocxEditorRoot`, and for keys it
   * leaves unresolved, to the active locale catalogue.
   */
  t?: (key: string, params?: Record<string, string | number>) => string;
  toggle?: boolean | NavigationPartProps;
  /**
   * Which Find matches to highlight while the Find tab is open: `'all'` (default),
   * `'active'`, or `'none'`. The pane stops requesting highlights when it closes or leaves the
   * tab; another `useDocumentSearch` consumer can still request them.
   */
  searchHighlight?: DocumentSearchHighlight;
  /**
   * Whether Ctrl+F (Cmd+F on macOS) opens the pane on the Find tab. Defaults to `true`. The
   * shortcut applies only while focus is in this editor, so the rest of the page keeps the
   * browser's own search. Set `false` to leave the shortcut to the browser everywhere.
   */
  findShortcut?: boolean;
  className?: string;
  style?: CSSProperties;
  children?: DocxEditorChildren;
}

/** @public */
export interface DocxEditorNavigationNamespace {
  (props: DocxEditorNavigationProps): VNode;
  readonly Header: typeof NavigationHeader;
  readonly Close: typeof NavigationClose;
  readonly Title: typeof NavigationTitle;
  readonly Tabs: typeof NavigationTabs;
  readonly Tab: typeof NavigationTab;
  readonly Headings: typeof NavigationHeadings;
  readonly Find: typeof NavigationFind;
  readonly Toggle: typeof NavigationToggle;
}

const DocxEditorNavigationImpl = defineComponent({
  name: 'DocxEditorNavigation',
  props: {
    t: { type: Function as PropType<DocxEditorNavigationProps['t']>, default: undefined },
    toggle: { type: [Boolean, Object] as PropType<boolean | NavigationPartProps>, default: true },
    searchHighlight: { type: String as PropType<DocumentSearchHighlight>, default: 'all' },
    findShortcut: { type: Boolean, default: true },
    className: { type: String, default: undefined },
    style: { type: Object as PropType<CSSProperties>, default: undefined },
    paneWidth: { type: Number, default: undefined },
    defaultOpen: { type: Boolean, default: undefined },
    defaultTab: { type: String as PropType<'headings' | 'find'>, default: undefined },
    open: { type: Boolean, default: undefined },
    tab: { type: String as PropType<'headings' | 'find'>, default: undefined },
    onOpenChange: { type: Function as PropType<(open: boolean) => void>, default: undefined },
    onTabChange: {
      type: Function as PropType<(tab: 'headings' | 'find') => void>,
      default: undefined,
    },
  },
  setup(props, { slots }) {
    const scope = useScopeClassName();
    const paneOptions = (): UseNavigationPaneOptions => ({
      ...(props.paneWidth !== undefined ? { paneWidth: props.paneWidth } : {}),
      ...(props.defaultOpen !== undefined ? { defaultOpen: props.defaultOpen } : {}),
      ...(props.defaultTab !== undefined ? { defaultTab: props.defaultTab } : {}),
      ...(props.open !== undefined ? { open: props.open } : {}),
      ...(props.tab !== undefined ? { tab: props.tab } : {}),
      ...(props.onOpenChange ? { onOpenChange: props.onOpenChange } : {}),
      ...(props.onTabChange ? { onTabChange: props.onTabChange } : {}),
    });
    const pane = useNavigationPane(paneOptions);
    const outline = useDocumentOutline();
    const search = useDocumentSearch(() => ({
      highlight: pane.open.value && pane.tab.value === 'find' ? props.searchHighlight : 'none',
    }));
    // The host's resolver, else the one `DocxEditorRoot` was given, else the catalogue.
    const rootT = useFormControlTranslate();
    const focus = useNavigationFocus(pane, () => props.findShortcut);
    const value = computed(() => ({
      pane,
      outline,
      search,
      t: props.t ?? rootT,
      intents: focus.intents,
      findShortcut: props.findShortcut,
    }));
    provide(NavigationContext, value as unknown as NavigationContextValue);
    const width = computed(() => pane.paneWidth.value);

    return () => (
      <div
        ref={focus.rootRef}
        class={`${scope}docx-nav${pane.open.value ? ' docx-nav--open' : ''}${pane.overlay.value ? ' docx-nav--overlay' : ''}${props.className ? ` ${props.className}` : ''}`}
        data-open={pane.open.value ? 'true' : 'false'}
        onKeydown={focus.onKeyDown}
        style={{
          '--docx-nav-width': `${width.value}px`,
          '--docx-nav-inset': `${NAVIGATION_PANE_INSET}px`,
          '--docx-nav-reservation': `${navigationPaneReservation(width.value)}px`,
          ...props.style,
        }}
      >
        {props.toggle !== false && !pane.open.value && (
          <NavigationToggle {...(typeof props.toggle === 'object' ? props.toggle : {})} />
        )}
        <aside
          class="docx-nav__panel-shell"
          aria-label={value.value.t('navigation.ariaLabel')}
          inert={!pane.open.value}
        >
          {slots.default?.() ?? (
            <>
              <NavigationHeader />
              <NavigationTabs />
              <NavigationHeadings />
              <NavigationFind />
            </>
          )}
        </aside>
      </div>
    );
  },
});

/** @public */
export const DocxEditorNavigation = Object.assign(DocxEditorNavigationImpl, {
  Header: NavigationHeader,
  Close: NavigationClose,
  Title: NavigationTitle,
  Tabs: NavigationTabs,
  Tab: NavigationTab,
  Headings: NavigationHeadings,
  Find: NavigationFind,
  Toggle: NavigationToggle,
}) as unknown as DocxEditorNavigationNamespace;

/** Alias matching React export name. */
export const Navigation = DocxEditorNavigation;

export {
  NavigationClose,
  NavigationFind,
  NavigationHeader,
  NavigationHeadings,
  NavigationTab,
  NavigationTabs,
  NavigationTitle,
  NavigationToggle,
};

export type { NavigationPartProps, NavigationTabProps } from './parts';

// packages/react/src/editor/navigation/DocxEditorNavigation.tsx
import type { DocxEditorChildren } from '../../docx-editor-children';
// The navigation pane: `DocxEditor.Navigation`.
//
// `<DocxEditor.Navigation />` on its own is the whole thing — a collapsed disc button that
// expands into a Headings/Find pane over the document's left gutter. Children replace the
// default composition part by part, and the three hooks behind it (`useNavigationPane`,
// `useDocumentOutline`, `useDocumentSearch`) are the escape hatch for a pane that shares
// none of this markup.
//
// THE PANE FLOATS; IT DOES NOT DOCK. It is absolutely positioned over the gutter to the
// left of the centred page, so opening it moves nothing as long as the gutter is wide
// enough to hold it. Only when the window is too narrow does it publish a shift, and only
// as much as it needs — see `navigation-geometry.ts`. That is the difference between the
// document sitting still and the document lurching sideways every time you open the pane.
//
// It stays MOUNTED when closed (width animates to zero, `inert` and `visibility` take it
// out of the tab order and hit testing), so a typed query and a scrolled heading list
// survive a close and reopen.
//
// WHERE IT MAY SIT. Beside `DocxEditor.Viewport` in a positioned box (the packaged frame),
// or as a direct child of the Viewport itself. The Viewport is the scroller, so a pane in it
// would scroll away with the pages; the stylesheet makes that pane sticky instead, and this
// component publishes the viewport's size for it (see `useNavigationFocus`).
//
// KEYBOARD. Ctrl/Cmd+F opens the pane on Find while focus is in this editor, opening moves
// focus into the pane, and Escape or the close arrow returns it to whatever opened it.

import { useMemo } from 'react';
import type { CSSProperties, ReactElement } from 'react';
import { useFormControlTranslate } from '../form-control-translate';
import { NavigationContext } from './navigation-context';
import {
  NAVIGATION_PANE_INSET,
  NAVIGATION_PANE_WIDTH,
  navigationPaneReservation,
} from './navigation-geometry';
import { useDocumentOutline } from './useDocumentOutline';
import { useDocumentSearch, type DocumentSearchHighlight } from './useDocumentSearch';
import { useNavigationFocus } from './useNavigationFocus';
import { useNavigationPane, type UseNavigationPaneOptions } from './useNavigationPane';
import type { NavigationPartProps } from './parts';
import {
  NavigationClose,
  NavigationFind,
  NavigationHeader,
  NavigationHeadings,
  NavigationTab,
  NavigationTabs,
  NavigationTitle,
  NavigationToggle,
} from './parts';
import { useScopeClassName } from '../scope-context';

/** Props for `DocxEditor.Navigation`. @public */
export interface DocxEditorNavigationProps extends UseNavigationPaneOptions {
  /**
   * Label resolver. Defaults to the `translate` given to `DocxEditor.Root`, and for keys it
   * leaves unresolved, to the active `LocaleContext` catalogue (bundled English unless a
   * provider swapped it).
   */
  t?: (key: string, params?: Record<string, string | number>) => string;
  /**
   * The collapsed disc button. `false` removes it; an OBJECT is props for the packaged one,
   * so a host can give it a class without restyling the library's.
   *
   * It is a prop rather than something you compose through `children` because the disc is
   * rendered OUTSIDE the panel: the panel is `inert` while the pane is shut, which is
   * exactly when the disc has to be clickable.
   */
  toggle?: boolean | NavigationPartProps;
  /**
   * Which Find matches to highlight while the Find tab is open: `'all'` (default),
   * `'active'`, or `'none'`. The pane stops requesting highlights when it closes or leaves the
   * tab; another `useDocumentSearch` consumer can still request them.
   */
  searchHighlight?: DocumentSearchHighlight;
  /**
   * Whether Ctrl+F (Cmd+F on macOS) opens the pane on the Find tab. Defaults to `true`. The
   * shortcut applies only while focus is in this editor, so the rest of the page keeps the
   * browser's own search. Set `false` to leave the shortcut to the browser everywhere.
   */
  findShortcut?: boolean;
  className?: string;
  style?: CSSProperties;
  /** Replaces the default composition (header, tabs, both panels). */
  children?: DocxEditorChildren;
}

/**
 * The document navigation pane — headings and find — over the left gutter.
 *
 * @public
 */
export function DocxEditorNavigation(props: DocxEditorNavigationProps): ReactElement {
  // Skip the scope class when the packaged wrapper already carries it.
  const scopeClassName = useScopeClassName();
  const {
    t: hostT,
    toggle = true,
    searchHighlight = 'all',
    findShortcut = true,
    className,
    style,
    children,
    ...paneOptions
  } = props;

  const pane = useNavigationPane(paneOptions);
  const outline = useDocumentOutline();
  // Matches are marked only while the Find tab is on screen.
  const highlight = pane.open && pane.tab === 'find' ? searchHighlight : 'none';
  const search = useDocumentSearch({ highlight });

  // The host's resolver, else the one `DocxEditor.Root` was given, else the active
  // catalogue. A host that passed `translate` only to Root used to get an English pane.
  // The cast bridges the two signatures — `TFunction` is keyed by the union derived from
  // `en.json`, the prop takes a plain string so a host can supply any resolver — and every
  // key this subtree passes is a real catalogue key.
  const rootT = useFormControlTranslate();
  const t = useMemo(
    () =>
      hostT ??
      ((key: string, params?: Record<string, string | number>) =>
        rootT(key as Parameters<typeof rootT>[0], params)),
    [hostT, rootT]
  );

  const focus = useNavigationFocus(pane, findShortcut);
  const value = useMemo(
    () => ({ pane, outline, search, t, intents: focus.intents }),
    [pane, outline, search, t, focus.intents]
  );

  const width = props.paneWidth ?? NAVIGATION_PANE_WIDTH;

  return (
    <NavigationContext.Provider value={value}>
      <div
        ref={focus.rootRef}
        className={`${scopeClassName}docx-nav${pane.open ? ' docx-nav--open' : ''}${pane.overlay ? ' docx-nav--overlay' : ''}${className ? ` ${className}` : ''}`}
        data-open={pane.open ? 'true' : 'false'}
        onKeyDown={focus.onKeyDown}
        style={
          {
            // Numbers this component owns, not file data: safe as computed inline values.
            '--docx-nav-width': `${width}px`,
            '--docx-nav-inset': `${NAVIGATION_PANE_INSET}px`,
            '--docx-nav-reservation': `${navigationPaneReservation(width)}px`,
            ...style,
          } as CSSProperties
        }
      >
        {toggle !== false && !pane.open && (
          <NavigationToggle {...(typeof toggle === 'object' ? toggle : {})} />
        )}
        <aside
          className="docx-nav__panel-shell"
          aria-label={value.t('navigation.ariaLabel')}
          // Closed but mounted: `inert` removes it from tab order and hit testing without
          // unmounting, so the query and scroll position survive a close/reopen.
          inert={!pane.open}
        >
          {children ?? (
            <>
              <NavigationHeader />
              <NavigationTabs />
              <NavigationHeadings />
              <NavigationFind />
            </>
          )}
        </aside>
      </div>
    </NavigationContext.Provider>
  );
}

/**
 * `DocxEditor.Navigation` with its parts attached as statics.
 *
 * @public
 */
export interface DocxEditorNavigationNamespace {
  (props: DocxEditorNavigationProps): ReactElement;
  readonly Header: typeof NavigationHeader;
  readonly Close: typeof NavigationClose;
  readonly Title: typeof NavigationTitle;
  readonly Tabs: typeof NavigationTabs;
  readonly Tab: typeof NavigationTab;
  readonly Headings: typeof NavigationHeadings;
  readonly Find: typeof NavigationFind;
  readonly Toggle: typeof NavigationToggle;
}

export const Navigation: DocxEditorNavigationNamespace = Object.assign(DocxEditorNavigation, {
  Header: NavigationHeader,
  Close: NavigationClose,
  Title: NavigationTitle,
  Tabs: NavigationTabs,
  Tab: NavigationTab,
  Headings: NavigationHeadings,
  Find: NavigationFind,
  Toggle: NavigationToggle,
});
