// packages/vue/src/components/DocumentOutline.vue
<template>
  <div v-if="isOpen" class="doc-outline">
    <div class="doc-outline__header">
      <button class="doc-outline__back" @click="$emit('close')">←</button>
      <span class="doc-outline__title">Document Outline</span>
    </div>
    <div class="doc-outline__body">
      <div v-if="headings.length === 0" class="doc-outline__empty">
        No headings found
      </div>
      <button
        v-for="(h, i) in headings"
        :key="i"
        class="doc-outline__item"
        :style="{ paddingLeft: (12 + h.level * 16) + 'px' }"
        @mousedown.prevent="$emit('navigate', h.pmPos)"
      >{{ h.text || '(untitled)' }}</button>
    </div>
  </div>
</template>

<script setup lang="ts">
import type { HeadingInfo } from '@eigenpal/docx-core/utils/headingCollector';

defineProps<{
  isOpen: boolean;
  headings: HeadingInfo[];
}>();

defineEmits<{
  (e: 'close'): void;
  (e: 'navigate', pmPos: number): void;
}>();
</script>

<style scoped>
.doc-outline {
  position: absolute;
  left: 0;
  top: 0;
  bottom: 0;
  width: 240px;
  background: #fff;
  border-right: 1px solid #e2e8f0;
  z-index: 50;
  display: flex;
  flex-direction: column;
  box-shadow: 2px 0 8px rgba(0,0,0,0.08);
  animation: slideIn 0.15s ease-out;
}
@keyframes slideIn {
  from { transform: translateX(-100%); }
  to { transform: translateX(0); }
}
.doc-outline__header {
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 10px 12px;
  border-bottom: 1px solid #e5e7eb;
}
.doc-outline__back {
  border: none;
  background: transparent;
  cursor: pointer;
  font-size: 16px;
  color: #6b7280;
  width: 28px;
  height: 28px;
  display: flex;
  align-items: center;
  justify-content: center;
  border-radius: 4px;
}
.doc-outline__back:hover { background: #f3f4f6; }
.doc-outline__title { font-weight: 600; font-size: 13px; color: #1f2937; }
.doc-outline__body { flex: 1; overflow-y: auto; padding: 4px 0; }
.doc-outline__empty { padding: 24px 16px; text-align: center; color: #9ca3af; font-size: 13px; }
.doc-outline__item {
  display: block;
  width: 100%;
  text-align: left;
  padding: 6px 12px;
  border: none;
  background: transparent;
  cursor: pointer;
  font-size: 13px;
  color: #374151;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}
.doc-outline__item:hover { background: #f3f4f6; }
</style>

// src/components/DocumentOutline.tsx
import React, { useEffect, useState } from 'react';
import type { HeadingInfo } from '../utils/headingCollector';
import { MaterialSymbol } from './ui/Icons';

/** @deprecated Use HeadingInfo from utils/headingCollector instead */
export type OutlineHeading = HeadingInfo;

interface DocumentOutlineProps {
  headings: HeadingInfo[];
  onHeadingClick: (pmPos: number) => void;
  onClose: () => void;
  topOffset?: number;
}

export const DocumentOutline: React.FC<DocumentOutlineProps> = ({
  headings,
  onHeadingClick,
  onClose,
  topOffset = 0,
}) => {
  const [open, setOpen] = useState(false);

  useEffect(() => {
    // Trigger slide-in on next frame
    requestAnimationFrame(() => setOpen(true));
  }, []);

  return (
    <nav
      className="docx-outline-nav"
      role="navigation"
      aria-label="Document outline"
      style={{
        position: 'absolute',
        top: topOffset,
        left: 30,
        bottom: 0,
        width: 240,
        display: 'flex',
        flexDirection: 'column',
        overflow: 'hidden',
        fontFamily: "'Google Sans', Roboto, Arial, sans-serif",
        zIndex: 40,
        // Slide-in animation
        transform: open ? 'translateX(0)' : 'translateX(-270px)',
        transition: 'transform 0.15s ease-out',
      }}
      onMouseDown={(e) => e.stopPropagation()}
    >
      {/* Header — back arrow + title */}
      <div
        style={{
          display: 'flex',
          alignItems: 'center',
          gap: 8,
          padding: '16px 16px 12px',
        }}
      >
        <button
          onClick={onClose}
          aria-label="Close outline"
          style={{
            background: 'none',
            border: 'none',
            cursor: 'pointer',
            padding: 4,
            borderRadius: '50%',
            display: 'flex',
            alignItems: 'center',
            color: '#444746',
          }}
          title="Close outline"
        >
          <MaterialSymbol name="arrow_back" size={20} />
        </button>
        <span style={{ fontWeight: 400, fontSize: 14, color: '#1f1f1f', letterSpacing: '0.01em' }}>
          Outline
        </span>
      </div>

      {/* Heading list */}
      <div style={{ overflowY: 'auto', flex: 1, paddingLeft: 20 }}>
        {headings.length === 0 ? (
          <div style={{ padding: '8px 16px', color: '#80868b', fontSize: 13, lineHeight: '20px' }}>
            No headings found. Add headings to your document to see them here.
          </div>
        ) : (
          headings.map((heading, index) => (
            <div
              key={`${heading.pmPos}-${index}`}
              style={{
                marginLeft: heading.level * 12,
              }}
            >
              <button
                className="docx-outline-heading-btn"
                onClick={() => onHeadingClick(heading.pmPos)}
                style={{
                  display: 'block',
                  width: '100%',
                  textAlign: 'left',
                  background: 'none',
                  border: 'none',
                  cursor: 'pointer',
                  padding: '5px 12px',
                  fontSize: 13,
                  fontWeight: 400,
                  color: '#1f1f1f',
                  lineHeight: '18px',
                  whiteSpace: 'nowrap',
                  overflow: 'hidden',
                  textOverflow: 'ellipsis',
                  borderRadius: 0,
                  letterSpacing: '0.01em',
                }}
                title={heading.text}
              >
                {heading.text}
              </button>
            </div>
          ))
        )}
      </div>
    </nav>
  );
};
