// packages/react/src/editor/navigation/parts.tsx
import type { DocxEditorChildren } from '../../docx-editor-children';
// The navigation pane's parts: `DocxEditor.Navigation.Header` / `.Close` / `.Title` /
// `.Tabs` / `.Tab` / `.Headings` / `.Find` / `.Toggle`.
//
// Each reads the pane state from context and renders only its own markup, so a host can
// keep the packaged Headings list while replacing the header, or drop the tab strip and
// pin one tab. Class names carry the look (core stylesheet, `--doc-*` tokens); nothing
// here hard-codes a colour.
//
// EVERY STRING THAT LANDS IN A ROW IS ALREADY BOUNDED. Heading text arrives from
// `Editor.getOutline()` and match text/context from `Editor.findMatches()`, both validated
// at the engine's derivation boundary (length-capped, control characters flattened). These
// components put them in `textContent` only — never in a style string, never in markup.

import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import type { CSSProperties, KeyboardEvent, ReactElement } from 'react';
import type { TextMatch } from '@docx-editor.dev/core/contracts/editor';
import { MaterialSymbol } from '../../components/ui/Icons';
import { selectDocumentAbsent } from '../document-presence';
import { useEditorState } from '../useEditorState';
import { usePlatformShortcut } from '../usePlatformShortcut';
import { useNavigationContext } from './navigation-context';
import { findKeyShortcuts, findShortcutTitle } from './navigation-keys';
// Aliased: this module also EXPORTS a component called `NavigationTab`, and the two
// declarations would collide in the generated .d.ts.
import type { NavigationTab as NavigationTabId } from './useNavigationPane';

/** Shared props for the pane's structural parts. @public */
export interface NavigationPartProps {
  className?: string;
  style?: CSSProperties;
  children?: DocxEditorChildren;
}

/** The tabs the pane supports, in strip order. Module-level so the keyboard handler
 * does not rebuild it (and its dependency identity) on every render. */
const TABS: NavigationTabId[] = ['headings', 'find'];

const cx = (...parts: (string | false | undefined)[]) => parts.filter(Boolean).join(' ');

// ─── Header ──────────────────────────────────────────────────────────────────────────

/**
 * The pane's title row. With no children it renders the close arrow and the title.
 *
 * @public
 */
export function NavigationHeader({
  className,
  style,
  children,
}: NavigationPartProps): ReactElement {
  return (
    <div className={cx('docx-nav__header', className)} style={style}>
      {children ?? (
        <>
          <NavigationClose />
          <NavigationTitle />
        </>
      )}
    </div>
  );
}

/** The back arrow that closes the pane. @public */
export function NavigationClose({ className, style, children }: NavigationPartProps): ReactElement {
  const { intents, t } = useNavigationContext('Close');
  return (
    <button
      type="button"
      className={cx('docx-nav__close', className)}
      style={style}
      aria-label={t('navigation.closeAriaLabel')}
      title={t('navigation.closeTitle')}
      onClick={intents.close}
    >
      {children ?? <MaterialSymbol name="arrow_back" size={20} />}
    </button>
  );
}

/** The pane's heading text. @public */
export function NavigationTitle({ className, style, children }: NavigationPartProps): ReactElement {
  const { t } = useNavigationContext('Title');
  return (
    <h2 className={cx('docx-nav__title', className)} style={style}>
      {children ?? t('navigation.title')}
    </h2>
  );
}

// ─── Tabs ────────────────────────────────────────────────────────────────────────────

/**
 * The tab strip. With no children it renders one `Tab` per tab the pane supports.
 *
 * A real `role="tablist"`, so arrow keys move between tabs and a screen reader announces
 * the panel each one controls.
 *
 * @public
 */
export function NavigationTabs({ className, style, children }: NavigationPartProps): ReactElement {
  const { pane, t } = useNavigationContext('Tabs');

  const onKeyDown = useCallback(
    (event: KeyboardEvent) => {
      const delta = event.key === 'ArrowRight' ? 1 : event.key === 'ArrowLeft' ? -1 : 0;
      if (delta === 0) return;
      event.preventDefault();
      const index = TABS.indexOf(pane.tab);
      pane.setTab(TABS[(index + delta + TABS.length) % TABS.length]!);
    },
    [pane]
  );

  return (
    <div
      className={cx('docx-nav__tabs', className)}
      style={style}
      role="tablist"
      aria-label={t('navigation.title')}
      onKeyDown={onKeyDown}
    >
      {children ?? TABS.map((value) => <NavigationTab key={value} value={value} />)}
    </div>
  );
}

/** Props for one tab. @public */
export interface NavigationTabProps extends NavigationPartProps {
  value: NavigationTabId;
}

/** One tab button. Children replace the label. @public */
export function NavigationTab({
  value,
  className,
  style,
  children,
}: NavigationTabProps): ReactElement {
  const { pane, t } = useNavigationContext('Tab');
  const selected = pane.tab === value;
  return (
    <button
      type="button"
      role="tab"
      id={`docx-nav-tab-${value}`}
      aria-selected={selected}
      aria-controls={`docx-nav-panel-${value}`}
      tabIndex={selected ? 0 : -1}
      className={cx('docx-nav__tab', selected && 'docx-nav__tab--selected', className)}
      style={style}
      onClick={() => pane.setTab(value)}
    >
      {children ?? t(`navigation.tabs.${value}`)}
    </button>
  );
}

// ─── Search box ──────────────────────────────────────────────────────────────────────

function SearchBox({
  value,
  onChange,
  onClear,
  placeholder,
  label,
  clearLabel,
  autoFocus,
  onEnter,
}: {
  value: string;
  onChange: (next: string) => void;
  /** Enter and Shift+Enter, with `backward` true for Shift. */
  onEnter?: (backward: boolean) => void;
  onClear: () => void;
  placeholder: string;
  label: string;
  clearLabel: string;
  autoFocus?: boolean;
}): ReactElement {
  // The find panel stays mounted (hidden or inert) so a typed query survives a close.
  // HTML `autoFocus` only runs on first mount, which is the closed pane — focus when
  // the field actually becomes the visible target.
  const inputRef = useRef<HTMLInputElement>(null);
  useEffect(() => {
    if (!autoFocus) return;
    inputRef.current?.focus();
  }, [autoFocus]);

  return (
    <div className="docx-nav__searchbox">
      <MaterialSymbol name="search" size={18} className="docx-nav__search-icon" />
      <input
        ref={inputRef}
        type="search"
        className="docx-nav__search-input"
        value={value}
        placeholder={placeholder}
        aria-label={label}
        autoFocus={autoFocus}
        onChange={(event) => onChange(event.target.value)}
        onKeyDown={(event) => {
          if (!onEnter || event.key !== 'Enter' || event.nativeEvent.isComposing) return;
          event.preventDefault();
          onEnter(event.shiftKey);
        }}
      />
      {value.length > 0 && (
        <button
          type="button"
          className="docx-nav__search-clear"
          aria-label={clearLabel}
          onClick={onClear}
        >
          <MaterialSymbol name="close" size={16} />
        </button>
      )}
    </div>
  );
}

// ─── Headings tab ────────────────────────────────────────────────────────────────────

/**
 * The heading list, indented by outline depth. Clicking a row moves the caret to that
 * heading and brings it into view.
 *
 * The filter box narrows the list CLIENT-SIDE — it hides rows whose text does not contain
 * what you typed. It is deliberately not the document search: filtering an outline and
 * searching a document are different questions, and the Find tab answers the second one.
 *
 * @public
 */
export function NavigationHeadings({ className, style }: NavigationPartProps): ReactElement {
  const { pane, outline, intents, t } = useNavigationContext('Headings');
  const [filter, setFilter] = useState('');
  // "This document has no headings" is a claim about the document; while there is none
  // (loading, parse failure, detached) the panel shows neither the claim nor the list.
  const documentAbsent = useEditorState(selectDocumentAbsent);

  const items = useMemo(() => {
    const needle = filter.trim().toLowerCase();
    if (needle.length === 0) return outline.items;
    return outline.items.filter((item) => item.heading.text.toLowerCase().includes(needle));
  }, [outline.items, filter]);

  const hidden = pane.tab !== 'headings';

  return (
    <div
      className={cx('docx-nav__panel', className)}
      style={style}
      role="tabpanel"
      id="docx-nav-panel-headings"
      aria-labelledby="docx-nav-tab-headings"
      hidden={hidden}
    >
      <SearchBox
        value={filter}
        onChange={setFilter}
        onClear={() => setFilter('')}
        placeholder={t('navigation.find.placeholder')}
        label={t('navigation.find.inputAriaLabel')}
        clearLabel={t('navigation.find.clearAriaLabel')}
      />
      {documentAbsent ? null : outline.isEmpty ? (
        <p className="docx-nav__empty">{t('navigation.headings.noHeadings')}</p>
      ) : items.length === 0 ? (
        <p className="docx-nav__empty">{t('navigation.find.noResults')}</p>
      ) : (
        <ul className="docx-nav__list">
          {items.map((item, index) => (
            <li key={`${item.heading.blockId}-${index}`}>
              <button
                type="button"
                className={cx(
                  'docx-nav__heading',
                  outline.selectedBlockId === item.heading.blockId && 'docx-nav__heading--current'
                )}
                // Depth is a number the engine derived, not a file string: safe as a
                // computed inline value, and CSS reads it for the indent.
                style={{ paddingInlineStart: `${8 + item.depth * 14}px` }}
                title={item.heading.text}
                onClick={() => {
                  outline.goTo(item.heading.blockId);
                  intents.picked();
                }}
              >
                {item.heading.text}
              </button>
            </li>
          ))}
        </ul>
      )}
    </div>
  );
}

// ─── Find tab ────────────────────────────────────────────────────────────────────────

/** One result row: the match in context, with the matched span emphasised. */
function ResultRow({
  match,
  active,
  onSelect,
}: {
  match: TextMatch;
  active: boolean;
  onSelect: () => void;
}): ReactElement {
  return (
    <li>
      <button
        type="button"
        className={cx('docx-nav__result', active && 'docx-nav__result--active')}
        aria-current={active ? 'true' : undefined}
        onClick={onSelect}
      >
        <span className="docx-nav__result-text">
          {match.contextBefore}
          <mark className="docx-nav__result-hit">{match.text}</mark>
          {match.contextAfter}
        </span>
      </button>
    </li>
  );
}

/**
 * The find panel: a query box, a result counter with previous/next, the match-case and
 * whole-word toggles, and the result list. Selecting a result moves the caret onto the
 * match and reveals its page.
 *
 * @public
 */
export function NavigationFind({ className, style }: NavigationPartProps): ReactElement {
  const { pane, search, intents, t } = useNavigationContext('Find');
  const hidden = pane.tab !== 'find';
  const hasQuery = search.query.trim().length > 0;
  const autoFocus = pane.open && !hidden;

  // Before any navigation nothing is selected, so the readout is a TOTAL, not a position:
  // saying "Result 1 of 7" while the caret has not moved claims a selection that is not
  // there. Once next/previous or a row click has landed, it becomes the position.
  const counter =
    search.matches.length === 0
      ? null
      : search.activeIndex < 0
        ? t(search.truncated ? 'navigation.find.totalTruncated' : 'navigation.find.total', {
            total: search.matches.length,
          })
        : t(search.truncated ? 'navigation.find.counterTruncated' : 'navigation.find.counter', {
            current: search.activeIndex + 1,
            total: search.matches.length,
          });

  return (
    <div
      className={cx('docx-nav__panel', className)}
      style={style}
      role="tabpanel"
      id="docx-nav-panel-find"
      aria-labelledby="docx-nav-tab-find"
      hidden={hidden}
    >
      <SearchBox
        value={search.query}
        onChange={search.setQuery}
        onClear={search.clear}
        placeholder={t('navigation.find.placeholder')}
        label={t('navigation.find.inputAriaLabel')}
        clearLabel={t('navigation.find.clearAriaLabel')}
        autoFocus={autoFocus}
        onEnter={(backward) => {
          // Enter runs a query still waiting for its debounce, then moves to a match.
          if (search.isPending) search.find(search.query);
          if (backward) search.previous();
          else search.next();
        }}
      />

      <div
        className="docx-nav__options"
        role="group"
        aria-label={t('navigation.find.optionsAriaLabel')}
      >
        <label className="docx-nav__option">
          <input
            type="checkbox"
            checked={search.matchCase}
            onChange={(event) => search.setMatchCase(event.target.checked)}
          />
          {t('navigation.find.matchCase')}
        </label>
        <label className="docx-nav__option">
          <input
            type="checkbox"
            checked={search.wholeWord}
            onChange={(event) => search.setWholeWord(event.target.checked)}
          />
          {t('navigation.find.wholeWord')}
        </label>
      </div>

      <div className="docx-nav__resultbar">
        <span className="docx-nav__count" aria-live="polite">
          {/* Nothing typed says nothing: an empty box is not "no results". */}
          {!hasQuery
            ? ''
            : search.isPending
              ? t('navigation.find.searching')
              : (counter ?? t('navigation.find.noResults'))}
        </span>
        <span className="docx-nav__steppers">
          <button
            type="button"
            className="docx-nav__stepper"
            aria-label={t('navigation.find.previousAriaLabel')}
            disabled={search.matches.length === 0}
            onClick={search.previous}
          >
            <MaterialSymbol name="keyboard_arrow_up" size={18} />
          </button>
          <button
            type="button"
            className="docx-nav__stepper"
            aria-label={t('navigation.find.nextAriaLabel')}
            disabled={search.matches.length === 0}
            onClick={search.next}
          >
            <MaterialSymbol name="keyboard_arrow_down" size={18} />
          </button>
        </span>
      </div>

      {search.matches.length > 0 && (
        <ul className="docx-nav__list" aria-label={t('navigation.find.resultsAriaLabel')}>
          {search.matches.map((match, index) => (
            <ResultRow
              key={`${match.blockId}-${match.start}-${index}`}
              match={match}
              active={index === search.activeIndex}
              onSelect={() => {
                search.goTo(index);
                intents.picked();
              }}
            />
          ))}
        </ul>
      )}
    </div>
  );
}

// ─── Toggle ──────────────────────────────────────────────────────────────────────────

/**
 * The collapsed pane's disc button. `DocxEditor.Navigation` renders one for you while the
 * pane is closed; place it yourself (a toolbar, a menu) with `toggle={false}` on the root.
 *
 * @public
 */
export function NavigationToggle({
  className,
  style,
  children,
}: NavigationPartProps): ReactElement {
  const { pane, intents, findShortcut, t } = useNavigationContext('Toggle');
  const shortcut = usePlatformShortcut();
  // Names the Find shortcut, the one way to open the pane besides this disc, only while it
  // is bound.
  const label = shortcut('Ctrl+F');
  const keyShortcuts = findShortcut ? findKeyShortcuts(label) : undefined;
  const title = findShortcut
    ? findShortcutTitle(t('navigation.openTitle'), label)
    : t('navigation.openTitle');
  return (
    <button
      type="button"
      className={cx('docx-nav__toggle', className)}
      style={style}
      aria-label={t('navigation.openAriaLabel')}
      aria-expanded={pane.open}
      aria-keyshortcuts={keyShortcuts}
      title={title}
      // A mousedown that reaches the document surface moves the caret; the pane opening
      // must leave the user's place in the text alone.
      onMouseDown={(event) => event.preventDefault()}
      onClick={intents.toggle}
    >
      {children ?? <MaterialSymbol name="toc" size={20} />}
    </button>
  );
}

// packages/vue/src/editor/navigation/parts.tsx
import {
  computed,
  defineComponent,
  onMounted,
  ref,
  watch,
  type CSSProperties,
  type PropType,
} from 'vue';
import type { TextMatch } from '@docx-editor.dev/core/contracts/editor';
import { MaterialSymbol } from '../../components/ui/Icons';
import { selectDocumentAbsent } from '../document-presence';
import { useEditorState } from '../useEditorState';
import { usePlatformShortcut } from '../usePlatformShortcut';
import { useLiveNavigationContext } from './navigation-context';
import { findKeyShortcuts } from './navigation-keys';
import type { NavigationTab as NavigationTabId } from './useNavigationPane';

import type { DocxEditorChildren } from '../../docx-editor-children';

/** Shared props for the pane's structural parts. @public */
export interface NavigationPartProps {
  className?: string;
  style?: CSSProperties;
  children?: DocxEditorChildren;
}

/** @public */
export interface NavigationTabProps extends NavigationPartProps {
  value: NavigationTabId;
}

const TABS: NavigationTabId[] = ['headings', 'find'];

const cx = (...parts: (string | false | undefined)[]) => parts.filter(Boolean).join(' ');

/** @public */
export const NavigationHeader = defineComponent({
  name: 'NavigationHeader',
  props: {
    className: { type: String, default: undefined },
    style: { type: Object as PropType<CSSProperties>, default: undefined },
  },
  setup(props, { slots }) {
    return () => (
      <div class={cx('docx-nav__header', props.className)} style={props.style}>
        {slots.default?.() ?? (
          <>
            <NavigationClose />
            <NavigationTitle />
          </>
        )}
      </div>
    );
  },
});

/** @public */
export const NavigationClose = defineComponent({
  name: 'NavigationClose',
  props: {
    className: { type: String, default: undefined },
    style: { type: Object as PropType<CSSProperties>, default: undefined },
  },
  setup(props, { slots }) {
    // Live: `t` and the intents follow the pane's props without a remount.
    const nav = useLiveNavigationContext('Close');
    const t = (key: string, params?: Record<string, string | number>) => nav.t(key, params);
    const intents = {
      toggle: () => nav.intents.toggle(),
      close: () => nav.intents.close(),
      picked: () => nav.intents.picked(),
    };
    return () => (
      <button
        type="button"
        class={cx('docx-nav__close', props.className)}
        style={props.style}
        aria-label={t('navigation.closeAriaLabel')}
        title={t('navigation.closeTitle')}
        onClick={intents.close}
      >
        {slots.default?.() ?? <MaterialSymbol name="arrow_back" size={20} />}
      </button>
    );
  },
});

/** @public */
export const NavigationTitle = defineComponent({
  name: 'NavigationTitle',
  props: {
    className: { type: String, default: undefined },
    style: { type: Object as PropType<CSSProperties>, default: undefined },
  },
  setup(props, { slots }) {
    // Live: `t` and the intents follow the pane's props without a remount.
    const nav = useLiveNavigationContext('Title');
    const t = (key: string, params?: Record<string, string | number>) => nav.t(key, params);
    return () => (
      <h2 class={cx('docx-nav__title', props.className)} style={props.style}>
        {slots.default?.() ?? t('navigation.title')}
      </h2>
    );
  },
});

/** @public */
export const NavigationTabs = defineComponent({
  name: 'NavigationTabs',
  props: {
    className: { type: String, default: undefined },
    style: { type: Object as PropType<CSSProperties>, default: undefined },
  },
  setup(props, { slots }) {
    // Live: `t` and the intents follow the pane's props without a remount.
    const nav = useLiveNavigationContext('Tabs');
    const { pane } = nav;
    const t = (key: string, params?: Record<string, string | number>) => nav.t(key, params);
    const onKeyDown = (event: KeyboardEvent) => {
      const delta = event.key === 'ArrowRight' ? 1 : event.key === 'ArrowLeft' ? -1 : 0;
      if (delta === 0) return;
      event.preventDefault();
      const index = TABS.indexOf(pane.tab.value);
      pane.setTab(TABS[(index + delta + TABS.length) % TABS.length]!);
    };
    return () => (
      <div
        class={cx('docx-nav__tabs', props.className)}
        style={props.style}
        role="tablist"
        aria-label={t('navigation.title')}
        onKeydown={onKeyDown}
      >
        {slots.default?.() ?? TABS.map((value) => <NavigationTab key={value} value={value} />)}
      </div>
    );
  },
});

/** @public */
export const NavigationTab = defineComponent({
  name: 'NavigationTab',
  props: {
    value: { type: String as PropType<NavigationTabId>, required: true },
    className: { type: String, default: undefined },
    style: { type: Object as PropType<CSSProperties>, default: undefined },
  },
  setup(props, { slots }) {
    // Live: `t` and the intents follow the pane's props without a remount.
    const nav = useLiveNavigationContext('Tab');
    const { pane } = nav;
    const t = (key: string, params?: Record<string, string | number>) => nav.t(key, params);
    return () => {
      const selected = pane.tab.value === props.value;
      return (
        <button
          type="button"
          role="tab"
          id={`docx-nav-tab-${props.value}`}
          aria-selected={selected}
          aria-controls={`docx-nav-panel-${props.value}`}
          tabindex={selected ? 0 : -1}
          class={cx('docx-nav__tab', selected && 'docx-nav__tab--selected', props.className)}
          style={props.style}
          onClick={() => pane.setTab(props.value)}
        >
          {slots.default?.() ?? t(`navigation.tabs.${props.value}`)}
        </button>
      );
    };
  },
});

const SearchBox = defineComponent({
  name: 'SearchBox',
  props: {
    value: { type: String, required: true },
    onChange: { type: Function as PropType<(next: string) => void>, required: true },
    onClear: { type: Function as PropType<() => void>, required: true },
    placeholder: { type: String, required: true },
    label: { type: String, required: true },
    clearLabel: { type: String, required: true },
    autoFocus: { type: Boolean, default: undefined },
    /** Enter and Shift+Enter, with `backward` true for Shift. */
    onEnter: { type: Function as PropType<(backward: boolean) => void>, default: undefined },
  },
  setup(props) {
    // The find panel stays mounted (hidden or inert) so a typed query survives a close.
    // HTML autofocus only runs on first mount, which is the closed pane — focus when
    // the field actually becomes the visible target.
    const inputRef = ref<HTMLInputElement | null>(null);
    const focusIfRequested = () => {
      if (props.autoFocus) inputRef.value?.focus();
    };
    onMounted(focusIfRequested);
    watch(() => props.autoFocus, focusIfRequested, { flush: 'post' });
    return () => (
      <div class="docx-nav__searchbox">
        <MaterialSymbol name="search" size={18} className="docx-nav__search-icon" />
        <input
          ref={inputRef}
          type="search"
          class="docx-nav__search-input"
          value={props.value}
          placeholder={props.placeholder}
          aria-label={props.label}
          autofocus={props.autoFocus}
          onInput={(event) => props.onChange((event.target as HTMLInputElement).value)}
          onKeydown={(event: KeyboardEvent) => {
            if (!props.onEnter || event.key !== 'Enter' || event.isComposing) return;
            event.preventDefault();
            props.onEnter(event.shiftKey);
          }}
        />
        {props.value.length > 0 && (
          <button
            type="button"
            class="docx-nav__search-clear"
            aria-label={props.clearLabel}
            onClick={props.onClear}
          >
            <MaterialSymbol name="close" size={16} />
          </button>
        )}
      </div>
    );
  },
});

/** @public */
export const NavigationHeadings = defineComponent({
  name: 'NavigationHeadings',
  props: {
    className: { type: String, default: undefined },
    style: { type: Object as PropType<CSSProperties>, default: undefined },
  },
  setup(props) {
    // Live: `t` and the intents follow the pane's props without a remount.
    const nav = useLiveNavigationContext('Headings');
    const { pane, outline } = nav;
    const t = (key: string, params?: Record<string, string | number>) => nav.t(key, params);
    const intents = {
      toggle: () => nav.intents.toggle(),
      close: () => nav.intents.close(),
      picked: () => nav.intents.picked(),
    };
    const filter = ref('');
    const documentAbsent = useEditorState(selectDocumentAbsent);
    const items = computed(() => {
      const needle = filter.value.trim().toLowerCase();
      if (needle.length === 0) return outline.items.value;
      return outline.items.value.filter((item) => item.heading.text.toLowerCase().includes(needle));
    });
    return () => {
      const hidden = pane.tab.value !== 'headings';
      return (
        <div
          class={cx('docx-nav__panel', props.className)}
          style={props.style}
          role="tabpanel"
          id="docx-nav-panel-headings"
          aria-labelledby="docx-nav-tab-headings"
          hidden={hidden}
        >
          <SearchBox
            value={filter.value}
            onChange={(next) => {
              filter.value = next;
            }}
            onClear={() => {
              filter.value = '';
            }}
            placeholder={t('navigation.find.placeholder')}
            label={t('navigation.find.inputAriaLabel')}
            clearLabel={t('navigation.find.clearAriaLabel')}
          />
          {documentAbsent.value ? null : outline.isEmpty.value ? (
            <p class="docx-nav__empty">{t('navigation.headings.noHeadings')}</p>
          ) : items.value.length === 0 ? (
            <p class="docx-nav__empty">{t('navigation.find.noResults')}</p>
          ) : (
            <ul class="docx-nav__list">
              {items.value.map((item, index) => (
                <li key={`${item.heading.blockId}-${index}`}>
                  <button
                    type="button"
                    class={cx(
                      'docx-nav__heading',
                      outline.selectedBlockId.value === item.heading.blockId &&
                        'docx-nav__heading--current'
                    )}
                    style={{ paddingInlineStart: `${8 + item.depth * 14}px` }}
                    title={item.heading.text}
                    onClick={() => {
                      outline.goTo(item.heading.blockId);
                      intents.picked();
                    }}
                  >
                    {item.heading.text}
                  </button>
                </li>
              ))}
            </ul>
          )}
        </div>
      );
    };
  },
});

const ResultRow = defineComponent({
  name: 'ResultRow',
  props: {
    match: { type: Object as PropType<TextMatch>, required: true },
    active: { type: Boolean, required: true },
    onSelect: { type: Function as PropType<() => void>, required: true },
  },
  setup(props) {
    return () => (
      <li>
        <button
          type="button"
          class={cx('docx-nav__result', props.active && 'docx-nav__result--active')}
          aria-current={props.active ? 'true' : undefined}
          onClick={props.onSelect}
        >
          <span class="docx-nav__result-text">
            {props.match.contextBefore}
            <mark class="docx-nav__result-hit">{props.match.text}</mark>
            {props.match.contextAfter}
          </span>
        </button>
      </li>
    );
  },
});

/** @public */
export const NavigationFind = defineComponent({
  name: 'NavigationFind',
  props: {
    className: { type: String, default: undefined },
    style: { type: Object as PropType<CSSProperties>, default: undefined },
  },
  setup(props) {
    // Live: `t` and the intents follow the pane's props without a remount.
    const nav = useLiveNavigationContext('Find');
    const { pane, search } = nav;
    const t = (key: string, params?: Record<string, string | number>) => nav.t(key, params);
    const intents = {
      toggle: () => nav.intents.toggle(),
      close: () => nav.intents.close(),
      picked: () => nav.intents.picked(),
    };
    return () => {
      const hidden = pane.tab.value !== 'find';
      const autoFocus = pane.open.value && !hidden;
      const hasQuery = search.query.value.trim().length > 0;
      const counter =
        search.matches.value.length === 0
          ? null
          : search.activeIndex.value < 0
            ? t(
                search.truncated.value ? 'navigation.find.totalTruncated' : 'navigation.find.total',
                {
                  total: search.matches.value.length,
                }
              )
            : t(
                search.truncated.value
                  ? 'navigation.find.counterTruncated'
                  : 'navigation.find.counter',
                {
                  current: search.activeIndex.value + 1,
                  total: search.matches.value.length,
                }
              );
      return (
        <div
          class={cx('docx-nav__panel', props.className)}
          style={props.style}
          role="tabpanel"
          id="docx-nav-panel-find"
          aria-labelledby="docx-nav-tab-find"
          hidden={hidden}
        >
          <SearchBox
            value={search.query.value}
            onChange={search.setQuery}
            onClear={search.clear}
            placeholder={t('navigation.find.placeholder')}
            label={t('navigation.find.inputAriaLabel')}
            clearLabel={t('navigation.find.clearAriaLabel')}
            autoFocus={autoFocus}
            onEnter={(backward: boolean) => {
              // Enter runs a query still waiting for its debounce, then moves to a match.
              if (search.isPending.value) search.find(search.query.value);
              if (backward) search.previous();
              else search.next();
            }}
          />
          <div
            class="docx-nav__options"
            role="group"
            aria-label={t('navigation.find.optionsAriaLabel')}
          >
            <label class="docx-nav__option">
              <input
                type="checkbox"
                checked={search.matchCase.value}
                onChange={(event) =>
                  search.setMatchCase((event.target as HTMLInputElement).checked)
                }
              />
              {t('navigation.find.matchCase')}
            </label>
            <label class="docx-nav__option">
              <input
                type="checkbox"
                checked={search.wholeWord.value}
                onChange={(event) =>
                  search.setWholeWord((event.target as HTMLInputElement).checked)
                }
              />
              {t('navigation.find.wholeWord')}
            </label>
          </div>
          <div class="docx-nav__resultbar">
            <span class="docx-nav__count" aria-live="polite">
              {!hasQuery
                ? ''
                : search.isPending.value
                  ? t('navigation.find.searching')
                  : (counter ?? t('navigation.find.noResults'))}
            </span>
            <span class="docx-nav__steppers">
              <button
                type="button"
                class="docx-nav__stepper"
                aria-label={t('navigation.find.previousAriaLabel')}
                disabled={search.matches.value.length === 0}
                onClick={search.previous}
              >
                <MaterialSymbol name="keyboard_arrow_up" size={18} />
              </button>
              <button
                type="button"
                class="docx-nav__stepper"
                aria-label={t('navigation.find.nextAriaLabel')}
                disabled={search.matches.value.length === 0}
                onClick={search.next}
              >
                <MaterialSymbol name="keyboard_arrow_down" size={18} />
              </button>
            </span>
          </div>
          {search.matches.value.length > 0 && (
            <ul class="docx-nav__list" aria-label={t('navigation.find.resultsAriaLabel')}>
              {search.matches.value.map((match, index) => (
                <ResultRow
                  key={`${match.blockId}-${match.start}-${index}`}
                  match={match}
                  active={index === search.activeIndex.value}
                  onSelect={() => {
                    search.goTo(index);
                    intents.picked();
                  }}
                />
              ))}
            </ul>
          )}
        </div>
      );
    };
  },
});

/** @public */
export const NavigationToggle = defineComponent({
  name: 'NavigationToggle',
  props: {
    className: { type: String, default: undefined },
    style: { type: Object as PropType<CSSProperties>, default: undefined },
  },
  setup(props, { slots }) {
    // Read in render, not destructured here: `t` and `findShortcut` are pane props that a
    // host can change while the disc stays mounted.
    const context = useLiveNavigationContext('Toggle');
    const shortcut = usePlatformShortcut();
    return () => {
      const { pane, intents, findShortcut, t } = context;
      const label = shortcut('Ctrl+F');
      return (
        <button
          type="button"
          class={cx('docx-nav__toggle', props.className)}
          style={props.style}
          aria-label={t('navigation.openAriaLabel')}
          aria-expanded={pane.open.value}
          // Names the Find shortcut, the one way to open the pane besides this disc, only
          // while it is bound.
          aria-keyshortcuts={findShortcut ? findKeyShortcuts(label) : undefined}
          title={
            findShortcut
              ? // The resolved label goes in as a parameter, never as catalog text: a translated
                // modifier (German "Strg") would name a key that does not open Find on macOS.
                t('navigation.openShortcutTitle', { shortcut: label })
              : t('navigation.openTitle')
          }
          onMousedown={(event) => event.preventDefault()}
          onClick={intents.toggle}
        >
          {slots.default?.() ?? <MaterialSymbol name="toc" size={20} />}
        </button>
      );
    };
  },
});
